Added missing fields to the Activity object
Javacord/Javacord pull request #1000
Opened 2022-05-17 16:17 UTC by RealYusufIsmail

I have added the missing fields for the Activity Object.

Also closes #999

2022-05-17 16:27 UTC, RealYusufIsmail commented
@KILLEliteMaste should I just use int for createdAt or something else?

2022-05-19 17:41 UTC, KILLEliteMaste requested changes

2022-05-19 17:41 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/activity/ActivityButtonsImpl.java
> +    public ActivityButtonsImpl(ActivityImpl activity, JsonNode data) {
Why do you pass the activity object and do nothing with it? Either remove it or just add another method to actually get it.

2022-05-19 17:41 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/activity/ActivityImpl.java
> +        this.createdAt = OffsetDateTime.parse(data.get("created_at").asText()).toInstant();
I don't think that will work
```suggestion
        this.createdAt = Instant.ofEpochMilli(data.get("created_at").asLong());
```

2022-05-19 17:41 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/activity/ActivitySecretsImpl.java
> +    public ActivitySecretsImpl(ActivityImpl activity, JsonNode data) {
See ActivityButtonImpl

2022-05-19 17:41 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/activity/ActivityImpl.java
> +        return Optional.of(buttons);
Since the list is always initialized, it doesn't make sense to return an optional

2022-05-19 17:41 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/activity/ActivitySecretsImpl.java
> +        }
Use the ternary operator to initialize the variables, so it doesn't take that many LoC

2022-05-20 17:24 UTC, KILLEliteMaste requested changes

2022-05-20 17:24 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +     * @return The time at which the activity was added/changed by the user.
You forgot to reformat this Javadoc

2022-05-20 17:24 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/activity/ActivityButtonsImpl.java
> +     * @param data The json data of the buttons.
You didn't reformat this Javadoc

2022-05-20 17:24 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/activity/ActivitySecretsImpl.java
> +     * @param data The json data of the activity.
You didn't reformat this Javadoc

2022-05-20 17:59 UTC, KILLEliteMaste approved these changes
LGTM!

2022-05-20 17:59 UTC, merged