Add support for creating, updating, deleting and bulk overwriting slash commands without Server instance.
Javacord/Javacord pull request #1001
Opened 2022-05-18 02:32 UTC by ShindouMihou

This adds additional support for methods that enable creating, updating, and deleting slash commands without the need for a Server instance. The primary motivation for this is to allow the ability to perform those actions regardless of the shard and cluster, in our case, we only needed the first shard to perform the necessary actions to keep the commands up-to-date.

- `bulkOverwriteServerApplicationCommands(long server, List<? extends ApplicationCommandBuilder<?, ?, ?>> applicationCommandBuilderList)`
- `deleteForServer(long server);`
- `createForServer(DiscordApi api, long server)`
- `updateForServer(DiscordApi api, long server)`

This also modifies the behavior of `ApplicationCommand` to store the server id instead of the Server instance but keeps the same Optional behavior for when the command isn't of a server slash command. (I'd be happy to get some notes if this does any bad side effect).

✅ The PR is tested to work for quite some time, although still unsure of the side effects of modifying the behavior of `ApplicationCommand`.

2022-05-19 15:49 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/DiscordApi.java
> +    /**
Can't select it but you can delegate the method here in the interface to your newly introduced method so we only have 1 implementation

2022-05-19 15:51 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
>          return delegate.createForServer(server);
Delegate the call to your new method and then you can also remove the methods from the Delegates for this specific method

2022-05-19 16:07 UTC, ShindouMihou commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java
> +     * Deletes this application command globally.
This is actually a comment issue from the original method (I copied the method without looking at the method) 😆 
https://github.com/BeemoBot/Javacord/blob/13a44ef17964c82c7a796ce722cebd822053040f/javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java#L80

I'll fix it up on this PR though.

2022-05-19 17:02 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/DiscordApi.java
> +    /**
Basically instead of how it's like now you do
```java
default CompletableFuture<List<ApplicationCommand>> bulkOverwriteServerApplicationCommands(
            Server server,
            List<? extends ApplicationCommandBuilder<?, ?, ?>> applicationCommandBuilderList){
return bulkOverwriteServerApplicationCommands(server.getId(), applicationCommandBuilderList)
}
```

2022-05-25 21:06 UTC, ShindouMihou commented
I should have applied all the following suggestions with the ApplicationCommand's `server` and `serverId` both added in `ApplicationCommand` as a compromise (https://discord.com/channels/151037561152733184/354648262453624833/976895755518353408) which works well for determining the status of the command itself (whether it's a server application command or a global application command).

It's not squashed ahead since I think I might want more checks to see whether all the suggestions were actually applied properly or all the suggestions were really applied. 💯

2022-05-26 12:46 UTC, KILLEliteMaste requested changes

2022-05-26 12:46 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandImpl.java
> +    private final long serverId;
Can be null as you are now doing checks if the `id == 0L` when it is not available. Also simplifies the return type of `getServerId()` with `Optional.ofNullable(serverId)`

2022-05-26 12:48 UTC, ShindouMihou commented on javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandImpl.java
> +    private final long serverId;
I tried setting this as null before but Java doesn't allow primitive types to be null. I could set it to the Long class instead which is nullable.

2022-05-26 12:51 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandImpl.java
> +    private final long serverId;
Exactly, doesn't really make sense to have it as a primitive type since you return `Long` in the getteranyway

2022-05-26 12:55 UTC, KILLEliteMaste requested changes

2022-05-28 08:58 UTC, ShindouMihou commented
Applied the remaining suggestions and squashed into a single commit, should be ready to go if there aren't any more suggestions.

2022-05-28 11:01 UTC, KILLEliteMaste requested changes
LGTM!

2022-05-28 11:01 UTC, KILLEliteMaste approved these changes
LGTM!

2022-05-28 11:01 UTC, merged