Rework application command permissions for permissions v2
Javacord/Javacord pull request #1004
Opened 2022-05-25 18:45 UTC by Mysterypotatoguy

Reworks application commands for permissions v2

Adds the new `default_member_permissions` and `dm_permission` functionality
Removes the old `default_permission` functionality
Adds the `APPLICATION_COMMAND_PERMISSIONS_UPDATE` event
Adds some audit log handling for the new log type

I tried to use some more friendly names for the builder/updater methods, but I'm open to any renaming suggestions as I'm not sure they are 100% clear.

Closes #992

2022-05-25 21:47 UTC, KILLEliteMaste requested changes

2022-05-25 21:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandUpdater.java
> +    public T setDefaultRequiredPermissions(PermissionType... requiredPermissions) {
Same here with the comments in the `ApplicationCommandBuilder`

2022-05-25 21:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/event/server/ApplicationCommandPermissionsUpdateEvent.java
> +    Collection<ApplicationCommandPermissions> getUpdatedPermissions();
Should be a `Set` since this will not contain duplicates

2022-05-25 21:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java
> +    boolean isDisabledByDefault();
See `ApplicationCommandBuilder`

2022-05-25 21:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissions.java
> +    boolean affectsAllChannels();
You forgot to add a method to check if `@everyone` is affected. To simplify this you can also directly add a `getServer` method so you just need to implement them in the interface.

https://discord.com/developers/docs/interactions/application-commands#application-command-permissions-object-application-command-permissions-constants

2022-05-25 21:50 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissions.java
> +    boolean affectsAllChannels();
The `@everyone` role is the `guild_id` so it will fetch correctly

2022-05-25 21:54 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissions.java
> +    boolean affectsAllChannels();
I am not sure what you mean by that. What I asked for was a `affectsEveryone` method which return true if the id is the server id or is this not "needed"?

2022-05-25 21:56 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
> +     * Passing no arguments will cause the command to be available to all users.
Hmm, I do like this solution because it removes the overwriting behaviour of trying to use both `setDefaultRequiredPermissions` and `setDisabledByDefault`, but the `null` behaviour seems very odd to me

2022-05-26 12:30 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
> +     * Passing no arguments will cause the command to be available to all users.
I just think this is confusing. I didn't get what this was doing until I looked at the implementation where I saw both methods change the `defaultMemberPermissions` variable.

2022-05-29 18:10 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
> +     * Passing no arguments will cause the command to be available to all users.
After thinking about it I can agree that passing `null` is pretty odd in Javacord. It doesn't fit in the style of everything else. What do you think about renaming the method to `setDefaultRequiredPermissionsDisabled` ?

2022-05-29 23:26 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
> +     * Passing no arguments will cause the command to be available to all users.
If you mean for the `null` argument proposed above I don't think that's clearer than `setDisabledByDefault`. It sounds more like there are _no_ required permissions

2022-05-29 23:34 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissions.java
> +    boolean affectsAllChannels();
I see, that would be fine but it's just a shortcut for `getRole() == @everyone`

2022-05-30 08:02 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissions.java
> +    boolean affectsAllChannels();
Yes but it's a special case of a role, which may be used more often or differently than if it just affects a general role. And nothings wrong about convenience methods :)

2022-05-30 08:04 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
> +     * Passing no arguments will cause the command to be available to all users.
That's not what I said. I agree with what you said and therefore proposed to change the name of the method from `setDisabledByDefault` to `setDefaultRequiredPermissionsDisabled` as imo it is not clear that they change the same thing just from looking at the method name.

2022-06-18 10:37 UTC, KILLEliteMaste requested changes
Please also add convenience methods that take this param in, in the `SlashCommand` and the 2 ContextMenu command interfaces. If you are so kind can you also add the missing convenience method for context menus with `name` and `description`? :)

2022-06-18 10:37 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandPermissionsImpl.java
> +    }
Please add a `getServer` method and then you are able to use a default implementation in the interface

2022-06-18 10:37 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
> +    public T setDefaultEnabledForPermissions(PermissionType... requiredPermissions) {
Please overload with an `EnumSet` param

2022-06-18 10:37 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/internal/ApplicationCommandUpdaterDelegate.java
> +    void setDefaultEnabledForPermissions(PermissionType... requiredPermissions);
Same param overloading here

2022-06-19 12:06 UTC, KILLEliteMaste approved these changes
Did the final last things that were left, otherwise LGTM!

2022-06-19 12:08 UTC, merged