Adds support for Attachment options in Slash Commands.
Javacord/Javacord pull request #1015
Opened 2022-06-16 18:02 UTC by ShindouMihou

This patch adds support for the attachment option type in slash commands and fixes #958. It's a simple change that creates a new `Attachment` class containing shared properties with `MessageAttachment` and `Attachment`. 

✅ Tested with multiple attachments and has been verified to work.

2022-06-16 19:11 UTC, KILLEliteMaste requested changes
The `SlashCommandOption` interface should have the convenience methods for attachments too

2022-06-16 19:53 UTC, montlikadani commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandInteractionImpl.java
> +                    }
```suggestion
                    resolvedAttachments.computeIfAbsent(Long.parseLong(attachmentNode.getKey()), id -> new AttachmentImpl(api, attachmentData));
```
With `computeIfAbsent` I think looks better

2022-06-16 21:42 UTC, ShindouMihou commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandInteractionImpl.java
> +                    }
I do agree. That section of the code is simply a copy of what was written for `resolvedUsers` as well.

2022-06-16 22:01 UTC, ShindouMihou commented
Applied all suggestions from KILLEliteMaste. I didn't apply the last one since I think it's better for now to keep the same style as the other resolved data such as `resolvedMembers` and `resolvedUsers`.

2022-06-16 22:32 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandInteractionImpl.java
> +                    }
In that case it doesn't make sense to copy it from the users. The users need it because of how Javacord works (user == member object). If we did not do this check we would simply overwrite the user which contains the member.
It is not wrong, but also not needed. I would suggest to apply this suggestion for both (user / attachment) or just do a simple `put` for users as it looks cleaner.

2022-06-16 22:59 UTC, ShindouMihou commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandInteractionImpl.java
> +                    }
Actually yeah, that made sense. I think my brain went offline while looking at this suggestion. A simple `put` should just do the trick in this scenario.

2022-06-17 08:50 UTC, ShindouMihou commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandInteractionImpl.java
> +                    }
Applied the following changes, thanks for the input! 🧇

2022-06-17 09:07 UTC, KILLEliteMaste approved these changes
LGTM!

2022-06-17 09:07 UTC, merged