Allow scheduled / delayed deletes
Javacord/Javacord pull request #1038
Opened 2022-06-26 17:37 UTC by Saladoc

This PR introduces a `Deletable` interface which takes over the existing deletion methods and introduces new ones for the scheduled deletion. Basically this is a do-over of the PR made by @cap5lut, incorporating the ideas from the discussion in #630.

I suggest either one of this and #630 to be merged and the other closed.

2022-07-13 17:07 UTC, KILLEliteMaste requested changes

2022-07-18 22:24 UTC, Mysterypotatoguy requested changes
Looks good from the API side, just a couple of entities missing for `Deletable`:
`Server`, `Role`, `MessageSet`(?)

n.b. `MessageSet` current implements as `deleteAll()` so unsure if this should be included

2022-07-18 22:27 UTC, Saladoc commented
`MessageSet` should not be `Deleteable` as per the interface since it does not represent a singular deletable entity, but a collection of them. The other ones I will update.

2022-07-21 15:01 UTC, KILLEliteMaste requested changes

2022-07-21 18:45 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +    }
Applied and tested those changes, discord does not complain about the header.

2022-07-21 18:51 UTC, KILLEliteMaste approved these changes
LGTM!

2022-10-03 08:34 UTC, Saladoc commented
reopening after accidental branch deletion

2022-10-03 08:43 UTC, Mysterypotatoguy approved these changes

2022-10-03 09:19 UTC, merged