Adds support for `min_length` and `max_length` for `String` in Slash Commands.
Javacord/Javacord pull request #1047
Opened 2022-07-10 14:02 UTC by ShindouMihou

This PR adds the newly implemented `min_length` and `max_length` for String options in Slash Commands. The documentations states `integer` for the parameter (same as for `INTEGER`) but seeing that `INTEGER` uses the `long` type, I decided to use the `long` type as well since I remembered that Discord's integer is longer than Java's integer.

☑️ This PR has been tested and works as intended.
![image](https://user-images.githubusercontent.com/69381903/178148169-c8341e65-40f9-4a1a-b17f-66f1fdb3c25e.png)

2022-07-13 16:20 UTC, KILLEliteMaste requested changes

2022-07-13 16:20 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOption.java
> +    Optional<Long> getStringMaxLength();
I think they should be called more generic. We Use `Long` for the LONG type and `Double` for DECIMAL as the docs tell us. Because this is not bound to something, I think this should be a more generic name like `getMinLength` as this option might be used for other command option types in the future or what do you think about this?

2022-07-13 16:20 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOptionBuilder.java
> +
Remove blank line

2022-07-19 16:22 UTC, ShindouMihou commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOption.java
> +    Optional<Long> getStringMaxLength();
I decided to follow through with the generic name instead. 🌮

2022-07-19 20:17 UTC, KILLEliteMaste requested changes

2022-07-19 20:17 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOptionBuilder.java
> +    public SlashCommandOptionBuilder setStringMaxLength(long stringMaxLength) {
You forgot to rename these

2022-07-19 21:27 UTC, ShindouMihou commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOptionBuilder.java
> +    public SlashCommandOptionBuilder setStringMaxLength(long stringMaxLength) {
Yeah, I didn't notice. Thanks for the heads up! I double-checked just now and it should all be renamed properly. 🌮

2022-07-19 21:41 UTC, KILLEliteMaste approved these changes
LGTM!

2022-07-19 21:41 UTC, merged