Updated discord api to v10
Javacord/Javacord pull request #1073
Opened 2022-08-05 20:44 UTC by RealYusufIsmail

I have updated the discord api version to 10

closes #960

TODO:
- [x] tweak identifying payload
- [x] add all the changes for the new version.

2022-08-05 22:39 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/InteractionMessageBuilderDelegateImpl.java
> +                tempAttachments.remove(new FileContainer(stream, attachment.getFileName()));
Removes the attachments that are wanted. Change this

2022-08-05 23:17 UTC, RealYusufIsmail commented
Apart from a few changes I am pretty much done. @KILLEliteMaste can you review this please.

2022-08-06 12:50 UTC, KILLEliteMaste commented
Why did you close #994 and opened a new PR?

2022-08-06 12:55 UTC, RealYusufIsmail commented
> Member

it was messy and some stuff was messed up.

2022-08-06 13:21 UTC, KILLEliteMaste commented
Not a valid reason imo. It's not like the PR is deleted. Anyway continue in this PR for now and please do not open unnecessary PRs

2022-08-06 14:40 UTC, RealYusufIsmail commented
> Not a valid reason imo. It's not like the PR is deleted. Anyway continue in this PR for now and please do not open unnecessary PRs

ok

2022-08-06 14:59 UTC, KILLEliteMaste requested changes
The attachment changes in you current implementation are only available in interactions. You are missing updating attachments for normal messages.

Did you really test your changes with actual code if they meet the requirements discussed in our Discord?

2022-08-06 14:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/intent/Intent.java
> +     * This is required to receive non-empty values for content fields (content, attachments, embeds, and components).
```suggestion
     * This is required to receive non-empty values for content fields (content, attachments, embeds and components).
```

2022-08-06 14:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/intent/Intent.java
> +    GUILD_SCHEDULED_EVENTS(16, false);
Remove it. Should be added in the PR which adds support for guild scheduled events

2022-08-06 14:59 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +        }
Why is this change necessary?

2022-08-06 14:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/internal/InteractionMessageBuilderDelegate.java
> +    }
Same here

2022-08-06 14:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/internal/InteractionMessageBuilderDelegate.java
> +
What is this for? It is not usable from anywhere except in the delegate

2022-08-06 15:03 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +        }
<img width="1408" alt="Screenshot 2022-08-06 at 16 03 12" src="https://user-images.githubusercontent.com/67903886/183254660-d52a6b6c-0d4e-4546-8b1b-2f2566708627.png">
no longer need to add deleteMessageDays unless it is above 0

2022-08-06 15:06 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/message/internal/InteractionMessageBuilderDelegate.java
> +
This is used to update the message. were the list attachmentsToKeep is used to set the attachments you want to keep and addNewAttachments is used to add new attachments.

If both are null, the message will stay the same and have the same attachments

2022-08-06 15:13 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/internal/InteractionMessageBuilderDelegate.java
> +
You don't understand me. Why are there 3 methods in the delegate if only 1 is used at all in the InteractionMessageUpdater or what it was called where the delegate is used?

2022-08-06 16:32 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/message/internal/InteractionMessageBuilderDelegate.java
> +
ah i see

2022-08-06 18:40 UTC, RealYusufIsmail reviewed
Ignore these ico

2022-08-08 21:04 UTC, RealYusufIsmail commented
Blocked until #1095 is merged

2022-08-09 11:38 UTC, RealYusufIsmail commented
https://user-images.githubusercontent.com/67903886/183638127-762186a0-9d75-4d11-8ef9-f04d3297933e.mov


https://user-images.githubusercontent.com/67903886/183638145-60eb4fbb-131f-4505-bfac-d8f685c3c5c0.mov

2022-08-09 12:39 UTC, RealYusufIsmail commented
almost done

2022-08-09 17:44 UTC, RealYusufIsmail commented
<img width="1597" alt="Screenshot 2022-08-09 at 18 43 58" src="https://user-images.githubusercontent.com/67903886/183723261-234ef9bc-927c-4af8-9fef-9574d3daceae.png">
first do not keep attachments
seconds keep attachments

work

2022-08-10 14:28 UTC, KILLEliteMaste requested changes

2022-08-10 14:28 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +
I would not add these methods, because then you would have to add it for every other too which clutters the interface a lot. I think it's okay to redirect users to use the MessageUpdater if they want to perform more complex updates. Instead you should add methods for only changing the attachments.

2022-08-10 14:28 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
> +
This seems extremely inflexible as you can not change the attachments without changing or setting the content again. Why didn't you add new methods like `keepAllAttachments` and `keepAttachments(Attachment...)` / `keepAttachments(Collection<Attachment>`?

2022-08-10 14:28 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/internal/MessageBuilderBaseDelegate.java
> +     * Removes all the attachments from the message.
```suggestion
     * Removes all attachments from the message.
```

2022-08-10 14:28 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    }
With this approach you are reuploading all files instead of keeping them I think. As the docs state, you need to set the attachments you want to keep in the `attachments` array. For that you will most likely need a new variable `List<Attachments>` and then add the attachments you want to keep to it and then finally in the JSON body when sending the request
https://discord.com/developers/docs/resources/channel#edit-message-jsonform-params

2022-08-10 17:19 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    }
Thats not true. I tested it and it keep the file that i stated to keep and remove the others

2022-08-10 17:19 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    }
The part of setting that attachments you want to keep is done by the programmer

2022-08-10 17:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    }
You may re-read what I wrote... But to be more exact:
You are **re-uploading** the files instead of keeping them. This is a significant difference.
You can easily check this by opening the image in the browser so you get the CDN link. After editing the message, the link is not the same

2022-08-11 19:25 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    }
https://user-images.githubusercontent.com/67903886/184222722-cf4f2c31-5b98-45ee-83e3-098f4f753b01.mov

2022-08-11 20:41 UTC, KILLEliteMaste requested changes

2022-08-11 20:41 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    protected final List<Attachment> attachments = new ArrayList<>();
This is not needed, because you get the message as an argument in the update function. This should most likely be a boolean for keeping all attachments / remove all attachments. 
By default it's `true`. If `false`, remove all and if it's `true` and `attachmentsToKeep` contains something, just keep the attachments in the list

2022-08-11 20:41 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    }
Move the logic to the updater instead so no implementation is necessary

2022-08-11 20:41 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    public void keepAttachments(Collection<Attachment> keepAttachments) {
The methods should probably be renamed to `addKeepAttachments`. It is not really clear what this methods does with the current implementation(you are clearing the list) and then you could also add `setKeepAttachments` so someone can overwrite the list

2022-08-11 20:41 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    }
You can not check if the name is the same because you can set description for new files as the docs state
https://discord.com/developers/docs/resources/webhook#edit-webhook-message-jsonform-params
You will also not be able to do this once you remove the attachments variable because you get the attachments already via the message in the edit method.

2022-08-12 10:43 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    public void keepAttachments(Collection<Attachment> keepAttachments) {
i changed a bit so no need for this

2022-08-12 16:23 UTC, Mysterypotatoguy commented
Just my two cents, I'm not sure if I missed a conversation somewhere, but having to always specify keeping attachments seems like an odd design. I would expect by default a message edit keeps all previous attachments.
My suggestion is just to have `addAttachment`/`removeAttachment`/`removeAllAttachments` and a `getAttachments` to be able to access attachments to remove.

2022-08-12 16:27 UTC, RealYusufIsmail commented
> Just my two cents, I'm not sure if I missed a conversation somewhere, but having to always specify keeping attachments seems like an odd design. I would expect by default a message edit keeps all previous attachments. My suggestion is just to have `addAttachment`/`removeAttachment`/`removeAllAttachments` and a `getAttachments` to be able to access attachments to remove.

By deafult attachments are kept

2022-08-12 16:29 UTC, RealYusufIsmail commented
<img width="515" alt="Screenshot 2022-08-12 at 17 28 05" src="https://user-images.githubusercontent.com/67903886/184402317-5a605693-3427-4155-b09f-f96c4ff7b855.png">
The add part is done through message builder and KILLEliteMaste said no to this. To keep specific attachments I added a method for that @Mysterypotatoguy

2022-08-12 16:30 UTC, KILLEliteMaste requested changes
Please do not ignore requested changes and mark them as resolved if you did no apply them. You did multiple times and now again with the methods in the `MessageBuilderBase`. 
Reviews are a really time consuming task and it is quiet exhausting if I have to mark the same issues over and over

2022-08-12 16:30 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
> +
These methods are still here... And they are also usable for i.e. the `InteractionImmediateResponseBuilder` where they are useless

2022-08-12 16:30 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +        keepAttachments = true;
Not needed

2022-08-12 16:30 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
> +    public T setAttachmentsToKeep(Collection<Attachment> attachments) {
In the implementation you do not set the attachments, you are just adding them to the list. 
Should be renamed to `add*`

2022-08-12 16:30 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +        }
What happens if you do not set the attachments array empty? I always read the documentation that the attachments will still be removed

2022-08-12 16:30 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +        }
Did you test your new changes? This should not work as you check if the list of attachments contains the id of the attachment in the first if statement.

Anyway, the logic seem wrong to me. 
1. The method gets executed when we want to keep the attachments. 
2. `if(!attachmentToKepp.isEmpty())` then add only the attachments from the collection
3. Or else the list is empty, then add all attachments from the message

2022-08-12 16:49 UTC, Mysterypotatoguy commented
Okay, I've re-read and I think I understand better now. In this case I think `setAttachmentsToKeep` is a misleading name and implies you need to always call it when editing. What about `removeAttachmentsExcept`? 
Or better yet if we can somehow get access to the message object (might involve splitting edit logic out) then there can just be a single internal list of attachments that can be edited instead of `newAttachments` and `attachmentsToKeep`, then what I said before is possible

2022-08-12 16:54 UTC, RealYusufIsmail commented
> Please do not ignore requested changes and mark them as resolved if you did no apply them. You did multiple times and now again with the methods in the `MessageBuilderBase`. Reviews are a really time consuming task and it is quiet exhausting if I have to mark the same issues over and over

I apologise and will not do this next time

2022-08-13 14:41 UTC, KILLEliteMaste commented
> Okay, I've re-read and I think I understand better now. In this case I think `setAttachmentsToKeep` is a misleading name and implies you need to always call it when editing. What about `removeAttachmentsExcept`? Or better yet if we can somehow get access to the message object (might involve splitting edit logic out) then there can just be a single internal list of attachments that can be edited instead of `newAttachments` and `attachmentsToKeep`, then what I said before is possible

Currently the message is always passed into the MessageUpdater so we get the attachments from there. 

I think it would be nice to have both methods. But we need to clear method names to not confuse them with `addAttachment` which adds a new attachment to the message. Maybe we should also rename the method `addAttachmentToKepp` to just `retainAttachment(s)` and it's quiet shorter. 
So maybe we have:
- `retainAttachment(s)`
- `retainAllAttachments`
- `removeAttachmentsExcept`
- `removeAllAttachments`

>  then there can just be a single internal list of attachments

I don't think this will work out as new files need to be handled [differently ](https://discord.com/developers/docs/resources/channel#edit-message) than just being added to the `attachments` array to keep files

2022-08-16 11:59 UTC, Mysterypotatoguy commented
`retainAttachments` sounds fine, `retainAllAttachments` is confusing again. To someone just reading the name does it need to be called every edit to retain existing attachments?
I'm also not sure what `removeRetainingAttachment` and `removeAllRetainingAttachments` should do, remove the *existing* attachments?

2022-08-16 12:08 UTC, KILLEliteMaste commented
> I'm also not sure what removeRetainingAttachment and removeAllRetainingAttachments should do, remove the existing attachments?

Basically just the opposite of the other method. 
`retainAttachments` = only keep the provided attachments
`removeRetainingAttachments` = remove the provided attachments, instead of only keeping them

> retainAttachments sounds fine, retainAllAttachments is confusing again

Maybe a bit, yes. But should there be no way to revert the retaining attachments? So then you are screwed once you use any retainAttachment method. We can still mention in the Javadocs that this is the default behavior.

2022-08-17 07:58 UTC, Mysterypotatoguy commented
If you do make a mistake like that, you can just throw away the edit without executing it. I don't see why in static code you would need to be able to revert something like that, unless I am misunderstanding what you are saying.
For example in MessageBuilder there is no option to remove content once it has been added because it makes no sense, you can just throw away the MessageBuilder (or correct the code)

IMO the API should be
`addAttachment`
`addAttachments`
`removeExistingAttachment`
`removeExistingAttachments`
`removeExistingAttachmentsExcept`

2022-08-17 08:29 UTC, KILLEliteMaste commented
> If you do make a mistake like that, you can just throw away the edit without executing it. I don't see why in static code you would need to be able to revert something like that, unless I am misunderstanding what you are saying. For example in MessageBuilder there is no option to remove content once it has been added because it makes no sense, you can just throw away the MessageBuilder (or correct the code)
> 
> IMO the API should be `addAttachment` `addAttachments` `removeExistingAttachment` `removeExistingAttachments` `removeExistingAttachmentsExcept`

The names don't go well with adding attachment descriptions for new files 
![image](https://user-images.githubusercontent.com/31566807/185071671-0296a08b-6556-42ff-b96d-cd4bef71d4c6.png)

Then we are basically stuck with only being able to remove attachments but not adding them to this array. Or should there be another method for adding these description? Then I think we need another variable to store specifically the attachments that should be newly added and that's also not that nice

2022-08-17 08:30 UTC, Mysterypotatoguy commented
Probably an object in itself, `AttachmentBuilder`?

2022-08-17 11:07 UTC, KILLEliteMaste requested changes
We have a few more needed changes for the API
The methods should be renamed and added as follows:
`removeExistingAttachment(Attachment)`
`removeExistingAttachments()` (remove all attachments)
`removeExistingAttachments(Attachment...)`
`removeExistingAttachments(Collection<Attachment>)`

Overload the `addAttachment` methods with a `String` description parameter i.e. `addAttachment(File file)` will be overlaoded with`addAttachment(File file, String description)`. In the implementation we can only have the implementation with the description and the currently existing methods will call these methods with a `null` descrption. You most likely have to adjust the `Filecontainer` to also include an optional description. Then when also a description is set you have to add them to the `attachment` JSON where you specify the attachments that should be kept. To include new files with a description as previously mentioned the format has to look like 
```json
"id": n,
"description": "desription"
```
where n = the index number when adding a file in the `addMultipartBodyToRequest` method

The priority of this PR is getting higher due to the message content intent that will be enforced very soon. Do you have an estimate when you can finish this PR with the current new and older requested changes?

2022-08-17 11:50 UTC, RealYusufIsmail commented
> We have a few more needed changes for the API The methods should be renamed and added as follows: `removeExistingAttachment(Attachment)` `removeExistingAttachments()` (remove all attachments) `removeExistingAttachments(Attachment...)` `removeExistingAttachments(Collection<Attachment>)`
> 
> Overload the `addAttachment` methods with a `String` description parameter i.e. `addAttachment(File file)` will be overlaoded with`addAttachment(File file, String description)`. In the implementation we can only have the implementation with the description and the currently existing methods will call these methods with a `null` descrption. You most likely have to adjust the `Filecontainer` to also include an optional description. Then when also a description is set you have to add them to the `attachment` JSON where you specify the attachments that should be kept. To include new files with a description as previously mentioned the format has to look like
> 
> ```json
> "id": n,
> "description": "desription"
> ```
> 
> where n = the index number when adding a file in the `addMultipartBodyToRequest` method
> 
> The priority of this PR is getting higher due to the message content intent that will be enforced very soon. Do you have an estimate when you can finish this PR with the current new and older requested changes?

I can try to get this pr done in 2 days, but might take longer if something comes up. I will make it my main focus

2022-08-18 18:23 UTC, KILLEliteMaste requested changes

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
> +
I think this is now the 3rd time I am telling you that these methods can not be in this class because they are available in i.e. The MessageBuilder where they are useless. So they should only be available when **updating** a message
Just for example the following code does not have these methods but currently do. 
```java
new InteractionImmediateResponseBuilderImpl(null).removeExistingAttachments(Arrays.asList());
new MessageBuilder().removeExistingAttachments(Arrays.asList());
```

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/internal/MessageBuilderBaseDelegate.java
> +
Remove line

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/internal/MessageBuilderBaseDelegate.java
> +
Remove line

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
> +
Remove line

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
> +
Remove line

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
> +
Remove line

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
> +
Remove lines

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilderBase.java
> +    T removeExistingAttachments(Collection<Attachment> attachments);
Should be the same as mentioned in the MessageBuilderBase

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    }
We do not have this method anymore as this clashes with `attachmentsToRemove`. So we specify only the attachments we want to remove. So then you can remove the `attachmentsToKeep` variable as it is no longer needed

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +        newAttachments.add(new FileContainer(url, true, description));
I explicitly told you that the methods **without the description parameter** in the implementation are no longer needed. When using `addAttachmentAsSpoiler(URL)` in a MessageBuilder you can already set `null` to the description there. The same is for the other addAttachment methods above

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    }
Method not needed. You can move the logic to the updater classes so we have a method less in the implementation

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +            }
```suggestion
           this.addAttachment(attachment.getUrl(), attachment.getDescription().orElse(null));
```

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/ComponentInteractionOriginalMessageUpdaterImpl.java
> +public  class ComponentInteractionOriginalMessageUpdaterImpl
Remove space

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/FileContainer.java
> +
Remove line

2022-08-18 18:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/FileContainer.java
> +
Remove line

2022-08-18 18:51 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +        newAttachments.add(new FileContainer(url, true, description));
sorry i think i mis read what you said

2022-08-19 15:12 UTC, KILLEliteMaste requested changes

2022-08-19 15:12 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +        }
If there are not attachments to remove, it means all attachments should be kept. You are missing the else case where all attachments are added that are kept.

2022-08-19 15:12 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/ExtendedInteractionMessageBuilderBaseImpl.java
> +        addAttachment(bytes, "SPOILER_" + fileName);
```suggestion
        addAttachment(bytes, "SPOILER_" + fileName, null);
```

2022-08-19 15:12 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/ExtendedInteractionMessageBuilderBaseImpl.java
> +        addAttachment(stream, "SPOILER_" + fileName);
```suggestion
        addAttachment(stream, "SPOILER_" + fileName, null);
```

2022-08-19 15:12 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/InteractionOriginalResponseUpdaterImpl.java
> +        addAttachment(image, "SPOILER_" + fileName);
```suggestion
        addAttachment(image, "SPOILER_" + fileName, null);
```

2022-08-19 15:12 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/InteractionOriginalResponseUpdaterImpl.java
> +        addAttachment(bytes, "SPOILER_" + fileName);
```suggestion
        addAttachment(bytes, "SPOILER_" + fileName, null);
```

2022-08-19 15:12 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/InteractionOriginalResponseUpdaterImpl.java
> +        addAttachment(stream, "SPOILER_" + fileName);
```suggestion
        addAttachment(stream, "SPOILER_" + fileName, null);
```

2022-08-19 17:55 UTC, KILLEliteMaste requested changes

2022-08-19 17:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +
```suggestion
```

2022-08-19 17:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +    }
The same for the methods below
```suggestion
    public MessageUpdater removeExistingAttachment(Attachment attachment) {
        delegate.removeExistingAttachment(attachment);
        return this;
    }
```

2022-08-19 17:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/WebhookMessageBuilder.java
> +            builder.addAttachment(attachment.getUrl(), attachment.getDescription().get());
```suggestion
            builder.addAttachment(attachment.getUrl(), attachment.getDescription().orElse(null));
```

2022-08-19 17:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/WebhookMessageBuilder.java
> +
You marked this as resolved again without removing the line

2022-08-19 17:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +            if (attachmentsToRemove.isEmpty() && clearAttachmentsIfAppropriate) {
Correct me if I am wrong, but shouldn't this check removed? It can only be true if the message is being edited. And if  `attachmentsToRemove` is empty we add all attachments to the array previously to keep them. With this method we would override the array and remove all attachments? I think this should be removed

2022-08-20 21:10 UTC, Mysterypotatoguy requested changes

2022-08-20 21:15 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
> +     * Adds the json data to the given object node.
The return text also needs to be changed. Seems to be copied from the `EmbedBuilderDelegateImpl`

2022-08-20 21:18 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +                    RequestBody.create(bytes, MediaType.parse(mediaType)));
> According to the [docs](https://discord.com/developers/docs/reference#editing-message-attachments-example-request-bodies-multipartformdata) this needs to be in the format file[n]

It actually has to be `files[n]` (missing `s` in your new example)

```
--boundary
Content-Disposition: form-data; name="files[0]"; filename="myfilename.png"
Content-Type: image/png

[image bytes]
--boundary
Content-Disposition: form-data; name="files[1]"; filename="mygif.gif"
Content-Type: image/gif

[image bytes]
--boundary--
```

2022-08-21 16:18 UTC, Mysterypotatoguy requested changes

2022-08-21 16:18 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +     * @return The updated message.
```suggestion
     * @return The current instance in order to chain call methods.
```

2022-08-21 16:18 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +     * @return The updated message.
```suggestion
     * @return The current instance in order to chain call methods.
```

2022-08-21 16:18 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +     * @return The updated message.
```suggestion
     * @return The current instance in order to chain call methods.
```

2022-08-21 16:18 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +     * @return The updated message.
```suggestion
     * @return The current instance in order to chain call methods.
```

2022-08-22 13:32 UTC, KILLEliteMaste approved these changes
LGTM!

2022-08-22 13:38 UTC, Mysterypotatoguy approved these changes
LGTM if everything has been tested

2022-08-22 14:05 UTC, merged

2022-08-24 07:19 UTC, KILLEliteMaste commented
@all-contributors please add @RealYusufIsmail for code