Add support for Message Interactions Object
Javacord/Javacord pull request #1078
Opened 2022-08-06 21:49 UTC by AhmedA1559

2022-08-07 10:14 UTC, KILLEliteMaste requested changes

2022-08-07 10:14 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/MessageInteractionImpl.java
> +        type = InteractionType.fromValue(typeId);
Please remove the `typeId` variable and inline the statement

2022-08-07 10:14 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/MessageInteractionImpl.java
> +                    null
Does the member packet include the user? I wouldn't say so because it is already present in a separate field `user`. Then you would need to create a user object instead of passing null

2022-08-07 10:14 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/MessageInteractionImpl.java
> +    }
You can override the method in the interface and use a default implementation
```java
@Override
default DiscordApi getApi() {
    return getMessage().getApi();
}
```

2022-08-07 10:35 UTC, AhmedA1559 commented on javacord-core/src/main/java/org/javacord/core/interaction/MessageInteractionImpl.java
> +                    null
> Does the member packet include the user? I wouldn't say so because it is already present in a separate field `user`. Then you would need to create a user object instead of passing null

The documentation lists the type of the member field as a "partial member object" so I think it does not then.

2022-08-07 12:34 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/MessageInteractionImpl.java
> +                    null
Don't you have the JSON packet from your testing so you could confirm if this is really the case? :)

2022-08-07 18:19 UTC, AhmedA1559 commented
Weirdly enough, I can't seem to get Discord to return a member field in the json. I looked around and it also seems that [Discord.js](https://cs.github.com/discordjs/discord.js/blob/a7deb8f89830ead6185c5fb46a49688b6d209ed1/packages/discord.js/src/structures/Message.js#L343) omits the member object, opting only to include the user field only.

2022-08-07 18:21 UTC, KILLEliteMaste commented
> Weirdly enough, I can't seem to get Discord to return a member field in the json. I looked around and it also seems that [Discord.js](https://cs.github.com/discordjs/discord.js/blob/a7deb8f89830ead6185c5fb46a49688b6d209ed1/packages/discord.js/src/structures/Message.js#L343) omits the member object, opting only to include the user field only.

Have you tried enabling the `GUILD_MEMBERS` intent?

2022-08-07 18:29 UTC, AhmedA1559 commented
> > Weirdly enough, I can't seem to get Discord to return a member field in the json. I looked around and it also seems that [Discord.js](https://cs.github.com/discordjs/discord.js/blob/a7deb8f89830ead6185c5fb46a49688b6d209ed1/packages/discord.js/src/structures/Message.js#L343) omits the member object, opting only to include the user field only.
> 
> Have you tried enabling the `GUILD_MEMBERS` intent?

Yeah: `DiscordApi api = new DiscordApiBuilder().setToken(token).setAllIntents().login().join();`

2022-08-08 16:22 UTC, KILLEliteMaste requested changes

2022-08-08 16:22 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +     * Gets the Message Interaction Object if the message responds to an interaction.
```suggestion
     * Gets the Message Interaction Object if the message is a response to an Interaction without an existing message.
```

2022-08-08 16:24 UTC, KILLEliteMaste commented
Not sure what you did, but in my setup with also having the guild members intent enabled I get a member in the message interaction when invoking a UserContextInteraction. But the logic looks right to me for handling the member JSON

2022-08-10 19:03 UTC, KILLEliteMaste approved these changes
LGTM!
Can you please rebase to the latest version, resolve the merge conflicts and squash the PR into a single commit?

2022-08-11 12:21 UTC, KILLEliteMaste requested changes

2022-08-11 12:21 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
> +        }
Move to the the constructor as I don't think this will ever change

2022-08-11 19:07 UTC, KILLEliteMaste approved these changes

2022-08-11 19:20 UTC, merged