Add missing field position to the message object
Javacord/Javacord pull request #1088
Opened 2022-08-07 10:57 UTC by shubhwip

Issue Link : https://github.com/Javacord/Javacord/issues/1084
Issue Description : https://discord.com/developers/docs/resources/channel#message-object

2022-08-07 11:10 UTC, RealYusufIsmail requested changes

2022-08-07 11:10 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +     * Gets the approximate position of the message in a thread
```suggestion
     * Gets the approximate position of the message in a thread.
```

2022-08-07 11:10 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
> +     * in company with total_message_sent on parent thread
No need to get into this much detail in an impl.

Just says the approximate position of the message in a thread

2022-08-07 11:10 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
> +     */
```suggestion
    /**
     * The position of the message in a channel.
     */
```

2022-08-07 11:15 UTC, RealYusufIsmail approved these changes

2022-08-07 12:38 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +     * Gets the approximate position of the message in a thread
I would say you should include the Javadoc you had in the implementation as this is not very informative. Someone might think why is it approximate or in general what you would do with this (its used in companion with total_message_sent). Including the Javadoc should clear it up a bit

2022-08-07 14:27 UTC, KILLEliteMaste requested changes

2022-08-07 14:27 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +     * in a thread in company with total_message_sent on parent thread.
Even when placing dots after the sentences it reads very choppy so lets just change it to what's written in the docs
```suggestion
     * A generally increasing integer (there may be gaps or duplicates)
     * that represents the approximate position of the message in a thread,
     * it can be used to estimate the relative position of the message in a thread
     * in company with {@link ServerThreadChannel#getTotalNumberOfMessagesSent()} on parent thread.
```
This will probably not work right away because the mentioned method in the Javadoc does no yet exists. So we have to wait for #1089 to be merged first.

2022-08-07 15:05 UTC, shubhwip commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +     * in a thread in company with total_message_sent on parent thread.
Thanks for the putting suggested change :) !! Added the change but for now build will fail until #1089 is merged.

2022-08-07 15:19 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +     * in a thread in company with total_message_sent on parent thread.
will try to get as fast as possible

2022-09-10 14:26 UTC, KILLEliteMaste commented
@shubhwip the PR has been merged. Can you please rebase the branch with the latest version?

2022-09-11 12:27 UTC, RealYusufIsmail approved these changes

2022-09-11 12:27 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
> +            : null;
```suggestion
        
        position = data.hasNonNull("position") ? data.get("position").asInt() 
            : null;
```

2022-09-11 12:27 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
> +            : null;
Unsure if this will cause the build to fail

2022-09-11 14:28 UTC, shubhwip commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
> +            : null;
no it was due to missing constructor param.

2022-09-12 08:22 UTC, KILLEliteMaste requested changes

2022-09-12 08:22 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
> +    private final int position;
Assigning `null` to this will not work. Change it to `Integer`

2022-09-15 06:45 UTC, KILLEliteMaste approved these changes
Thank you, LGTM!

2022-09-15 06:45 UTC, merged