added total number of messages sent
Javacord/Javacord pull request #1089
Opened 2022-08-07 10:58 UTC by RealYusufIsmail

closes #1086

2022-08-07 13:05 UTC, KILLEliteMaste requested changes
Currently thread channels are not updated completely. Do you mind also adjusting the `ThreadUpdateHandler` and add the missing events for the updatable fields? You would also have to adjust the message create listener to check if the message is in a thread channel to check if the `total_message_count` has to be increased. If not let me know and I will create a separate issue.

2022-08-07 13:17 UTC, RealYusufIsmail commented
> Currently thread channels are not updated completely. Do you mind also adjusting the `ThreadUpdateHandler` and add the missing events for the updatable fields? You would also have to adjust the message create listener to check if the message is in a thread channel to check if the `total_message_count` has to be increased. If not let me know and I will create a separate issue.

will do

2022-08-08 16:55 UTC, KILLEliteMaste requested changes

2022-08-08 16:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/event/channel/server/thread/ServerThreadChannelArchiveTimestampChangeEvent.java
> +public interface ServerThreadChannelArchiveTimestampChangeEvent extends ServerThreadChannelEvent {
Here and for all other events+listeners please switch the order of `Change` and the keyword(s) before so it becomes `ServerThreadChannelChangeArchiveTimestampEvent `

2022-08-08 16:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/event/channel/server/thread/ServerThreadParentIdChangeEvent.java
> +public interface ServerThreadParentIdChangeEvent extends ServerThreadChannelEvent {
Can you move threads to another channel?

2022-08-08 16:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/listener/server/thread/ServerThreadChannelArchiveTimestampChangeListener.java
> +        ServerChannelAttachableListener, GloballyAttachableListener, ObjectAttachableListener {
Please change this in every listener interface. ChannelCategories and ServerVoiceChannel can not have threads so this listener shouldn't be attachable to them.
```suggestion
        ServerTextChannelAttachableListener, GloballyAttachableListener, ObjectAttachableListener {
```

2022-08-08 16:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/channel/ServerThreadChannelImpl.java
> +    private Set<ThreadMember> members;
No need to remove the `final` modifier. The collection is not immutable

2022-08-08 16:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        if (!Objects.deepEquals(oldMessageCount, newMessageCount)) {
Why so complicated? A simple `!=` is sufficient
(Also applies for the other fields below)

2022-08-08 16:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +            if (server.isReady()) {
Shouldn't be necessary so please remove it

2022-08-08 16:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        final Set<ThreadMember> oldMembers = thread.getMembers();
In `ServerThreadChannelImpl `please adjust `getMembers` to return a copy of the collection instead of exposing the one in the implementation

2022-08-08 21:09 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/event/channel/server/thread/ServerThreadParentIdChangeEvent.java
> +public interface ServerThreadParentIdChangeEvent extends ServerThreadChannelEvent {
will need to check.

2022-08-08 21:10 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/event/channel/server/thread/ServerThreadParentIdChangeEvent.java
> +public interface ServerThreadParentIdChangeEvent extends ServerThreadChannelEvent {
no you cant, will remove this.

2022-08-09 07:23 UTC, KILLEliteMaste requested changes

2022-08-09 07:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/event/channel/server/thread/ServerThreadChannelMessageCountChangeEvent.java
> -public interface ServerThreadChannelMessageCountChangeEvent extends ServerThreadChannelEvent {
Why did you remove this event?

2022-08-09 07:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/listener/server/thread/ServerThreadChannelChangeArchiveTimestampListener.java
> +        GloballyAttachableListener, ObjectAttachableListener {
Here and in the other files please move them to the previous line

2022-08-09 07:23 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/event/channel/server/thread/ServerThreadChannelEvent.java
> +public interface ServerThreadChannelEvent extends ServerChannelEvent, TextChannelEvent {
Does it make sense that it extends `TextChannelEvent`? I don't think so as you will also get methods like `getPrivateChannel` and `getServerTextChannel` which should be useless for this event or not?

2022-08-09 07:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/channel/ServerThreadChannelImpl.java
> +        return new HashSet<>(members);
Sorry, didn't specify clear enough what I wanted
`return new Collections.unmodifiableSet(members);`

2022-08-09 07:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/event/channel/server/thread/ServerThreadChannelEventImpl.java
>          this.channel = channel;
You already have the channel in the ServerChannelEventImpl.
In the method below this should work: `super.getChannel().asServerThreadChannel().orElseThrow()`

2022-08-09 07:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        if (!Objects.deepEquals(oldMessageCount, newMessageCount)) {
You missed this

2022-08-09 07:23 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
>              if (server.isReady()) {
You have not removed this as I also mentioned in a comment

2022-08-09 08:09 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
>              if (server.isReady()) {
ah

2022-08-10 19:47 UTC, KILLEliteMaste requested changes
You have not edited the MessageCreateListener as I said [in this comment](https://github.com/Javacord/Javacord/pull/1089#pullrequestreview-1064418746)

2022-08-10 19:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/event/channel/server/thread/ServerThreadChannelChangeTotalMessagesEvent.java
> +public interface ServerThreadChannelChangeTotalMessagesEvent extends ServerThreadChannelEvent {
```suggestion
public interface ServerThreadChannelChangeTotalMessageSentEvent extends ServerThreadChannelEvent {
```

2022-08-10 19:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/listener/server/thread/ServerThreadChannelChangeMemberCountListener.java
> +        GloballyAttachableListener, ObjectAttachableListener {
Move to previous line

2022-08-10 19:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/listener/server/thread/ServerThreadChannelChangeTotalMessagesListener.java
> +public interface ServerThreadChannelChangeTotalMessagesListener extends ServerThreadChannelAttachableListener,
```suggestion
public interface ServerThreadChannelChangeTotalMessageSentListener extends ServerThreadChannelAttachableListener,
```

2022-08-10 19:47 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/channel/ServerThreadChannelImpl.java
> +     * The number of messages that are sent.
```suggestion
     * The total number of messages that are sent.
```

2022-08-10 19:47 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/event/channel/server/thread/ServerThreadChannelChangeTotalMessagesEventImpl.java
> +public class ServerThreadChannelChangeTotalMessagesEventImpl extends ServerThreadChannelEventImpl
```suggestion
public class ServerThreadChannelChangeTotalMessageSentEventImpl extends ServerThreadChannelEventImpl
```

2022-08-10 19:47 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +
Here and below you have many 2 empty lines. Reduce them to 1

2022-08-10 19:47 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
>              }
You copied this straight from the implementation without even reading the issue as it clearly says that this only happens in the `GUILD_CREATE` event or is this not the case and the documentation is wrong?

2022-08-10 19:47 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/event/channel/server/thread/ServerThreadChannelChangeTotalMessagesEventImpl.java
> +        return oldTotalMessageCount;
Rename to totalMessageSent. `total_message_count` was a typo by me

2022-08-10 19:47 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        }
`total_message_count` does not exist (change to `total_message_sent`) so this should throw an exception. Did you try to run this code? 
You also need to dispatch the listener here

2022-09-02 20:35 UTC, KILLEliteMaste requested changes

2022-09-02 20:35 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
> +        }
```suggestion
        message.getServerThreadChannel().ifPresent(stc-> {
            ((ServerThreadChannelImpl)stc).setTotalNumberOfMessagesSent(stc.getTotalNumberOfMessagesSent() + 1);
        });
```

2022-09-02 20:35 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +
You marked it as resolved again without applying the changes...

2022-09-02 20:35 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        //id and userid are only omitted on GUILD_CREATE event
Comment does not add any value to this. Remove it.

2022-09-02 20:35 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +                || getChannel().getType() == ChannelType.SERVER_PUBLIC_THREAD;
You are missing to check for `SERVER_NEWS_THREAD`

2022-09-02 20:35 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +     * or {@link ChannelType#SERVER_PUBLIC_THREAD public thread} channel.
```suggestion
     * Checks if the message was sent in a thread channel.
```

2022-09-02 20:35 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/channel/ServerThreadChannelImpl.java
> +            //id and userid are only omitted on GUILD_CREATE event
Why did you remove the comment?

2022-09-03 14:21 UTC, KILLEliteMaste requested changes

2022-09-03 14:21 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        final int newAutoArchiveDuration = jsonChannel.get("auto_archive_duration").asInt();
Please test your PR's at least in some basics ways... Then you would clearly see that a bunch of fields are not accessible that way
```json
{
  "type": 11,
  "total_message_sent": 1,
  "thread_metadata": {
    "locked": false,
    "create_timestamp": "TIME",
    "auto_archive_duration": 1440,
    "archived": false,
    "archive_timestamp": "TIME"
  },
  "rate_limit_per_user": 0,
  "parent_id": "ID1",
  "owner_id": "ID2",
  "name": "test thread",
  "message_count": 1,
  "member_count": 1,
  "last_message_id": "ID3",
  "id": "ID4",
  "guild_id": "ID5",
  "flags": 0
}
```

2022-09-03 14:21 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        }
![image](https://user-images.githubusercontent.com/31566807/188274479-acdc6e07-1e37-42b4-aacd-e398864fd954.png)
According to this your logic would be wrong. Instead if the packet contains a member object, add it to all current members in the thread and then dispatch the event without checking if they are equal.

2022-09-03 15:41 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        final int newAutoArchiveDuration = jsonChannel.get("auto_archive_duration").asInt();
thats why i think https://github.com/Javacord/Javacord/pull/1094 should be merged first

2022-09-03 18:09 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        final int newAutoArchiveDuration = jsonChannel.get("auto_archive_duration").asInt();
It doesn't matter if this PR gets merged first or not. You have requested a review and served not working code that could have been easily found if you executed that code once.
Anyway the PR has been merged so you can change it

2022-09-04 07:09 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        final int newAutoArchiveDuration = jsonChannel.get("auto_archive_duration").asInt();
done

2022-09-04 11:27 UTC, KILLEliteMaste requested changes

2022-09-04 11:27 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        }
`member` is not an array as I have shown you.
```suggestion
        if (jsonChannel.hasNonNull("member")) {
            final Set<ThreadMember> members = thread.getMembers();
            final ThreadMember member = new ThreadMemberImpl(api, server, jsonChannel.get("member"));
            members.add(member);
            thread.setMembers(newMembers);

            final ServerPrivateThreadJoinEvent event =
                    new ServerPrivateThreadJoinEventImpl(thread, newMembers,
                            oldMembers);

            api.getEventDispatcher().dispatchServerPrivateThreadJoinEvent(
                    (DispatchQueueSelector) thread.getServer(), thread.getServer(), thread, event);
        }
```
I don't have access to private threads to test it but this should work. The data to dispatch for this event should probably be just just the ServerThreadChannel. And then it's probably also the best to move this code to the very end so it gets executed last

2022-09-04 11:27 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/listener/server/thread/ServerPrivateThreadJoinListener.java
> +     * This method is called every time a user joins a server thread channel.
```suggestion
     * This method is called every time you (the bot) joins a server thread channel.
```

2022-09-04 11:27 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        final int newAutoArchiveDuration = jsonChannel.get("thread_metadata").get("auto_archive_duration")
Don't repeat yourself. Create a JsonNode for the `thread_metadata`. 

You are also missing to update the `invitable` field which can be absent in the json packet and is only sent for private threads
![image](https://user-images.githubusercontent.com/31566807/188310880-ece70fcd-6505-4c12-bdea-ba812e5ecbfb.png)

2022-09-04 17:46 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +        }
> The data to dispatch for this event should probably be just just the ServerThreadChannel

Any reason you have not applied this requested change and exchanged the old/new members with the ServerThreadChannel? I am not sure if you even have to do this. It may be possible that it's already possible to get the channel by default through this event because it's already extending something.

2022-09-09 17:38 UTC, RealYusufIsmail commented
@KILLEliteMaste any updates on this pr

2022-09-09 22:05 UTC, KILLEliteMaste requested changes

2022-09-09 22:05 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +            final Set<ThreadMember> members = thread.getMembers();
```suggestion
            final Set<ThreadMember> members = new HashSet<>(thread.getMembers());
```

2022-09-09 22:05 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +                            oldMembers);
```suggestion
                    new ServerPrivateThreadJoinEventImpl(thread, member);
```
You have still not removed the members from the event...
Instead just pass the new ThreadMember of the bot

2022-09-10 06:03 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +                            oldMembers);
will do so

2022-09-10 06:39 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadUpdateHandler.java
> +                            oldMembers);
will this work 
```java
  if (jsonChannel.hasNonNull("member")) {
            final Set<ThreadMember> members = new HashSet<>(thread.getMembers());
            final ThreadMember member = new ThreadMemberImpl(api, server, jsonChannel.get("member"));
            members.add(member);
            thread.setMembers(members);

            final ServerPrivateThreadJoinEvent event =
                    new ServerPrivateThreadJoinEventImpl(thread, member);

            api.getEventDispatcher().dispatchServerPrivateThreadJoinEvent(
                    (DispatchQueueSelector) thread.getServer(), thread.getServer(), thread, event);
        }
```

2022-09-10 10:54 UTC, KILLEliteMaste approved these changes
Thank you, LGTM!

2022-09-10 10:55 UTC, merged