Added  missing field fail_if_not_exists to the Message Reference Object
Javacord/Javacord pull request #1090
Opened 2022-08-07 11:06 UTC by RealYusufIsmail

2022-08-07 11:18 UTC, shubhwip commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageReferenceImpl.java
> +        this.failIfNotExists = data.get("fail_if_not_exists").asBoolean();
Can we specify here default value as `true` as mentioned in the docs ?

2022-08-07 11:19 UTC, shubhwip commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageReferenceImpl.java
>          return Optional.ofNullable(message);
Would there be a need of `Optional` if we have default value as `true` always :) ?

2022-08-07 11:31 UTC, wasdennnoch commented
`fail_if_not_exists` is used when _sending_ messages, not when receiving them, so it has to be added to the corresponding message builders etc. It determines if, when sending a reply, discord should return you an error when you're replying to an unknown message, or if Discord should ignore the message reference in that case and treat it as a normal message send without a reply.

2022-08-07 11:34 UTC, RealYusufIsmail commented
> `fail_if_not_exists` is used when _sending_ messages, not when receiving them, so it has to be added to the corresponding message builders etc. It determines if, when sending a reply, discord should return you an error when you're replying to an unknown message, or if Discord should ignore the message reference in that case and treat it as a normal message send without a reply.

will do so

2022-08-07 11:58 UTC, RealYusufIsmail commented
> #1085

When replying is there a way to check if the message id is null like here,

```java
 if (replyingTo != null) {
            body.putObject("message_reference").put("message_id", replyingTo);
        }
```

2022-08-07 11:59 UTC, RealYusufIsmail commented
or would i check here for example ```java
private CompletableFuture<Message> executeRequestWithoutAttachments(TextChannel channel,
                                                                        ObjectNode body,
                                                                        RestRequest<Message> request) {
        request.setBody(body);
        //check if fail_if_not_exists is false and message doesn't exist, trough exception
        return request.execute(result -> ((DiscordApiImpl) channel.getApi())
                .getOrCreateMessage(channel, result.getJsonBody()))
                .whenComplete((newMessage, throwable) -> {
                    if (throwable != null) {
                        throwable.printStackTrace();
                    }
                });
    }

```

2022-08-07 12:06 UTC, wasdennnoch commented
> When replying is there a way to check if the message id is null like here,

Not sure where/why you're trying to check that. The code you posted already checks if the message should be a reply, and populates allowed_mentions. Now you just have to add a variable in the replied_mentions payload that tells _discord_ if it should check if the message exists or not. So something like

```java
if (replyingTo != null) {
    body.putObject("message_reference")
        .put("message_id", replyingTo)
        .put("fail_if_not_exists", failIfNotExists);
}
```

where the boolean `failIfNotExists` (or whatever you'll call the variable) will be configurable by the user somehow.

2022-08-07 12:06 UTC, RealYusufIsmail commented
ok

2022-08-07 12:28 UTC, RealYusufIsmail commented
> > When replying is there a way to check if the message id is null like here,
> 
> Not sure where/why you're trying to check that. The code you posted already checks if the message should be a reply, and populates allowed_mentions. Now you just have to add a variable in the replied_mentions payload that tells _discord_ if it should check if the message exists or not. So something like
> 
> ```java
> if (replyingTo != null) {
>     body.putObject("message_reference")
>         .put("message_id", replyingTo)
>         .put("fail_if_not_exists", failIfNotExists);
> }
> ```
> 
> where the boolean `failIfNotExists` (or whatever you'll call the variable) will be configurable by the user somehow.

done

2022-08-07 12:35 UTC, shubhwip commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageReferenceImpl.java
> +        return Optional.ofNullable(failIfNotExists);
Do we need `Optional` here as value of `failIfNotExists ` will be true by default always.

2022-08-07 12:38 UTC, shubhwip commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageReferenceImpl.java
> +        this.failIfNotExists = data.hasNonNull("fail_if_not_exists") ? data.get("fail_if_not_exists").asBoolean() :
This could have been simplified with `this.failIfNotExists = data.get("fail_if_not_exists").asBoolean(true);`

2022-08-07 12:56 UTC, AhmedA1559 commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> reply(String messageContent, boolean checkIfMessageExists) {
Wouldn't this break pre-existing code? I think you should make a method with signature `CompletableFuture<Message> reply(String messageContent)` that calls this method with a default parameter for `checkIfMessageExists`.

2022-08-07 12:56 UTC, AhmedA1559 commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
> +    public MessageBuilder replyTo(Message message, boolean checkIfMessageExists) {
The same here.

2022-08-07 13:31 UTC, AhmedA1559 requested changes

2022-08-07 13:31 UTC, AhmedA1559 commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    private boolean checkIfMessageExists = false;
[The discord docs](https://discord.com/developers/docs/resources/channel#message-reference-object-message-reference-structure) report that this is, by default, true.

2022-08-07 13:31 UTC, AhmedA1559 commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageReference.java
> +     * Gets weather the message reference is valid.
```suggestion
     * Gets whether the message reference is valid.
```

2022-08-07 13:31 UTC, AhmedA1559 commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageReference.java
> +    //
```suggestion
```

2022-08-07 13:31 UTC, AhmedA1559 commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +     * @param checkIfMessageExists Used to tell discord if you want to check if the message exists.
```suggestion
     * @param checkIfMessageExists If true, tells discord to throw an error if the message reference does not exist, if false, then leaves out the message reference if it does not exist but still sends the message.
```

2022-08-07 13:31 UTC, AhmedA1559 commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +     * @param checkIfMessageExists Used to tell discord if you want to check if the message exists.
```suggestion
     * @param checkIfMessageExists If true, tells discord to throw an error if the message reference does not exist, if false, then leaves out the message reference if it does not exist but still sends the message.
```

2022-08-07 15:27 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageReferenceImpl.java
> +        return Optional.ofNullable(failIfNotExists);
yeah, will change that

2022-08-07 15:30 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    private boolean checkIfMessageExists = false;
Would just doing
` private boolean checkIfMessageExists;`
work better

2022-08-07 15:38 UTC, RealYusufIsmail commented
@AhmedA1559 @wasdennnoch can you do re review please

2022-08-07 16:34 UTC, AhmedA1559 requested changes

2022-08-07 16:34 UTC, AhmedA1559 commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
> +    public MessageBuilder replyTo(long messageId, boolean checkIfMessageExists) {
Needs to be fixed to include `MessageBuilder replyTo(long messageId)` and `MessageBuilder replyTo(Message message)` signatures.

2022-08-07 16:34 UTC, AhmedA1559 commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> reply(EmbedBuilder embed, boolean checkIfMessageExists) {
I think the name `checkIfMessageExists` is a misnomer: setting this to false still has the behavior of checking the message reference, but instead does not assert an error. It would probably be better to have a name like `assertReferenceExists` instead. This should be applied to the rest of the PR.

2022-08-07 16:40 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> reply(EmbedBuilder embed, boolean checkIfMessageExists) {
will do

2022-08-08 08:04 UTC, RealYusufIsmail commented
@AhmedA1559 re-review please

2022-08-08 09:24 UTC, AhmedA1559 approved these changes
Other than that, LGTM. Please make sure to test though to check behavior.

2022-08-08 09:24 UTC, AhmedA1559 commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
> +        replyTo(message, false);
The default value is supposed to be true.

2022-08-08 09:38 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
> +        replyTo(message, false);
ok

2022-08-08 20:54 UTC, RealYusufIsmail commented
done

2022-09-10 11:07 UTC, RealYusufIsmail commented
@KILLEliteMaste can you have a look at this pr please

2022-09-10 13:59 UTC, KILLEliteMaste requested changes

2022-09-10 13:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
>          return this;
```suggestion
        return replyTo(message, true);
```

2022-09-10 13:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
> +        return this;
```suggestion
        return replyTo(messageId, true);
```

2022-09-10 13:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
> +        return this;
```suggestion
        return replyTo(message.getId(), assertReferenceExists);
```

2022-09-10 13:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageReference.java
> +    boolean doesMessageReferenceExist();
As @wasdennnoch pointed out, this field is only used when sending the message.

2022-09-10 13:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +     *                             if it does not exist but still sends the message.
```suggestion
     * @param assertReferenceExists If true, throw an error if the message you are replying to does not exists otherwise, 
     *                                                   if false send the message regardless without a reference to a message.
```
The same for the other Javadoc

2022-09-12 08:17 UTC, KILLEliteMaste approved these changes
Thank you, LGTM!

2022-09-12 08:18 UTC, merged