Update ServerFeature ENUM Class
Javacord/Javacord pull request #1096
Opened 2022-08-09 06:25 UTC by shubhwip

Add WelcomeScreen and WelcomeScreenChannel
Add Missing fields in ServerImpl
Add Missing System Channel Flags

Issue Link : https://github.com/Javacord/Javacord/issues/1087
Issue Description :

> Missing fields:
> 
> premium_progress_bar_enabled
> welcome_screen
> max_video_channel_users
> max_members
> max_presences
> widget_channel_id
> widget_enabled
>
> ServerFeatures enum is outdated:
> https://discord.com/developers/docs/resources/guild#guild-object-guild-features
> 
> Add missing System Channel Flags
> https://discord.com/developers/docs/resources/guild#guild-object-system-channel-flags
> 
>

2022-08-09 06:26 UTC, shubhwip commented
Some Queries :
1. Does `WelcomeScreenImpl` need to extend `DiscordEntity` ?
2. Should I include welcome screen in `InviteImpl` as well ?
https://discord.com/developers/docs/resources/invite#invite-object

2022-08-09 07:28 UTC, KILLEliteMaste commented
> 1. Does `WelcomeScreenImpl` need to extend `DiscordEntity` ?

No, this object does not have an ID

> 2. Should I include welcome screen in `InviteImpl` as well ?

Why do you think so? Can't find anything related to the welcome screen in the mentioned docs.

2022-08-09 07:41 UTC, shubhwip commented
> A small note: Next time please use one of these [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to mention the issue so the issue gets linked properly and auto closed. Examples can also be found when you follow the link how it should look like.
> 

Sure will do.

> > 1. Does `WelcomeScreenImpl` need to extend `DiscordEntity` ?
> 
> No, this object does not have an ID
> 
> > 2. Should I include welcome screen in `InviteImpl` as well ?
> 
> Why do you think so? Can't find anything related to the welcome screen in the mentioned docs.

If you look at the docs of guild structure
https://discord.com/developers/docs/resources/guild#guild-object-guild-structure
In `welcome_screen?` field it is mentioned that

> the welcome screen of a Community guild, shown to new members, returned in an [Invite](https://discord.com/developers/docs/resources/invite#invite-object)'s guild object

2022-08-09 07:52 UTC, KILLEliteMaste commented
> If you look at the docs of guild structure
https://discord.com/developers/docs/resources/guild#guild-object-guild-structure
In welcome_screen? field it is mentioned that

Ah yes, this means that the welcome screen is inside the `guild` key in the JSON packet. I don't think we should care about this in the `InviteImpl`, as Javacord requires servers to be at any time cached, and the `GUILD_CREATE` packet already contains the welcome screen

2022-08-09 08:46 UTC, shubhwip commented
@KILLEliteMaste Also can you please give some review feedback on this PR ?

2022-08-09 09:22 UTC, KILLEliteMaste requested changes

2022-08-09 09:22 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * @return Checks if the server has join messages reply buttons enabled.
You copy pasted this. Please rephrase it like you have it for `hasServerReminderNotificationsEnabled`.
The same for the other Javadoc(also the other classes you edited / added) for the fields you added and the Javadoc starts with uppercase(fields below)

2022-08-09 09:22 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    Optional<Long> getWidgetChannelId();
Please add this method
```java
default Optional<RegularServerChannel> getWidgetChannel(){
    return getWidgetChannelId.map(this::getRegularServerChannel)
}
```

2022-08-09 09:22 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * returned in an Invite's guild object.
```suggestion
```

2022-08-09 09:22 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/ServerFeature.java
> +     * server has set up auto moderation rules.
```suggestion
     * Server has set up auto moderation rules.
```

2022-08-09 09:22 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/invite/WelcomeScreen.java
> +
```suggestion
```

2022-08-09 09:22 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +        this.widgetEnabled = data.get("widget_enabled").asBoolean(false);
```suggestion
        this.widgetEnabled = data.path("widget_enabled").asBoolean(false);
```

2022-08-09 09:22 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
>      }
Please create an enum instead. I think they are bitwise or'd so you can return an EnumSet but this has to be checked if this is really the case

2022-08-09 09:22 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/invite/WelcomeScreenImpl.java
> +                }
Remove this. If it's up to 5 then Discord should enforce this rule. But if they decide to increase the limit we would need to update the library

2022-08-09 09:22 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/invite/WelcomeScreenImpl.java
> +        return welcomeScreenChannels;
```suggestion
        return Collections.unmodifiableList(welcomeScreenChannels);
```

2022-08-09 09:22 UTC, AhmedA1559 approved these changes

2022-08-09 09:24 UTC, KILLEliteMaste requested changes

2022-08-09 09:24 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/invite/WelcomeScreenChannel.java
> +
```suggestion
```

2022-08-09 09:33 UTC, RealYusufIsmail requested changes

2022-08-09 09:33 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * whether the guild has the boost progress bar enabled.
```suggestion
     * whether the guild's nitro progress bar is enabled.
```
use nitro or boost

2022-08-09 09:33 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/invite/WelcomeScreen.java
> +     * the server description shown in the welcome screen.
```suggestion
     * Gets the server description shown in the welcome screen.
```

2022-08-09 09:33 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/invite/WelcomeScreen.java
> +     * the channels shown in the welcome screen, up to 5.
```suggestion
     * Gets the channels shown in the welcome screen, up to 5.
```

2022-08-09 09:33 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/invite/WelcomeScreenChannel.java
> +     * the channel's id.
```suggestion
     * Gets the channel's id.
```

2022-08-09 09:33 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/invite/WelcomeScreenChannel.java
> +     * the description shown for the channel.
```suggestion
     * Gets the description shown for the channel.
```

2022-08-09 09:33 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/invite/WelcomeScreenChannel.java
> +     * the emoji id, if the emoji is custom.
```suggestion
     * Gets the emoji id, if the emoji is custom.
```

2022-08-09 09:33 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/invite/WelcomeScreenChannel.java
> +     * the emoji name if custom, the unicode character if standard, or null if no emoji is set.
```suggestion
     * Gets the emoji name if custom, the unicode character if standard, or null if no emoji is set.
```

2022-08-09 09:33 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +     */
```suggestion
    /**
     * True if the server widget is enabled.
     */
    private volatile boolean widgetEnabled;

    /**
     * The channel id that the widget will generate an invite to, or null if set to no invite.
     */
    private volatile long widgetChannelId;

    /**
     * The maximum number of presences for the guild (null is always returned, apart from the largest of guilds).
     */
    private volatile int maxPresences;

    /**
     * The maximum number of members for the guild.
     */
    private volatile int maxMembers;

    /**
     * The maximum amount of users in a video channel.
     */
    private volatile int maxVideoChannelUsers;

    /**
     * The welcome screen of a Community guild, shown to new members, returned in an Invite's guild object.
     */
    private volatile WelcomeScreen welcomeScreen;
    /**
     * Whether the guild has the boost progress bar enabled.
     */
```

2022-08-09 09:34 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +     */
can you the same for the other.

2022-08-10 05:08 UTC, shubhwip commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * whether the guild has the boost progress bar enabled.
`boost` is used everywhere across the project so will go with that :)

2022-08-10 07:07 UTC, KILLEliteMaste requested changes

2022-08-10 07:07 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/invite/WelcomeScreenChannelImpl.java
> +    private final Long channelId;
```suggestion
    private final long channelId;
```

2022-08-10 07:07 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/invite/WelcomeScreenChannelImpl.java
> +        this.description = data.hasNonNull("description") ? data.get("description").asText() : null;
```suggestion
        this.channelId = data.get("channel_id").asLong();
        this.description = data.get("description").asText();
```

2022-08-10 07:07 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/invite/WelcomeScreenChannelImpl.java
> +        return Optional.ofNullable(description);
```suggestion
    public long getChannelId() {
        return channelId;
    }

    @Override
    public String getDescription() {
        return description;
```

2022-08-10 07:07 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/invite/WelcomeScreenImpl.java
> +        if (data.has("welcome_channels")) {
if clause can be removed as the JSON always contains the array

2022-08-10 07:25 UTC, shubhwip commented on javacord-core/src/main/java/org/javacord/core/entity/server/invite/WelcomeScreenImpl.java
> +        if (data.has("welcome_channels")) {
How do we find out from discord docs that value will be always `non null` ?  My guess was if a `field` has question mark at the end in discord docs then its value can be null sometimes.

2022-08-10 07:34 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/invite/WelcomeScreenImpl.java
> +        if (data.has("welcome_channels")) {
If the field has a question mark it means that the field may be absent. When the type has a question mark it can be `null`. But the `welcom_channels` doesn't have a single question mark
![image](https://user-images.githubusercontent.com/31566807/183842214-fbe81285-5a2d-4879-84e7-35d4e257ee46.png)

2022-08-10 08:01 UTC, RealYusufIsmail requested changes
Other than that LGTM

2022-08-10 08:01 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/SystemChannelFlag.java
> + */
I would suggest to write something better, this does not really explain what the purpose of the system channel flags are.

2022-08-10 08:25 UTC, RealYusufIsmail approved these changes

2022-08-10 08:35 UTC, KILLEliteMaste requested changes

2022-08-10 08:35 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +        return systemChannelFlags;
```suggestion
        return EnumSet.copyOf(systemChannelFlags);
```

2022-08-10 08:35 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +    }
You forgot to remove this

2022-08-10 08:35 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +        return getWidgetChannelId().flatMap(channelId -> getRegularChannelById(channelId));
```suggestion
        return getWidgetChannelId().flatMap(this::getRegularChannelById);
```

2022-08-10 08:45 UTC, RealYusufIsmail approved these changes

2022-08-10 08:46 UTC, RealYusufIsmail requested changes

2022-08-10 08:46 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +    }
```suggestion
    @Override
    public EnumSet<SystemChannelFlag> getSystemChannelFlags() {
        return EnumSet.copyOf(systemChannelFlags);
    }
```

2022-08-10 08:54 UTC, RealYusufIsmail approved these changes
LGTM

2022-08-10 08:56 UTC, KILLEliteMaste approved these changes
Thank you, LGTM!

2022-08-10 08:58 UTC, merged