Added Session-specific Gateway Resume URLs
Javacord/Javacord pull request #1102
Opened 2022-08-09 20:50 UTC by RealYusufIsmail

closes #1074

2022-08-09 20:51 UTC, RealYusufIsmail commented
blocked until #1073

2022-08-15 18:32 UTC, KILLEliteMaste commented
Docs got a bit [clearer ](https://github.com/discord/discord-api-docs/commit/4ca01c593d7bc7c3f329cb3882fc03d495bc35fa)and we should not use the resume url when the session is invalid

2022-08-17 11:43 UTC, RealYusufIsmail commented
> Docs got a bit [clearer ](https://github.com/discord/discord-api-docs/commit/4ca01c593d7bc7c3f329cb3882fc03d495bc35fa)and we should not use the resume url when the session is invalid

will check it out

2022-08-22 15:59 UTC, KILLEliteMaste requested changes
I got this from the Discord Devs server how to handle the resumeUrl properly maybe this helps you as some things are missing I think:
```
Cache resume url just like you do session id
- do I have session id?
 - no, ready, cache resume url and session
 - yes
  - do i have resume url?
  - no, resume to default
  - yes, resume to url

- did my resume fail?
 - no, all is well
 - yes, invalidate resume url & session
```

I am wondering, don't we have to set the session id and now resumeUrl to null in case we receive an `INVALID_SESSION`? Unfortunately I have no experience with the Discord Websocket so far so i can't really tell.

2022-08-22 15:59 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +            if (sessionId == null) {
Why do you check if the session id is null? And you have duplicated code when the resumeUrl is null. This can be simplified by only checking whether resumeUrl is null

2022-08-22 15:59 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +            resumeUrl = null;
Shouldn't the session id be set to null too in this case?

2022-08-22 16:00 UTC, RealYusufIsmail commented
Will check it out

2022-08-24 14:47 UTC, KILLEliteMaste requested changes

2022-08-24 14:47 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +    private String resumeUrl = null;
```suggestion
    private volatile String resumeUrl = null;
```

2022-09-02 15:51 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
I don't get these changes. Any explanations on why you added it?
This looks to me as if the flag is false, you're not doing anything and just let the bot die.

2022-09-02 16:07 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
The Boolean d identifies if the api can be resume or not. JDA does something similar

2022-09-02 16:46 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
I know. But how would that be relevant here? We are not resuming, we are sending an identify(``sendIdentify``). So why would it matter if it is resumable?

2022-09-02 16:47 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
In the case that `d` is false the session is *not* resumable and from this point I presume we wait for the disconnect and start a full reconnect

2022-09-02 16:48 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
As I said, we are not resuming. We are identifying...

2022-09-02 16:50 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
Oh, in that case yes that is correct https://discord.com/developers/docs/topics/gateway#resuming

2022-09-02 16:53 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
Before this code block, we wait the 1-5 random seconds and then send an identify. I do not get why we would base that on the flag. This worked perfectly fine so far and I see no justification to change this in a PR that just aims to dynamically change the url used for resuming

2022-09-02 16:57 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
I agree with doing this before the 1-5s wait but this is currently nonconformant to the gateway docs. Leaving it like this will just cause longer reconnect delays if we try to resume an un-resumable invalid session

2022-09-02 17:01 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
How exactly is this nonconformant?

```
1. Connection lost
2. Reconnect to the gateway
3. Send Opcode 6 Gateway Resume packet with session id
4. Gateway replies with opcode 9 invalid session (e.g. because the network loss was just too long)
5. We wait 1-5 seconds
6. We send an identify
```
We're doing steps 4 to 6 right here. And I don't get how the "d" flag would have any influence on wether or not we should send a fresh identify as documented in the link you sent above

2022-09-02 17:14 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
Given [this PR](https://github.com/discord/discord-api-docs/pull/5323) (which is apparently not yet included in the docs website), the actual strategy should be to set the resume url to null and close the connection using ``sendCloseFrame``, and then let Javacord automatically create a new connection. Right?

2022-09-02 17:15 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
> the gateway has invalidated an active session and is requesting client action

We may also be able to receive INVALID_SESSION *before* a disconnect

2022-09-02 17:21 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
Hmh. So, given that we should do the following:
```
Received Opcode 9
- Clear resume URL and session ID
- Did we just try to resume?
  Yes: Wait 1-5 seconds
  No: Continue without delay
- send close frame
```

2022-09-03 13:31 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
how do i check if we should resume

2022-09-03 13:31 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                }
would i use the boolean d

2022-09-11 20:09 UTC, RealYusufIsmail commented
I think I am done though I am unsure if I have done this right. @KILLEliteMaste any ideas

2022-09-14 11:02 UTC, bassner requested changes

2022-09-14 11:02 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                            WebSocketCloseReason.COMMANDED_RECONNECT.getCloseReason());
I don't think COMMANDED_REDIRECT is there correct code to use here. Discord has not commanded a reconnect, we just have an invalid session. We could just use the normal DISCONNECT close code here I guess ... Discord doesn't care afaik but using COMMANDED_REDIRECT is definitely incorrect

2022-09-14 20:06 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +            new AtomicMarkableReference<>(null, false);
Yeah sounds reasonable, will implement it tomorrow or the latest the weekend

2022-09-15 17:55 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                    sendIdentify(websocket);
can you check if i have done this right in my lates commit

2022-09-15 17:55 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +            new AtomicMarkableReference<>(null, false);
can you check if i have done this right in my lates commit

2022-09-17 00:14 UTC, bassner requested changes

2022-09-17 00:14 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
>                      api.getGatewayIdentifyRatelimiter().requestQuota();
Huh? We don't want to send an identify here. You're still disconnecting right after this, right? Please remove the sendIdentify and the requestQuota

2022-09-17 05:15 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
>                      api.getGatewayIdentifyRatelimiter().requestQuota();
ok

2022-09-17 05:17 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
>                      api.getGatewayIdentifyRatelimiter().requestQuota();
why was sendIdentify used in the past.

2022-09-17 12:51 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
>                      api.getGatewayIdentifyRatelimiter().requestQuota();
because we didn't reconnect and used the existing connection instead
And now we do reconnect

2022-09-17 13:16 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
>                      api.getGatewayIdentifyRatelimiter().requestQuota();
ok, so does everything look good now, like as in done

2022-09-18 11:02 UTC, bassner requested changes

2022-09-18 18:04 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                    if (triedToResume) {
what do you mean

2022-09-18 18:06 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                    if (triedToResume) {
ah i see

2022-09-24 14:52 UTC, KILLEliteMaste requested changes
Other than that it LGTM!

2022-09-24 14:52 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
> +                    logger.info("Hit identifying rate limit. Reconnecting ...");
```suggestion
                    logger.info("Hit identifying rate limit. Reconnecting...");
```

2022-09-24 16:27 UTC, KILLEliteMaste approved these changes

2022-09-24 17:24 UTC, bassner commented
I'll test this branch in a staging environment to see if it's stable

2022-09-26 13:40 UTC, bassner commented
This seems to work properly on my system 👍 
![grafik](https://user-images.githubusercontent.com/23171488/192291580-687a18cc-690d-462f-9bf5-bd89f5be4dfc.png)

2022-09-26 13:40 UTC, bassner approved these changes

2022-09-26 14:51 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/gateway/WebSocketCloseReason.java
> +            "reconnecting."),
yeah thats better

2022-09-26 14:53 UTC, RealYusufIsmail commented
@bassner if is all ok, can you merge it.

2022-09-26 14:53 UTC, bassner approved these changes

2022-09-26 14:57 UTC, merged