Improve CONTRIBUTING file and add PR template
Javacord/Javacord pull request #1105
Opened 2022-08-10 16:04 UTC by KILLEliteMaste

Below you will see how the PR template is rendered.

---

## Description

## Checklist
- [ ] I have tested this PR[^1].
- [ ] I have read the [contributing guidelines](./CONTRIBUTING.md).

## Changelog
- 

### Breaking Changes

Closes Issue: NaN

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2022-08-10 17:47 UTC, RealYusufIsmail commented
what just thinking about this

2022-08-10 17:53 UTC, RealYusufIsmail requested changes

2022-08-10 17:53 UTC, RealYusufIsmail commented on .github/PULL_REQUEST_TEMPLATE.md
> +Closes Issue: NaN
```suggestion
closes : NaN
```
I would change it to this, as Closes Issue does not really register with Github so it does not actually show it in Development section but closes :  works

2022-08-10 17:53 UTC, RealYusufIsmail commented on .github/PULL_REQUEST_TEMPLATE.md
> +### Breaking Changes
```suggestion
### Changes

- [ ] Existing code
- [ ] New feature

<!-- 
Write down the changes this PR introduces. 
If there are breaking changes list them separately.
-->
## Changelog
- 

### Breaking Changes
```

2022-08-10 17:53 UTC, RealYusufIsmail commented on .github/PULL_REQUEST_TEMPLATE.md
> +### Breaking Changes
up to you

2022-08-10 17:53 UTC, RealYusufIsmail commented on .github/PULL_REQUEST_TEMPLATE.md
> +
In my opinion this should go at the bottom, it means it less cluttered

2022-08-10 17:54 UTC, RealYusufIsmail commented
Also do you mind adding an issue template, i.e if its an issue or a feature request.

2022-08-10 18:26 UTC, KILLEliteMaste commented on .github/PULL_REQUEST_TEMPLATE.md
> +### Breaking Changes
There are arguments against this approach https://github.com/Javacord/Javacord/issues/767#issuecomment-856255155 which I agree with

2022-08-10 18:27 UTC, RealYusufIsmail commented on .github/PULL_REQUEST_TEMPLATE.md
> +### Breaking Changes
ok

2022-08-13 14:17 UTC, KILLEliteMaste commented
Bug Report issue form:
![github com_KILLEliteMaste_Javacord_blob_improvement_contributing_ github_ISSUE_TEMPLATE_bug_report yml](https://user-images.githubusercontent.com/31566807/184498105-6d6a40a0-384b-4871-8056-35a673b145b2.png)

Feature request template form:
![github com_KILLEliteMaste_Javacord_blob_improvement_contributing_ github_ISSUE_TEMPLATE_bug_report yml (3)](https://user-images.githubusercontent.com/31566807/184498161-e1f40474-5644-4ddb-9280-864523e8feac.png)

2022-09-11 20:15 UTC, RealYusufIsmail commented on .github/PULL_REQUEST_TEMPLATE.md
> +Closes Issue: NaN
Why was this ignored

2022-09-11 20:15 UTC, RealYusufIsmail requested changes
Other than LGTM

2022-10-03 08:57 UTC, Saladoc requested changes

2022-10-03 08:57 UTC, Saladoc commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +        or are unsure if this is really a bug, make sure to:
```suggestion
        This form is only for submitting feature requests. If you have a usage question
        or are unsure if the feature you propose does exist already, make sure to:
```

2022-10-03 08:57 UTC, Saladoc commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +      required: false
The placeholder text is at odds with the validations. The placeholder text suggests this being optional, the validation enforces it. Either one must change to be consistent.

2022-10-03 09:53 UTC, KILLEliteMaste commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +      required: false
I am not sure what you mean. The validation rule is set to **not** required.

2022-10-03 09:57 UTC, Saladoc commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +      required: false
So I either had a display error or a mixup here. That's strange.

2022-10-03 10:05 UTC, merged