Improve release workflow
Javacord/Javacord pull request #1106
Opened 2022-08-14 05:25 UTC by shubhwip

resolves #1033

2022-08-14 07:08 UTC, shubhwip commented
Shall we address this one #990 in the last step of this workflow after auto merging PR ?

2022-09-04 16:28 UTC, Bastian commented
Sorry for the late response. If you want to, feel free to also do #990 :)

2022-09-04 16:29 UTC, Bastian commented on .github/workflows/release.yml
> +      - name: Setup Gradle
What's the reason for the Gradle Build as the last step?

2022-09-04 16:36 UTC, Bastian commented on .github/workflows/release.yml
> +          milestone: 1
This is the wrong milestone.
The correct milestone would be dynamic (the one for the version, e.g. 17 -> https://github.com/Javacord/Javacord/milestone/17). Since it's probably pretty complicated to fine the correct milestone, it's fine to just skip this and not assign the PR to any milestone.

2022-09-04 16:39 UTC, Bastian commented on .github/workflows/release.yml
> +      # Reference : https://github.com/marketplace/actions/create-pull-request
There's no need to have these "Reference" comments. It's pretty easy to find the documentation for an action if you need it + we don't have these comments on the other actions.

2022-09-04 16:46 UTC, Bastian requested changes
Thanks for the PR! 🎉 
Looks good overall, just some minor problems, see the code comments :)

2022-09-18 11:38 UTC, Bastian approved these changes

2022-09-18 11:44 UTC, merged

2022-09-18 11:45 UTC, Bastian commented
Thank you very much! 🎉