[Breaking change] Updated Ban system
Javacord/Javacord pull request #1113
Opened 2022-08-31 05:31 UTC by RealYusufIsmail

Removed reason as it has been removed.

Changed from delete_message_days to delete_message_seconds

Closes : #1112

2022-08-31 06:41 UTC, KILLEliteMaste requested changes
- Please do not remove the old methods and instead deprecate them so users have some time to migrate. 
- You can already switch to setting the AuditLogReason on the request instead as a parameter but **the reason itself has not been removed from the ban object**. Just how you set it has been (will be) changed.

2022-08-31 06:41 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    default CompletableFuture<Void> banUser(User user, int deleteMessageDuration, TimeUnit unit) {
Please overload with 
`banUser(User user, int deleteMessageDurationInSeconds)` 
`banUser(User user, Duration durationToDeleteMessages)`

2022-08-31 06:41 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * @param deleteMessageDuration The number of messages to delete within the duration. (0-7)
Here and the methods below please change the allowed duration in the Javadoc to `Between 0 and 604800 seconds (7 days) `

2022-08-31 13:06 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    default CompletableFuture<Void> banUser(User user, int deleteMessageDuration, TimeUnit unit) {
No need for the fist one as you can do that with unit

2022-08-31 13:06 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    default CompletableFuture<Void> banUser(User user, int deleteMessageDuration, TimeUnit unit) {
basically ```java
ban(user, 10, TimeUnit.Second, "")
```

2022-09-02 04:58 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    default CompletableFuture<Void> banUser(User user, int deleteMessageDuration, TimeUnit unit) {
I cant even do the first because I would have to remove 
```java
default CompletableFuture<Void> banUser(User user, int deleteMessageDays, String reason) {
        return banUser(user.getId(), deleteMessageDays, reason);
    }
```
due to duplication

2022-09-09 15:48 UTC, RealYusufIsmail commented
@KILLEliteMaste any updates on the pr?

2022-09-09 16:59 UTC, KILLEliteMaste requested changes
> the reason itself has not been removed from the ban object. Just how you set it has been (will be) changed.

You ignored the comment. Add the reason back to everything

2022-09-09 16:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    CompletableFuture<Void> banUser(String userId, Duration duration, String reason);
```suggestion
    default CompletableFuture<Void> banUser(String userId, Duration duration, String reason){
        return banUser(userId, duration.getSeconds(), TimeUnit.SECONDS, reason)
    }
```

2022-09-09 16:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
>       * @return A future to check if the ban was successful.
Missing Javadoc `deprecated` tag

2022-09-09 16:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    }
This should be above the method above

2022-09-09 16:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     *             deleteMessageDays is deprecated by discord.
```suggestion
     * @deprecated Use {@link #banUser(String, int, TimeUnit)} instead.
```
The same for the other deprecations

2022-09-09 17:36 UTC, RealYusufIsmail commented
> > the reason itself has not been removed from the ban object. Just how you set it has been (will be) changed.
> 
> You ignored the comment. Add the reason back to everything

as in the old discord reason, if so that has been removed by discord so it wont work

2022-09-09 19:59 UTC, KILLEliteMaste requested changes

2022-09-09 19:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
>      CompletableFuture<Void> banUser(String userId, int deleteMessageDays, String reason);
```suggestion
    default CompletableFuture<Void> banUser(String userId, int deleteMessageDays, String reason) {
        return banUser(userId, deleteMessageDays, TimeUnit.DAYS, reason);
    }
```
With this we can reduce the implementation to just 1 method

2022-09-09 19:59 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +
Why did you move the method here? You should have moved it just before `default CompletableFuture<Void> banUser(User user, Duration duration, String reason) {` line 2052

2022-09-09 20:01 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +
Sorry, I thought you meant to put above the method for ban which has duration

2022-09-10 11:14 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    default CompletableFuture<Void> banUser(User user, long deleteMessageDuration, TimeUnit unit) {
Is there any specific reason why you choose `long` instead of `int` for the `deleteMessageDuration` ?

2022-09-10 11:19 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    default CompletableFuture<Void> banUser(User user, long deleteMessageDuration, TimeUnit unit) {
yeah, 
<img width="667" alt="Screenshot 2022-09-10 at 12 19 51" src="https://user-images.githubusercontent.com/67903886/189480911-974e4668-ee0c-424f-992c-3d67ec507f33.png">

2022-09-10 11:24 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    default CompletableFuture<Void> banUser(User user, long deleteMessageDuration, TimeUnit unit) {
I think it's better to change it to an `int`. Long exceeds the max value that can be used here so it's overkill and unnecessary. You can still cast the int to a long without any issues

2022-09-10 11:28 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    default CompletableFuture<Void> banUser(User user, long deleteMessageDuration, TimeUnit unit) {
ok

2022-09-10 11:29 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    default CompletableFuture<Void> banUser(User user, long deleteMessageDuration, TimeUnit unit) {
done

2022-09-10 13:23 UTC, KILLEliteMaste approved these changes
LGTM!

2022-09-10 13:29 UTC, merged