Fix ConcurrentModificationException for GUILD_EMOJIS_UPDATE handler
Javacord/Javacord pull request #1121
Opened 2022-09-06 04:50 UTC by ILGO0413

Do not modify iterated collection immediately but modify it after the iteration.

2022-09-09 15:33 UTC, KILLEliteMaste requested changes

2022-09-09 15:33 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildEmojisUpdateHandler.java
> +            server.getCustomEmojis().removeAll(emojiToDelete);
This will not work because it returns an unmodifiable set. Instead you should do it like before with `ServerImpl#removeCustomEmoji` inside the `forEach`

2022-09-09 18:20 UTC, KILLEliteMaste approved these changes
Thank you for the PR, LGTM!
Can you please rebase to the latest version and squash the PR into a single commit?

2022-09-11 12:22 UTC, ILGO0413 commented
As I messed it up, it is easier to apply PR https://github.com/Javacord/Javacord/pull/1124 and close this one.
All changes are the same.
Shame on me for the mess.

2022-09-11 20:08 UTC, RealYusufIsmail commented
What do you mean

2022-09-11 20:09 UTC, RealYusufIsmail commented
Ah i see, can you not rebase

2022-09-12 08:28 UTC, closed without merging