add nsfw for vc
Javacord/Javacord pull request #1127
Opened 2022-09-17 17:39 UTC by RealYusufIsmail

closes : #1126

2022-09-17 19:04 UTC, RealYusufIsmail commented
@KILLEliteMaste can you please check this pr

2022-09-17 20:05 UTC, Zeitheron commented
I would also add the `updateNsfwFlag` method since it is present in [ServerTextChannel#L79](https://github.com/Javacord/Javacord/blob/master/javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannel.java#L79)

2022-10-10 16:58 UTC, Saladoc approved these changes
One typo, but apart from that LGTM

2022-10-10 16:58 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/entity/channel/ServerVoiceChannelUpdaterDelegateImpl.java
> +     * Whether the vc in nsfw or not.
```suggestion
     * Whether the vc is nsfw or not.
```

2022-10-10 17:03 UTC, Saladoc requested changes
As per the conversation on discord, please test the changes and verify the correctness of your code.

2022-10-14 18:45 UTC, RealYusufIsmail commented
Will get on this pr tomorrow

2022-10-14 19:22 UTC, RealYusufIsmail commented
nsfw can be null for vc

2022-10-16 19:02 UTC, Saladoc requested changes
Code-wise everything appears to be in order. 
Please 
 - Rebase and squash your commits
 - Edit the Pull Request description to include at least the changelog portion from the current issue template.

2022-10-17 07:34 UTC, KILLEliteMaste requested changes

2022-10-17 18:30 UTC, Saladoc requested changes

2022-10-17 19:27 UTC, KILLEliteMaste approved these changes

2022-10-17 21:10 UTC, Saladoc approved these changes

2022-10-17 21:10 UTC, merged