Add the ability to listen for replies to specific messages
Javacord/Javacord pull request #1139
Opened 2022-10-03 14:02 UTC by Mysterypotatoguy

## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](./CONTRIBUTING.md).

## Changelog
- Adds message reply listeners (via `Message#addMessageCreateListener`)

### Breaking Changes
N/A

## Description

Adds the ability to attach message create listeners to messages, which will be fired when the message receives a reply 

Closes: #1114

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2022-10-04 15:12 UTC, KILLEliteMaste reviewed
Imo the `MessageCreateListener` doesn't fit name wise for this purpose. We are not listening for MessageCreates but rather for MessageReplies. And adding a `MessageCreateListener` to a message is not that obvious that you are waiting for replies. For that reason I think a new `MessageReplyListener` (can extend from `MessageCreateListener`) would make more sense

2022-10-04 15:24 UTC, KILLEliteMaste commented
> Should a `MessageReplyListener` have its own event `MessageReplyEvent` or should it still use the `MessageCreateEvent`?

I think it's own event is better. Then we can also add `getReferencedMessage` and `requestReferencedMessage` to the event like we have for the message content.

2022-10-05 10:25 UTC, Saladoc commented
Semantics question for `MessageReplyEvent`: 
If attached to a `User` / `MessageAuthor`, does it 
 * Trigger for messages in Reply to that user / author?
 * Trigger for messages by that user / author?

2022-10-05 10:42 UTC, Mysterypotatoguy commented
It doesn't necessarily have to be attachable to `User`/`MessageAuthor`

2022-10-05 13:21 UTC, Vampire commented
Why not both?

2022-10-12 17:44 UTC, KILLEliteMaste requested changes

2022-10-12 17:44 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/listener/message/MessageReplyListener.java
> +        ObjectAttachableListener {
Shouldn't the interface extend the same interfaces as the `MessagecreateListener`?

2022-10-12 17:44 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/event/message/MessageReplyEventImpl.java
> +    private Message referencedMessage;
```suggestion
    private final Message referencedMessage;
```

2022-10-12 17:44 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
> +        optionalReferencedMessage.ifPresent(referencedMessage -> {
```suggestion
        message.getReferencedMessage().ifPresent(referencedMessage -> {
```
And remove the variable assignment in line 93

2022-10-12 18:20 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/listener/message/MessageReplyListener.java
> +        ObjectAttachableListener {
Not sure, do we really want this being attachable to Servers and TextChannels? The semantics seem very weird to me

2022-10-12 19:28 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/listener/message/MessageReplyListener.java
> +        ObjectAttachableListener {
Why not? You listen to replies happening in a specific channel or server. I cannot see where that would be weird.

2022-10-16 18:29 UTC, KILLEliteMaste requested changes

2022-10-16 18:29 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
> +            }
```suggestion
            message.getAuthor().getWebhookId().ifPresent(webhookIds::add);
            referencedMessage.getAuthor().getWebhookId().ifPresent(webhookIds::add);
```

2022-10-16 18:42 UTC, KILLEliteMaste approved these changes
LGTM!

2022-10-16 19:32 UTC, merged