Add support for Select Menus v2
Javacord/Javacord pull request #1150
Opened 2022-10-14 18:37 UTC by KILLEliteMaste

## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](./CONTRIBUTING.md).

## Changelog
- Add support for select menus v2
- Deprecated SelectMenu#create methods in favor of #createStringMenu
- Add numerous new methods to SelectMenuInteraction to get the new possible values (channels, roles, users)

### Breaking Changes
- SelectMenuBuilder now requires a SELECT_MENU_* component type and a custom_id to be instantiated.

## Description
Add support for the various new select menu types (channel, role, user, mentionable)

Closes: #1149

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2022-10-14 18:48 UTC, RealYusufIsmail requested changes
Currently looks 👍🏻

2022-10-14 18:48 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/message/component/SelectMenuImpl.java
> +     * @param channelTypes     The channel types of the select menu..
```suggestion
     * @param channelTypes      The channel types of the select menu..
```

2022-10-14 18:48 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/handler/interaction/InteractionCreateHandler.java
> +                            + "Please contact the developer!", componentTypeId);
Might change this to create an issue or instead of the developer to a developer

2022-10-14 19:09 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/util/handler/interaction/InteractionCreateHandler.java
> +                            + "Please contact the developer!", componentTypeId);
ok

2022-10-16 21:00 UTC, Saladoc approved these changes
LGTM, I only found a small inconsistency with the pluralization of method / field names.

2022-10-16 21:07 UTC, RealYusufIsmail approved these changes
Apart from LGTM

2022-10-16 21:07 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/interaction/SelectMenuInteractionImpl.java
> +        if (componentType == ComponentType.SELECT_MENU_CHANNEL) {
Can a switch no be used instead of all these if else

2022-10-16 21:41 UTC, merged