added get thread member endpoint
Javacord/Javacord pull request #1155
Opened 2022-10-18 16:43 UTC by RealYusufIsmail

## Checklist
- [ ] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](./CONTRIBUTING.md).

## Changelog
- 
Added the ability to get a thread member by there id.

### Breaking Changes

## Description

Closes: https://github.com/Javacord/Javacord/issues/906

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2022-10-18 18:15 UTC, RealYusufIsmail commented
@Saladoc can you review this pr please

2022-10-18 19:18 UTC, Saladoc requested changes
Methods that (might) do a rest request under the hood should be named `requestXY`. Methods that return a local value (for example from cache) should be named `getXY`.

Also please keep your method descriptions consistent. We usually describe what a method does (`Gets a Foo from the Bar`), not what the method is used for (`Used to get a Foo from the Bar`)

2022-10-18 19:21 UTC, Mysterypotatoguy requested changes
I'd argue `getThreadMembers` may need to be renamed to `requestThreadMembers` too, but this would be a breaking change

2022-10-18 19:21 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ThreadMember.java
> -
Revert line removal

2022-10-18 19:21 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannel.java
> +    CompletableFuture<ThreadMember> getThreadMember(long userId);
```suggestion
    CompletableFuture<ThreadMember> requestThreadMemberById(long userId);
```

2022-10-18 19:21 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannel.java
> +    default CompletableFuture<ThreadMember> getThreadMember(String userId) {
```suggestion
    default CompletableFuture<ThreadMember> requestThreadMemberById(String userId) {
```

2022-10-18 19:24 UTC, Saladoc commented
> I'd argue `getThreadMembers` may need to be renamed to `requestThreadMembers` too, but this would be a breaking change

We can rename the method, keep an old one in that calls the new one and deprecate it in favor of the new one.

2022-10-18 20:08 UTC, Saladoc requested changes

2022-10-18 20:08 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannel.java
> +    CompletableFuture<Set<ThreadMember>> requestThreadMembers();
This is a breaking change. Please restore the old method and deprecate it in favor of the new method.

2022-10-19 15:32 UTC, Saladoc approved these changes

2022-10-19 15:34 UTC, Mysterypotatoguy approved these changes

2022-10-19 15:40 UTC, merged