added new error code 50039
Javacord/Javacord pull request #1163
Opened 2022-10-23 11:00 UTC by RealYusufIsmail

## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](./CONTRIBUTING.md).

## Changelog
- Added the new error code 50039

### Breaking Changes

## Description
https://github.com/discord/discord-api-docs/commit/9174f05ca633772a78a4339fa576bded66bc45f9#diff-2adb841744dbfb715ce95d82e0c7bad2a498da041ee52c1282e2336286b8361a

Closes: NaN

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2022-10-23 13:12 UTC, RealYusufIsmail commented
@KILLEliteMaste can you please review this

2022-10-24 18:17 UTC, KILLEliteMaste requested changes

2022-10-24 18:17 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/rest/RestRequestResultErrorCode.java
> +    INVALID_ACTIVITY_ACTION(50039, "Invalid Activity Action"),
Seems weird to me that every word start with a capital. Maybe a typo in the docs?
```suggestion
    INVALID_ACTIVITY_ACTION(50039, "Invalid activity action"),
```

2022-10-24 23:51 UTC, KILLEliteMaste approved these changes

2022-10-24 23:52 UTC, merged