Fix:Wrong links in readme
Javacord/Javacord pull request #1178
Opened 2022-11-01 08:42 UTC by haseeb-xd

Issue #1174

Please review the PR

2022-11-01 08:52 UTC, haseeb-xd commented
wait for my other fix

2022-11-01 12:38 UTC, Saladoc requested changes

2022-11-01 12:38 UTC, Saladoc commented on .github/README_template.md
> +It has rich [documentation](https://javacord.org/wiki/) and an [awesome community on Discord](https://discord.com/invite/javacord) that loves to help with any specific problems and questions.
Do not change links that are not broken. The internal links are working perfectly fine.

2022-11-01 12:38 UTC, Saladoc commented on .github/README_template.md
> +Contributions of any kind are welcome. You can start contributing to this library by creating issues, submitting pull requests or improving the [Javacord Wiki](https://javacord.org/wiki/).
Since this is the contributing section, the link is meant to go to the github repository.

2022-11-01 12:38 UTC, Saladoc commented on .github/README_template.md
> +If you are not familiar with build managers, you can follow this [setup guide](https://javacord.org/wiki/getting-started/setup/intellij-gradle.html) or download Javacord directly from [GitHub](https:
Do not change links that are not broken. The internal links are working perfectly fine.

2022-11-01 16:01 UTC, Saladoc approved these changes
Thanks for the fix. Please rebase on master and squash your commits into one for merging.

2022-11-03 13:43 UTC, merged

2022-11-03 13:44 UTC, KILLEliteMaste commented
@all-contributors please add @haseeb-xd for doc