Fix deprecated IP Discovery UDP packet size
Javacord/Javacord pull request #1216
Opened 2023-03-02 02:17 UTC by KILLEliteMaste

## Checklist
- [ ] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Changed deprecated IP Discovery UDP packet size to 74 which is required from the 15.03.23 onwards

## Description
![image](https://user-images.githubusercontent.com/31566807/222313586-0ace5734-d75f-4636-b86b-cf20852cc1f0.png)

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2023-03-02 15:21 UTC, Mysterypotatoguy requested changes

2023-03-02 15:21 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/util/gateway/AudioUdpSocket.java
>          ByteBuffer.wrap(buffer).putInt(0, ssrc);
```suggestion
        ByteBuffer.wrap(buffer)
            .putShort((short) 1)
            .putShort((short) 70)
            .putInt(ssrc);
```

Ref: https://discord.com/developers/docs/topics/voice-connections#ip-discovery
Apparently this changed in 2019 and we never noticed

2023-03-02 15:21 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/util/gateway/AudioUdpSocket.java
>          String ip = new String(Arrays.copyOfRange(buffer, 3, buffer.length - 2)).trim();
```suggestion
        String ip = new String(buffer, 8, buffer.length - 2).trim();
```

2023-03-02 16:20 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/gateway/AudioUdpSocket.java
>          String ip = new String(Arrays.copyOfRange(buffer, 3, buffer.length - 2)).trim();
Had to change this to `new String(buffer, 8, buffer.length - 10).trim();` otherwise it would throw an error. There was also an issue with the port, which was hardcoded so it would obviously no longer work since the array changed

2023-03-02 16:33 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/util/gateway/AudioUdpSocket.java
>          String ip = new String(Arrays.copyOfRange(buffer, 3, buffer.length - 2)).trim();
Ah yes, port should be
`int port = ByteBuffer.wrap(new byte[]{buffer[69], buffer[68]}).getShort() & 0xffff;` or
`int port = ByteBuffer.wrap(new byte[]{buffer[buffer.length -1], buffer[buffer.length - 2]}).getShort() & 0xffff;`

My bad on the `String`, the last parameter is a length not an end index

2023-03-05 00:57 UTC, Mysterypotatoguy approved these changes

2023-03-05 01:45 UTC, merged