Fix interactions in text-in-voice channels
Javacord/Javacord pull request #1223
Opened 2023-03-26 21:28 UTC by Mysterypotatoguy

## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Fixes AssertionError when receiving interactions from text-in-voice channels

Closes: #1222 

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2023-03-26 22:16 UTC, felldo requested changes

2023-03-26 22:16 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/util/handler/interaction/InteractionCreateHandler.java
> +                        .orElse(null);
Makes it easier to debug next time
```suggestion
                        .orElseThrow(AssertionError::new);
```

2023-03-26 22:28 UTC, felldo reviewed
Not exactly sure what I am doing wrong, but if I send a slash command in the voice channel as described in the issue and I do not get any error. And since every TextableRegularServerChannel is a TextChannel, we should be able to get the voice channel

2023-03-26 22:40 UTC, Mysterypotatoguy commented
Well that's super odd, I was able to reproduce it earlier and now I cannot 🤔
Perhaps this is some caching issue with text-in-voice channels instead?

2023-03-26 22:42 UTC, felldo commented
> Well that's super odd, I was able to reproduce it earlier and now I cannot 🤔 Perhaps this is some caching issue with text-in-voice channels instead?

This would be my first guess, that the channel is not even cached

2023-03-27 07:42 UTC, RealMarvn commented
Ok so I have other commands which try to get the voice channel by ID. Those work great most of the time. The only leak is when I try to get the voice channel via getConnectedVoiceChannel. It could be a cache issue. But I have never watched inside Javacord.

2023-08-08 10:37 UTC, closed without merging