Add server scheduled events
Javacord/Javacord pull request #1243
Opened 2023-04-18 22:04 UTC by felldo

## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Added support for server scheduled events

Closes: #1097 

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2023-04-19 10:30 UTC, Saladoc requested changes
Great work, I've noted some things I stumbled acrosss and suggestions.

2023-04-19 10:30 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/ServerScheduledEventBuilder.java
> +
```suggestion

    /**
     * Sets the scheduled start and end time of the server scheduled event.
     *
     * @param scheduledStartTime The scheduled start time of the server scheduled event.
     * @param duration The intended duration to calculate the scheduled end time.
     * @return The current instance in order to chain call methods.
     */
    public ServerScheduledEventBuilder setScheduledStartAndEndTimes(Instant scheduledStartTime, Duration duration) {
        return setScheduledStartTime(scheduledStartTime).setScheduledEndTime(scheduledStartTime.plus(duration));
    }
```
Another convenience method that I reckon will address a common use case. Needs another import to fully work.

Maybe on the updater too?

2023-04-19 10:30 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/ServerScheduledEventUser.java
> +public interface ServerScheduledEventUser {
Type level documentation missing. I assume a participant in a server scheduled event?

2023-04-19 10:30 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/listener/server/scheduledevent/ServerScheduledEventCreateListener.java
> + * This listener listens to server afk channel changes.
```suggestion
 * This listener listens to server scheduled event creations.
```

2023-04-19 10:30 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +                .execute(result -> new ServerScheduledEventImpl(api, result.getJsonBody()));
Shouldn't these also update the locally cached events? Same for the method below.

2023-04-19 10:30 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +    private final Set<ServerScheduledEvent> scheduledEvents = Collections.synchronizedSet(new HashSet<>());
Is there a benefit of using a synchronized set over a `ConcurrentHashMap<Long, ServerScheduledEvent>` with the id as the key?

2023-04-19 10:37 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +        return requestScheduledEventById(eventId, true);
What do you mean? There's an overloaded method below that allows setting the user count

2023-04-19 10:46 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/EntityMetadata.java
> +public interface EntityMetadata {
I also thought about this, but I was thinkin about `ServerScheduledEventMetadata` which is pretty long. The same for the enums. The names are getting pretty long for `ServerScheduledEventPrivacyLevel` too

2023-04-19 10:52 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/ServerScheduledEvent.java
> +    default CompletableFuture<Void> updateToExternalEvent(String entityMetadataLocation, Instant endTime) {
The documentation lead me to this. Just updating an event to type external, requires specific fields to have certain values
![image](https://user-images.githubusercontent.com/31566807/233052968-58556820-03a2-4d72-ab30-3c579c912e15.png)

2023-04-19 10:55 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +        return requestScheduledEventById(eventId, true);
The documentation should reflect the default behavior imho.

2023-04-19 11:01 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +                .execute(result -> new ServerScheduledEventImpl(api, result.getJsonBody()));
Not necessary because we get updates via the Create/UpdateHandler anyway.

2023-04-19 11:04 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +    private final Set<ServerScheduledEvent> scheduledEvents = Collections.synchronizedSet(new HashSet<>());
Not really. But a map might be better since it has better time complexity

2023-04-19 11:20 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +                .execute(result -> new ServerScheduledEventImpl(api, result.getJsonBody()));
If we can be sure that the cached events are always accurate, wouldn't that make the `request...` methods unnecessary then?

2023-04-19 13:54 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +                .execute(result -> new ServerScheduledEventImpl(api, result.getJsonBody()));
I see so you can just get them on demand. That makes sense.

2023-04-20 11:32 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/ServerScheduledEvent.java
> +
Note: It is possible to set the end time for all event types, but it is still not mandatory for non-external events and not even possible in the discord client

2023-04-20 11:38 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/EntityMetadata.java
> +public interface EntityMetadata {
The question now is whether we want to go uniform with the other naming or omit the `server` part (for the enums you mentioned) which may be semantically more correct since they could be used for events outside of servers (group DM events) if this was ever added, which I doubt in the near future.

2023-04-20 14:14 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/ServerScheduledEvent.java
> +    default CompletableFuture<Void> updateToExternalEvent(String entityMetadataLocation, Instant endTime) {
I see. are there corresponding requirements for updating to other types? Are they required to always have a channel for example?

2023-04-20 14:16 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/ServerScheduledEvent.java
> +
Noted. In that case we can of course make the scheduled Duration optional or just omit the method(s). Maybe just the latter, if having an end time can be considered an edge case.

2023-04-20 14:20 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/ServerScheduledEvent.java
> +    default CompletableFuture<Void> updateToExternalEvent(String entityMetadataLocation, Instant endTime) {
> I see. are there corresponding requirements for updating to other types? Are they required to always have a channel for example?

Yes, see https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-object-field-requirements-by-entity-type

2023-04-20 14:28 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/ServerScheduledEvent.java
> +    default CompletableFuture<Void> updateToExternalEvent(String entityMetadataLocation, Instant endTime) {
In that case we should probably provide similar `updateToXY` methods for the other types that accept all requirements specific to the target type.

2023-04-20 21:12 UTC, felldo commented
With your suggested changes, I also added `Server` to the enums. It just doesn't feel alright, to leave it out when the documentation also calls them this way. The only way I see this could go well with a smaller name is moving the enums to the interface, which would also make sense, but we haven't done this anywhere else.
Instead of `ServerScheduledEventPrivacyLevel.SERVER_ONLY` we could have `ServerScheduledEvent.PrivacyLevel.SERVER_ONLY`. With an import, the user can also reduce it to `PrivacyLevel.SERVER_ONLY` without loosing where the enum value actually comes from when importing it completely.

2023-04-21 07:30 UTC, Saladoc approved these changes
Looks good. Just one more thought I noted down, you can decide whether or not that has merit. Since it's a simple matter of naming I'm leaving the decision entirely up to you. Green light.

2023-04-21 07:30 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/scheduledevent/ServerScheduledEventEntityMetadata.java
> +public interface ServerScheduledEventEntityMetadata {
Technically we could omit "Entity" from both here and `ServerScheduledEventEntityType` since we do precisely name the entity as `ServerScheduledEvent`.

This could also be done for the existing getters and setters, but leaving them as is would also be fair game in order to be more consistent with the official discord documentation.

2023-04-21 11:25 UTC, merged