Fixed a cache corruption issue when receiving ephemeral messages in text-in-voice channels
Javacord/Javacord pull request #1251
Opened 2023-07-16 14:00 UTC by bassner

## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Check for TextableRegularServerChannels instead of pure ServerTextChannels when receiving ephemeral messages

### Breaking Changes
None.

## Description

When receiving an ephemeral messages, Javacord was checking if the channel is on a server rather than a DM by looking for ServerTextChannels and ServerThreadChannels. However, ephemeral messages can also be received in voice channels. As Javacord was not checking for that, it created a private channel in the cache with the ID of the voice channel, which corrupted the cache and made further interactions or messages impossible to handle for that specific channel.

Steps to reproduce without this PR:

1. Create a server voice channel
2. Let a bot send a message with a button into that channel.
3. Add a listener so that the bot responds with an ephemeral messages if the button is clicked.
4. Click the button and observe that it works for the first time.
5. Click the button again and see that it doesn't work anymore + see the exception in logs
6. Send a message as a user into the channel and see in the logs how Javacord fails to handle the message

This is potentially the actual fix for the problem of #1223.

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2023-07-16 17:35 UTC, felldo reviewed
I saw that we currently use `getServerTextChannelById` in `WebhooksUpdateHandler` as well. As the voice channels can now have webhooks because of the text channel, would you mind changing this in this PR too?

2023-07-17 13:15 UTC, bassner commented
This actually turns out to not be that easy. I first have to convert `TextableRegularServerChannel` into a fully fledged entity sitting in between voice/text channels and `RegularServerChannel` in the entity hierarchy, with interfaces, updater etc. I'm looking into it but it's quite complex

2023-07-18 12:12 UTC, felldo requested changes
Because the `TextableRegularServerChannel` is now implemented like the other types, methods to the `DiscordApi` should be added to get the channel so you don't have to map the server channel like you do it now.

You put some more fields like the `parentId` in the `TextableRegularServerChannel`. Name wise I think this doesn't really fit in there. But for now I think it is okay

2023-07-18 12:12 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/channel/TextableRegularServerChannelBuilderDelegateImpl.java
> + * The implementation of {@link ServerTextChannelBuilderDelegate}.
```suggestion
 * The implementation of {@link TextableRegularServerChannelBuilderDelegate}.
```

2023-07-18 12:12 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerVoiceChannel.java
>       *
Same here, `updateNsfwFlag` should be in the `TextableRegularServerChannel`?

2023-07-18 12:12 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannel.java
>      @Override
`getMentionTag` can be removed as it's already present in `TextableRegularServerChannel`

2023-08-07 13:32 UTC, RealMarvn commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannel.java
>      @Override
Is there anything new on this pr after your commit?

2023-08-07 16:16 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannel.java
>      @Override
What do you mean?

2023-08-07 16:22 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannel.java
>      @Override
This is not my PR and I just suggested some changes -> haven't commited anything

2023-08-08 10:06 UTC, RealMarvn commented
I still have issues testing it. There is still no #setCategory or #addPermissionOverwrite in for TextChannel builders.

2023-08-08 10:13 UTC, bassner commented
> I still have issues testing it. There is still no #setCategory or #addPermissionOverwrite in for TextChannel builders.

![image](https://github.com/Javacord/Javacord/assets/23171488/b0069147-7911-43a5-9161-74b1d8e64cea)

It works, tho. I guess there's still something wrong with importing this snapshot into your project

2023-08-08 18:55 UTC, felldo requested changes

2023-08-08 18:55 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ChannelType.java
> +    SERVER_STAGE_VOICE_CHANNEL(13, false, true, true, true, false),
```suggestion
    SERVER_STAGE_VOICE_CHANNEL(13, false, true, true, true, true),
```

2023-08-08 18:55 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/channel/TextableRegularServerChannelBuilder.java
> +    public TextableRegularServerChannelBuilder<T> setCategory(ChannelCategory category) {
The same for `setSlowmodeDelayInSeconds`
```suggestion
    public T setCategory(ChannelCategory category) {
```

2023-08-08 18:55 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/channel/TextableRegularServerChannelUpdater.java
> +    public TextableRegularServerChannelUpdater<T> setCategory(ChannelCategory category) {
The same for the other methods
```suggestion
    public T setCategory(ChannelCategory category) {
```

2023-08-13 13:06 UTC, felldo approved these changes
LGTM!

2023-08-14 11:32 UTC, merged