Add message author id to ReactionAddEvent
Javacord/Javacord pull request #1289
Opened 2023-11-11 09:42 UTC by kezc

## Checklist
- [ ] I have tested this PR[^1].
- [ ] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Added message author id to message reaction event

### Breaking Changes
- None

## Description

Closes: https://github.com/Javacord/Javacord/issues/1249

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2023-11-11 15:03 UTC, RealYusufIsmail requested changes

2023-11-11 15:03 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/event/message/reaction/ReactionAddEvent.java
> +     * @return The reaction.
```suggestion
     * @return The message author id.
```

2023-11-11 15:03 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/event/message/reaction/ReactionAddEventImpl.java
> +     */
Java doc is jot required in impls

2023-11-11 17:10 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/event/message/reaction/ReactionAddEventImpl.java
> +     */
That's non-sense.
JavaDoc always makes sense everywhere.
It makes most sense or should always be there on public methods in the public API.
But JavaDoc is always and everywhere better to be there than not to be there.
Thus you should really not motivate people to leave it out, especially when they already added it.

2023-11-11 17:12 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/event/message/reaction/ReactionAddEventImpl.java
> +     */
Ok I apologia

2023-11-11 17:19 UTC, kezc commented on javacord-core/src/main/java/org/javacord/core/event/message/reaction/ReactionAddEventImpl.java
> +     */
Anyway, thanks @RealYusufIsmail  for pointing it out as I was forced to add it by linter and I've started wondering why. Now I see that `@Override` annotation is missing.

2023-11-11 17:24 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/event/message/reaction/ReactionAddEventImpl.java
> +     */
Ah, sorry @RealYusufIsmail, I misread your comment as "you don't need to add JavaDoc to core classes", which are our "implementation" of the logic.

That you don't need it on methods that implement an interface if you properly inherit the JavaDoc is true of course.

2023-11-11 18:21 UTC, kezc commented on javacord-core/src/main/java/org/javacord/core/event/message/reaction/ReactionAddEventImpl.java
> +     */
Ok, I've removed the unnecessary JavaDoc.

2023-11-11 18:57 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/event/message/reaction/ReactionAddEventImpl.java
> +     */
> classes

Not a problem.

2023-11-11 18:58 UTC, RealYusufIsmail approved these changes
LGTM. Please squash you commits and one of the contrubters will merge your pr if they approve.

2023-11-13 11:34 UTC, felldo requested changes

2023-11-13 11:34 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionAddHandler.java
> +        long messageAuthorId = packet.get("message_author_id").asLong();
```suggestion
        Long messageAuthorId = packet.hasNonNull("message_author_id") ? packet.get("message_author_id").asLong() : null;
```

2023-11-13 11:34 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/event/message/reaction/ReactionAddEventImpl.java
> +    private final long messageAuthorId;
```suggestion
    private final Long messageAuthorId;
```

2023-11-13 11:34 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/event/message/reaction/ReactionAddEventImpl.java
> +                                long userId, Member member, long messageAuthorId) {
```suggestion
                                long userId, Member member, Long messageAuthorId) {
```

2023-11-13 11:34 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/event/message/reaction/ReactionAddEventImpl.java
> +        return messageAuthorId;
```suggestion
    public Optional<Long> getMessageAuthorId() {
        return Optional.ofNullable(messageAuthorId);
```

2023-11-13 11:34 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/event/message/reaction/ReactionAddEvent.java
> +    long getMessageAuthorId();
```suggestion
    Optional<Long> getMessageAuthorId();
```
This is an optional field and should return an `Optional<Long>`

2023-11-17 07:29 UTC, kezc commented on javacord-api/src/main/java/org/javacord/api/event/message/reaction/ReactionAddEvent.java
> +    long getMessageAuthorId();
Good point, thank you!

2024-01-19 20:57 UTC, felldo approved these changes
LGTM! Thanks!

2024-01-19 21:00 UTC, merged