Add attachment flags
Javacord/Javacord pull request #1292
Opened 2023-11-16 19:07 UTC by mikolaj-skrzypczak

## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Added attachment flags

### Breaking Changes
None

## Description

Closes: #1248

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2023-11-17 16:14 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
> +        flags = bitfield != null ? AttachmentFlags.getFlagTypeByBitfield(bitfield) : null;
can these not be combined together, rather than having a separate variable

2023-11-18 13:04 UTC, mikolaj-skrzypczak commented on javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
> +        flags = bitfield != null ? AttachmentFlags.getFlagTypeByBitfield(bitfield) : null;
I guess I could change it to:
```java
flags = data.hasNonNull("flags")
                ? AttachmentFlags.getFlagTypeByBitfield(data.get("flags").asInt())
                : null;
```
Would that be a satisfying solution for you?

2023-11-18 17:54 UTC, RealYusufIsmail commented on javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
> +        flags = bitfield != null ? AttachmentFlags.getFlagTypeByBitfield(bitfield) : null;
yeah that works

2023-11-18 19:28 UTC, RealYusufIsmail approved these changes
LGTM. Please squash your commits then wait for a review so they can check then merge

2024-01-13 19:37 UTC, mikolaj-skrzypczak commented
Is there any chance for those changes to be merged any time soon? I kind of need it to pass one task in one of the courses in my studies 😅

2024-01-13 22:32 UTC, felldo requested changes
Sorry for the late response, but here we go! I've outlined some issues with your code which would need to be fixed first before we can merge your PR :)

2024-01-13 22:32 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/AttachmentFlags.java
> +    private final int bitfield;
This is not a bitfield, but only the value of the flag. The bitfield would be something like `010` where the `1` corresponds to a specific flag like `IS_REMIX`. And `0` would mean that another potentual flag is not applied for this attachment. So each single digit corresponds alway to one flag.
So please rename it and everywhere else in your newly added code :)
```suggestion
    private final int id;
```

2024-01-13 22:32 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/AttachmentFlags.java
> +    public int getBitfield() {
```suggestion
    public int getId() {
```

2024-01-13 22:32 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/AttachmentFlags.java
> +    public static AttachmentFlags getFlagTypeByBitfield(final int bitfield) {
```suggestion
    public static AttachmentFlags getFlagTypeById(final int id) {
```

2024-01-13 22:32 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
> +                : null;
This is not the correct way to get flags. Please have a look at this, on how to get the flags from a bitfield
https://github.com/Javacord/Javacord/blob/971ea44e5d671d380382e0617fcaeaad070c8d02/javacord-core/src/main/java/org/javacord/core/entity/activity/ActivityImpl.java#L82-L89

2024-01-13 22:32 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/AttachmentFlags.java
> +public enum AttachmentFlags {
```suggestion
public enum AttachmentFlag {
```

2024-01-13 22:32 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
> +    private final AttachmentFlags flags;
```suggestion
    private final EnumSet<AttachmentFlag> attachmentFlags = EnumSet.noneOf(AttachmentFlag.class);
```

2024-01-13 22:32 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
> +     * Attachment flags combined as a bitfield.
```suggestion
     * Attachment flags computed from the bitfield.
```

2024-01-13 22:32 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
> +    public Optional<AttachmentFlags> getFlags() {
```suggestion
    public Optional<EnumSet<AttachmentFlag>> getFlags() {
```

2024-01-13 22:49 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
> +    public Optional<AttachmentFlags> getFlags() {
I think this can just be an `EnumSet<AttachmentFlag>` with an empty set when there are no flags

2024-01-13 22:53 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
> +    public Optional<AttachmentFlags> getFlags() {
> I think this can just be an `EnumSet<AttachmentFlag>` with an empty set when there are no flags

You are right. In this case it wouldn't make sense to return an optional, as there is no information that we loose when we remove it

2024-01-15 21:02 UTC, mikolaj-skrzypczak commented
@felldo thank you for the review :)
I think that my latest commit adressed the highlighted issues

2024-01-15 22:09 UTC, felldo requested changes

2024-01-16 07:24 UTC, mikolaj-skrzypczak commented on javacord-api/src/main/java/org/javacord/api/entity/AttachmentFlag.java
> +     * @param id attachment flags combined as a bitfield.
🤦, fixed

2024-01-17 23:14 UTC, felldo approved these changes
LGTM! Thanks!

2024-01-17 23:15 UTC, merged