Default allowed mentions
Javacord/Javacord pull request #1293
Opened 2023-12-19 16:32 UTC by TheKodeToad

## Checklist
- [ ] I have tested this PR[^1].
- [ ] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Added default allowed mentions

### Breaking Changes

## Description
I used a slightly hacky approach of passing around DiscordApi. I hope it's okay!

Closes: #527

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2023-12-19 16:56 UTC, TheKodeToad commented
I tested a bot but I didn't test `./gradlew build` :)

2024-01-19 21:26 UTC, felldo requested changes
Looks good so far, but:
* Please rename every field/method/Javadoc so it says `defaultAllowedMentions`.
* You have added the DiscordApi to a few methods, please add it as the first parameter

2024-01-19 21:26 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
> +    }
We usually don't have getters in the `DiscordApiBuilder`
```suggestion
```

2024-01-19 21:26 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/internal/DiscordApiBuilderDelegate.java
> +
```suggestion
```

2024-01-19 22:54 UTC, TheKodeToad commented on javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
> +    }
There are getters for e.g. bot token in the builder 🤔

2024-01-19 23:02 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
> +    }
There are a few exceptions for like the bot token you mentioned or also the total shards. But if you look at the other 30 setters, none of them has getters. Not sure about the exact use case of the current getters, but I doubt getting the allowed mentioned on the builder instance is going to provide any benefits

2024-01-21 16:02 UTC, TheKodeToad commented
Hmm, the constructor which doesn't use a websocket doesn't have a defaultAllowedMentions parameter... is that an issue? It's internal anyway, right?

2024-01-21 16:11 UTC, felldo commented
> Hmm, the constructor which doesn't use a websocket doesn't have a defaultAllowedMentions parameter... is that an issue? It's internal anyway, right?

What do you mean? Can you show me which line?

2024-01-21 16:24 UTC, TheKodeToad commented
> What do you mean? Can you show me which line?

https://github.com/TheKodeToad/Javacord/blob/default-allowed-mentions/javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java#L422

2024-01-21 16:43 UTC, felldo commented
There are a lot of other things the constructor doesn't have, so it's okay

2024-01-22 00:26 UTC, TheKodeToad commented
This PR should be ready then! hopefully I didn't miss anything...

2024-01-22 07:41 UTC, felldo approved these changes
LGTM! Thanks!

2024-01-22 07:42 UTC, merged