Add role flags
Javacord/Javacord pull request #1294
Opened 2023-12-30 19:40 UTC by kezc

## Checklist
- [ ] I have tested this PR[^1].
- [ ] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Add `flags` field to `Role` and implementation in `RoleImpl`.

### Breaking Changes
N/A

## Description
Add `flags` field to `Role`. There's one possible value currently - `IN_PROMPT`. Documentation https://discord.com/developers/docs/topics/permissions

Closes: https://github.com/Javacord/Javacord/issues/1247

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2024-01-13 22:42 UTC, felldo requested changes
Sorry for the late response. I have requested some minimal changes and then this can be merged :)

2024-01-13 22:42 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/permission/Role.java
> +    Set<RoleFlag> getFlags();
```suggestion
    EnumSet<RoleFlag> getFlags();
```

2024-01-13 22:42 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/permission/RoleFlag.java
> +    IN_PROMPT(1 << 0);
Please add a Javadoc https://discord.com/developers/docs/topics/permissions#role-object-role-flags

Also please add a second enum type of `UNKNOWN(-1)` in case when discord adds a new value to the bitmask

2024-01-13 22:42 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/permission/RoleImpl.java
> +    private final Set<RoleFlag> flags = EnumSet.noneOf(RoleFlag.class);
```suggestion
    private final EnumSet<RoleFlag> flags = EnumSet.noneOf(RoleFlag.class);
```

2024-01-13 22:42 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/permission/RoleImpl.java
> +        setRoleFlag(data.get("flags").asInt());
Please move the code directly in to the construcor.

2024-01-13 22:42 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/permission/RoleFlag.java
> +
Missing method to get a flag by it's id / flag value
https://github.com/Javacord/Javacord/blob/971ea44e5d671d380382e0617fcaeaad070c8d02/javacord-api/src/main/java/org/javacord/api/entity/activity/ActivityFlag.java#L26-L38

2024-01-15 17:05 UTC, kezc commented
@felldo thank you for the review! I've added the changes. If you spot anything, let me know, I am more than happy to help!

2024-01-17 23:20 UTC, felldo requested changes
Just some minor things regarding a typo and formatting I missed during the first review

2024-01-17 23:20 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/permission/RoleFlag.java
> +     * @param flag The bitmask of the flag.
```suggestion
     * @param flag The id of the flag.
```

2024-01-17 23:20 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/permission/RoleFlag.java
> +     * Gets the integer value of the role flag.
Missing empty line
```suggestion
     * Gets the integer value of the role flag.
     
```

2024-01-17 23:20 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/permission/RoleFlag.java
> +     * Gets the role flag of the given integer value.
Missing empty line
```suggestion
     * Gets the role flag of the given integer value.
     
```

2024-01-19 20:49 UTC, felldo approved these changes
LGTM! Thanks!

2024-01-19 20:50 UTC, merged