Add Bulk Ban Support
Javacord/Javacord pull request #1301
Opened 2024-03-19 15:27 UTC by wasdennnoch

## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Added bulk ban support
- Fixed NPE in default ban method

### Breaking Changes

## Description

- https://github.com/discord/discord-api-docs/pull/6720
- Also fixes an NPE when calling `Server#banUser(String)`; this method would previously pass `null` as the `Duration` to the other overloads, which would then attempt to call `duration.getSeconds()`.

I'm not 100% confident that the `BulkBanResponse` I used is the way you generally want to approach such cases where an endpoint returns a special object that doesn't occur anywhere else, and I also wasn't quite sure where to put it; for now, I've put it next to the `Ban`  classes representing a single ban. Feedback appreciated.

Closes: NaN

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

2024-03-31 22:52 UTC, felldo requested changes
You missed to add the status code
![image](https://github.com/Javacord/Javacord/assets/31566807/69b417a6-64d3-48af-a793-9c48d8a8454e)

2024-03-31 22:52 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/server/BulkBanResponseImpl.java
> +    private final Set<Long> bannedUserIds = new LinkedHashSet<>();
Is there a specific reason you used a `LinkedHashSet`?

2024-03-31 22:52 UTC, felldo commented on javacord-core/src/main/java/org/javacord/core/entity/server/BulkBanResponseImpl.java
> +    }
Either you should return a unmodifiable copy of the collection or you assign an unmodifiable collection right away to the class fields

2024-03-31 22:52 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +                LongStream.of(userIds).boxed().map(Long::toUnsignedString).collect(Collectors.toList()),
```suggestion
                LongStream.of(userIds).mapToObj(Long::toUnsignedString).collect(Collectors.toList()),
```

2024-03-31 22:52 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +        return bulkBanUsers(Arrays.stream(userIds).collect(Collectors.toList()), 0, TimeUnit.SECONDS, null);
Seems a bit overly complex? :D
```suggestion
        return bulkBanUsers(Arrays.asList(userIds), 0, TimeUnit.SECONDS, null);
```

2024-03-31 22:52 UTC, felldo commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * Bans the given user from the server.
Change this and the Javadoc from the other newly added methods
```suggestion
     * Bans the given users from the server.
```

2024-04-02 18:15 UTC, wasdennnoch commented on javacord-core/src/main/java/org/javacord/core/entity/server/BulkBanResponseImpl.java
> +    private final Set<Long> bannedUserIds = new LinkedHashSet<>();
I used it to preserve the order the API returns the IDs in. It was more of a potential nice-to-have and probably doesn't really matter, the API afaik just returns them in the same order you sent them in. But to be honest I also don't really see the use case for order preservation, so I've changed it to a normal HashSet for a tiny bit of performance gain.

2024-04-02 18:59 UTC, merged