Remove Client login support
Javacord/Javacord pull request #576
Opened 2020-06-12 18:39 UTC by Saladoc

Fixes #540 

Currently not tested in-depth, but up for review.

2020-06-12 21:03 UTC, Bastian commented
Do we want to deprecate it first or just remove it as it is pretty much broken anyway?

Without client accounts, we can most likely also remove group channels. Or is there any way for bots to interact with them?

2020-06-12 22:42 UTC, Saladoc commented
I could make a deprecation PR too and we could hold this off until 3.1.0, but since it's not a concious design decision but rather a reality brought to us by discord, I'd not bother with deprecation.

2020-10-24 13:24 UTC, Saladoc commented
@Bastian How do you want to proceed here?

2020-12-27 12:49 UTC, Bastian approved these changes
I agree that a deprecation is not neccessary.

2021-08-28 16:40 UTC, Saladoc commented
Since #847 will also do a cleanup with regards to deprecated methods, I added this PR to the same milestone. Since the functionality behind the user account methods has long been discontinued, prior deprecation is not necessary.

2022-01-26 20:48 UTC, KILLEliteMaste requested changes
When searching for `group` in the project there are still some things left.
- CertainMessageEvent#isGroupMessage
- In MessageAuthor and VoiceChannel , TextChannel, Channel some Javadocs contain `(private channel or group channel)` which can be removed. In Addition VoiceChannel also check for group channels sometimes
- DiscordApi some Javadocs contain `Can be <code>null</code> to search for group channels without name` which can be removed

2022-01-26 20:48 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
> +
Seems redundant for me to have it as a variable. Should be directly concated in the `getPrefixedToken` method

2022-01-26 20:48 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/ReadyHandler.java
>                          logger.warn("Unknown or unexpected channel type. Your Javacord version might be out of date!");
Can't select everything (up to the if statement) but this now seems to be code that will never be reached. Therefore this should be removed

2022-01-26 20:48 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelDeleteHandler.java
> +                logger.info("Received an update for a group channel. This should be impossible.");
```suggestion
                logger.info("Received CHANNEL_DELETE packet for a group channel. This should be impossible.");
```

2022-01-26 20:48 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
> +                logger.info("Received an update for a group channel. This should be impossible.");
```suggestion
                logger.info("Received CHANNEL_UPDATE packet for a group channel. This should be impossible.");
```

2022-01-26 20:48 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/guild/VoiceStateUpdateHandler.java
> +                    logger.info("Received an update for a group channel. This should be impossible.");
```suggestion
                    logger.info("Received a VOICE_STATE_UPDATE packet for a group channel. This should be impossible.");
```

2022-01-26 21:28 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/util/handler/ReadyHandler.java
>                          logger.warn("Unknown or unexpected channel type. Your Javacord version might be out of date!");
Same goes for the ChannelCreate/Delete/Update Handlers, but we still keep the informative log messages. Only dead code here is the GROUP_CHANNEL case as bots still have private message capabilities.

2022-01-26 21:29 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
> +
I'm in favor of keeping magic values in constants and not directly in the code. I see no reason to inline this.

2022-01-26 21:34 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/ReadyHandler.java
>                          logger.warn("Unknown or unexpected channel type. Your Javacord version might be out of date!");
According to the mentioned issue above the code the `private_channels` array is always empty for bots. And it has also been completely removed from the docs on the READY event so it makes no sense to keep it

2022-01-31 22:39 UTC, KILLEliteMaste requested changes
Just a few minor things :)

2022-01-31 22:39 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
> +                logger.info("Received CHANNEL_UPDATE packet  for a group channel. This should be impossible.");
```suggestion
                logger.info("Received CHANNEL_UPDATE packet for a group channel. This should be impossible.");
```

2022-01-31 22:39 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/DiscordApi.java
>          return Collections.unmodifiableCollection(channels);
Here and in the methods below it is not necessary to add the channels to a collection before we return an unmodifiable collection. So here `Collections.unmodifiableCollection(getServerChannelsByName(name));` should be sufficient.

2022-01-31 22:39 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/channel/Channel.java
> +     * In private channels this always returns <code>true</code> if the user is  part of the chat.
```suggestion
     * In private channels this always returns <code>true</code> if the user is part of the chat.
```

2022-01-31 22:39 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageAuthor.java
> +     * In private channels this always returns {@code true}  if the user is part of the chat.
```suggestion
     * In private channels this always returns {@code true} if the user is part of the chat.
```

2022-02-01 20:02 UTC, KILLEliteMaste approved these changes
LGTM!
Please rebase on the latest version and feel free to merge it right away :)

2022-02-01 21:19 UTC, merged