Add user public flags
Javacord/Javacord pull request #637
Opened 2020-10-01 17:30 UTC by Mysterypotatoguy

Adds the public user flags (aka badges) property to the User object

2020-10-04 12:16 UTC, Bastian requested changes

2020-10-04 12:16 UTC, Bastian commented on javacord-api/src/main/java/org/javacord/api/entity/user/UserFlag.java
> +    String description;
```suggestion
    private final int flag;
    private final String description;
```

2020-10-04 12:16 UTC, Bastian commented on javacord-api/src/main/java/org/javacord/api/entity/user/UserFlag.java
> +    HOUSE_BRAVERY(64, "House Bravery"),
I think it would be better to write it like in the Discord docs instead of using decimal notation:
```suggestion
    DISCORD_EMPLOYEE(1 << 0, "Discord Employee"),
    DISCORD_PARTNER(1 << 1, "Discord Partner"),
    HYPESQUAD_EVENTS(1 << 2, "HypeSquad Events"),
    BUG_HUNTER_LEVEL_1(1 << 3, "Bug Hunter Level 1"),
    HOUSE_BRAVERY(1 << 5, "House Bravery"),
```
and so on

2020-10-25 18:45 UTC, Bastian approved these changes

2020-10-25 18:52 UTC, merged

2020-12-22 14:50 UTC, Zeitheron commented on javacord-api/src/main/java/org/javacord/api/entity/user/UserFlag.java
> +    HOUSE_BALANCE(1 << 8, "House Bravery"),
Duplicate `House Bravery` ? I think it's supposed to be `House Balance`