Moved and added missing canXY() methods from VoiceChannel to ServerVoiceChannel
Javacord/Javacord pull request #638
Opened 2020-10-01 17:50 UTC by KILLEliteMaste

Already existing canXY() methods now check only the required permission.
Removed canConnectToVoiceChannel and canMuteUsersInVoiceChannel from MessageAuthor because there was no use.

Solves #574

2020-10-04 12:48 UTC, Bastian requested changes
Thank you! 

Just some small parts that need improvements.

2020-10-04 12:48 UTC, Bastian commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageAuthor.java
> -    default boolean canConnectToVoiceChannel() {
Please deprecate the methods instead of just removing them. That way, we don't introduce a breaking change.

2020-10-04 12:48 UTC, Bastian commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerVoiceChannel.java
> +                .hasAnyPermission(user, PermissionType.ADMINISTRATOR, PermissionType.PRIORITY_SPEAKER))
This does not take into account if the user is the server's owner. (also at other places)

2020-10-04 12:48 UTC, Bastian commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerVoiceChannel.java
> +        return asServerVoiceChannel().map(serverVoiceChannel -> serverVoiceChannel
Unnecessary `asServerVoiceChannel()` (also at other places)

2020-10-04 13:05 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerVoiceChannel.java
> +                .hasAnyPermission(user, PermissionType.ADMINISTRATOR, PermissionType.PRIORITY_SPEAKER))
It does because the server owner automatically has all permissions and so the permission check will return true

2022-07-19 21:33 UTC, Saladoc approved these changes

2022-07-20 18:29 UTC, merged