Use member object as SSOT for role membership
Javacord/Javacord pull request #662
Opened 2020-11-15 19:50 UTC by Bastian

Fixes https://github.com/Javacord/Javacord/issues/660

2020-11-18 16:48 UTC, Vampire requested changes

2020-11-18 16:48 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/entity/permission/RoleImpl.java
> +                .filter(member -> member.getServer().getId() == server.getId())
If you edit anyway, I'd like to suggest using the more object oriented `member.getServer().equals(server)`.

2020-11-18 16:48 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +                .filter(member -> member.getServer().getId() == getId())
`member.getServer().equals(this)` like above

2020-11-18 16:48 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +                                    list.add(getEveryoneRole());
I don't think it is correct that a user has the everyone role if he is not a member of the server. I think it should instead be `.orElseGet(Collections::emptyList)`.

2020-11-28 16:45 UTC, Bastian commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +                                    list.add(getEveryoneRole());
I'm unsure about whether it should contain the role or not, but considering that it has always been like this in Javacord, I won't change it (now). This would be a breaking change.

2020-11-29 01:27 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +                                    list.add(getEveryoneRole());
That's not correct or at least it wasn't before the cache change.
`org.javacord.api.entity.server.Server#getRoles(org.javacord.api.entity.user.User)` was
```java
return Collections.unmodifiableList(
        getRoles().stream()
                .filter(role -> role.hasUser(user))
                .collect(Collectors.toList()));
```
and `org.javacord.core.entity.permission.RoleImpl#hasUser` started with
```java
if (isEveryoneRole()) {
    return getServer().isMember(user);
}
```
So you correctly only got the everyone role if the user was a member of that server.

2020-11-29 16:30 UTC, Vampire requested changes
lgtm except for the bug with the everyone role that was introduced with the cache/intent-changes.
The old behavior that Javacord always had makes much more sense imho, because if a user is not a member of a server it does not make sense if he has any role, but he should have no role on that server.

2020-12-05 12:25 UTC, Bastian commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +                                    list.add(getEveryoneRole());
Seems like my memory was wrong then :|

2020-12-05 23:12 UTC, Vampire approved these changes
lgtm

2020-12-06 10:31 UTC, Bastian commented
Thx for the review :)

2020-12-06 10:31 UTC, merged