compensate missing CHANNEL_CREATE event for text channels
Javacord/Javacord pull request #708
Opened 2021-02-03 15:57 UTC by Joshix-1

fixes #707

2021-02-03 17:42 UTC, Joshix-1 commented
With the second commit the text channel will not be created with the bot as receiver.

2021-02-03 17:43 UTC, Joshix-1 commented
> as reaction to some channel command
That will only happen on shard 0. You won't receive commands on other shards.

2021-02-03 18:51 UTC, Vampire commented
> That will only happen on shard 0. You won't receive commands on other shards.

Why not?
I'm talking about commands in server channels

2021-02-03 18:54 UTC, Vampire commented
> With the second commit the text channel will not be created with the bot as receiver.

But now you miss the message create event for the bots message.
Maybe the channel needs to be optional, or in this edge case you need to request the channel by id from Discord.

2021-02-03 19:02 UTC, Joshix-1 commented
I don't like any option. The channel being optional would be a big change. And requesting the id would create an extra unnecessary request.

2021-02-03 21:20 UTC, Vampire commented
It's imho not unnecessary if you otherwise loose the event. And it is just one request and only in case the first incoming message on a private channel is by the bot.

2021-02-04 13:36 UTC, Vampire requested changes

2021-02-04 13:36 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
> +            UserImpl recipient = new UserImpl(api, packet.get("author"), (MemberImpl) null, null);
Definitely a nit, but I'd like to suggest calling this `author`. :-)

2021-02-04 13:36 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
> +                        .thenAccept(channel -> handle(channel, packet));
I think in this case we should actually wait for the result of the request synchronously, or the order of events is not correct anymore.
As this is an edge case anyway, I think it should be ok to wait here without introducing a performance problem.

2021-02-04 13:36 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
> +                        .thenAccept(channel -> handle(channel, packet));
Also in this case currently no `PrivateChannelCreateEvent` is dispatched.
I think it should uniformly dispatch the event in both cases.
Otherwise you can for example not easily attach a listener to all newly create channels as this one would be missing.

2021-02-04 14:19 UTC, Vampire approved these changes
lgtm

thanks :-)

2021-02-05 16:45 UTC, coaxial1 commented
I don't think requesting a channel synchronously is a good idea because I think the case you consider as "edge case" is the normal case. Almost all DM interactions with bots are initiated by bots themselves. Let it be welcome messages, DM replies to commands, DMs sent as notification, DMs as a response to a reaction, etc. There are barely use cases for the user to open a DM channel to a bot on their own behalf, except for special use cases like single-server Ticketing systems or similar things; this is mostly due to the fact that without any open DM session to a user, as a bot, you wouldn't know to which server a request or DM belongs. Therfore, DM interactions / sessions are often created based on server interactions. At least I have only seen one bot yet that allowed DM interactions without a preceding server interaction, and I've seen a lot.

If this is blocking the complete packet handler thread (and thus all event processing on that shard) for 100 milliseconds to wait for the channel request response, and you only send 5 DMs per second or need to dispatch a large number of DMs at once, you'd block shard 0 for a relatively long time from processing anything else - and you reach that number very easily on large bots as you're sending most DMs from other shards. Additionally, you'd consume twice as many requests from the already very low global ratelimits than actually needed.

Instead, we should think about not dispatching a channel create event for DMs at all. That way, we can dispatch the message create event asynchronously, and prevent blocking the handler thread. We'd need to make the channel optional, but can add a new method like "getChannelId()" to the Message interface.

We're wrapping Discords API, and they stopped dispatching channel create events for DM, and so should we; they have done it in v6 to support legacy clients only (that worked with the discontinued bot DM list). It would be a breaking change but we have a very breaking change release ahead anyways as we're switching to v8.

2021-02-05 18:00 UTC, Vampire commented
Switching to v8 per-se is not a breaking change, but an implementation detail unless this causes changes in the Javacord API.
Making the channel `Optional` was my other suggestion how to deal with it, but Joshix didn't like it.

Not dispatching the channel create event would be a breaking change behaviour-wise, but it could certainly be done.
But that then also needs to be clearly communicated in the release notes and the channel made `Optional`, maybe adding a `requestChannel` method like we have it for other places.

I'd second that move actually, I just tried to get the code here correct behaviour-wise as Joshix didn't like the `Optional` idea.

I guess @Bastian should share a thought about it.
But probably the `Optional` road and no channel create event is indeed the way to go.

2021-03-18 16:12 UTC, Vampire commented
@Joshix-1 what do you think about the last two comments and changing to the `Optional` way?

2021-03-18 20:15 UTC, Joshix-1 commented
I agree.
How would you make Message#isPrivateMessage() work then? I don't think it is a good idea to just assume that it is private if the channel is missing because of webhooks. I think there can be some changes now that the channel will be Optional.
https://github.com/Javacord/Javacord/blob/19bf2f31110ebd098b3a4ab315a533757a4be772/javacord-api/src/main/java/org/javacord/api/entity/message/Message.java#L893-L895

2021-03-19 14:10 UTC, coaxial1 commented
I guess we would need to work with the `guild_id` sent by Discord in the message payload to determine if it's private or not. iirc, group chats are only available for user bots and we should remove that feature entirely anyways ( #576 )

2021-03-19 19:23 UTC, Joshix-1 commented
I think making the channel Optional is the way to go. (I spend way too much time making the channel optional.)

It's currently in a "it build without errors" state and needs testing.

2021-03-21 00:16 UTC, coaxial1 commented
I understand that, and it looks good. Nevertheless, that alone shouldn't be the most important factor when choosing a solution. :)

I just think this: 
- Making the channel optional everywhere is a breaking change that will impact more code than an optional recipient. You probably call ``Message#getChannel`` more frequently than ``PrivateChannel#getRecipient`` (tbh, I wrote 70k lines of code with Javacord and didn't even know it existed 😬 ). For a lot of work done with Javacord it'd probably just be a minimal change, if any at all
- If we'd just make the recipient optional, we'd have a more justifiable, straight-forward solution for the missing channel create event on the gateway.
- It's hard to tell a user why a channel can be optional / why a message doesn't have a channel in some cases, which doesn't make much sense from a users perspective - it might cause confusion when a channel is clearly there in all cases (on guilds), but still comes as an Optional, although the only case where it's empty may be in DMs
- In contrary, it's easy to explain why a recipient may be null (e.g. by just showing what we got from the gateway, as we simply don't have it).
- With an optional recipient, we could even still deliver a channel create event with an empty recipient field, which is not the case in the current solution. In the rare case that someone is using it, we could still provide it, and provide a method to fetch the recipient if required.
- With an optional recipient, we would already have the message we received in the cache, while with the current solution, the message would not be cached.

I apologize that I come up with this "idea" after you worked on the "optional channel" solution - just trying to find the most practical one for everyone.

What do you guys think? :)

2021-03-21 00:34 UTC, Joshix-1 commented
Making the channel optional has the advantage that we can always return the message when sending messages with webhooks. Otherwise it wouldn't be possible to get the object when the bot isn't on the server with the message. 
This is a rare problem, but it could get more important with slash commands.

But you are right; making the recipient optional, would be the better way for this pr.

2021-03-21 00:36 UTC, coaxial1 commented
We should also check if we can resolve #524 with this PR as it's a similar problem... 🤔

2021-03-21 00:43 UTC, coaxial1 commented
> This is a rare problem, but it could get more important with slash commands.

I don't see an issue there (yet). I do not see a reason to start an interaction from anywhere else than a server the bot is in; and I don't think Javacord should even try to support "interactions only", that's not what it's for, imho. We should see slash commands as an guild based add-on, so we probably always have the server text channel for the interaction cached. Do I oversee something obvious? :)

2021-03-21 01:05 UTC, Joshix-1 commented
> We should also check if we can resolve #524 with this PR as it's a similar ekzem... thinking 
Would #524 get fixed with the recipient being optional?

> so we probably always have the server text channel for the interaction cached.
Maybe, I don't know. Do the interaction create events respect shards?

2021-03-21 02:10 UTC, coaxial1 commented
> Would #524 get fixed with the recipient being optional?
Well, no, but since we're trying to compensate the missing channel create event, we could fix that reaction issue as well. It's caused by the same thing: There's no channel create event preceding the reaction add event.

> Maybe, I don't know. Do the interaction create events respect shards?
Yes, if you opt to receive them through the gateway, they come in on the shard of the server the interaction has been initiated on. Only the other possibility (receiving interactions through a HTTP call to your own server / VM) is shard agnostic, but is intended to be used by interaction only applications that do not have a bot account and active gateway sessions

2021-03-22 20:29 UTC, Joshix-1 commented
I made the recipient optional now. (not tested yet, just a draft)
This pr now tries to fix the problems with reactions (#524) aswell.

The version with the optional channel is at: https://github.com/Joshix-1/Javacord/tree/optional_channel , but I think it is a better idea to don't make the channel optional.

2021-03-22 21:07 UTC, coaxial1 requested changes
Wow, this looks good and very clean.

I added a few very minor comments and suggestions, if you don't mind. Please feel free to accept/reject them as you see fit.

I'll do a few manual tests tomorrow.

2021-03-22 21:07 UTC, coaxial1 commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionRemoveAllHandler.java
> +            if (!packet.hasNonNull("guild_id")) { // if channel null and private channel:
I'd suggest to return early if `packet.hasNonNull("guild_id")` is `true`, so we could get rid of `else`

2021-03-22 21:07 UTC, coaxial1 commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionRemoveHandler.java
> +        if (!packet.hasNonNull("guild_id")) { // if private channel:
I'd swap the `if` and `else` block here, and remove the `!` from the condition

2021-03-25 19:19 UTC, Joshix-1 commented
I updated it and it seems to work.

2021-03-26 21:34 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionAddHandler.java
> +        }
I assume this should never happen since the event will get lost. Please add a logger message

2021-03-26 21:34 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionRemoveAllHandler.java
> +            }
Same here. Add a logger message since all server channels should be cached

2021-03-26 21:34 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionRemoveHandler.java
> +        }
Same here. Add a logger message

2021-03-27 21:09 UTC, Joshix-1 commented
I added logging messages and removed the blank lines.

2021-03-27 23:52 UTC, lost-illusi0n commented
Just tried this fix (on commit 80285c8) and it seemed to work... until it didn't. 
Not sure what exactly caused it but after a few minutes (after responding and handling messages fine, both in DMs and servers), it had stopped handling messages from servers correctly. I could still DM the bot, and the bot could DM me, but it was not able to do so with messages from servers. Here's the assertion error I was getting spammed with after a few minutes.
```
23:26:23.316 [Javacord - Handlers Processor] WARN  org.javacord.core.util.gateway.PacketHandler - Couldn't handle packet of type MESSAGE_CREATE. Please contact the developer! (packet: {"type":19,"tts":false,"timestamp":"2021-03-27T23:26:23.258000+00:00","referenced_message":{"type":0,"tts":false,"timestamp":"2021-03-27T23:25:45.658000+00:00","pinned":false,"mentions":[],"mention_roles":[],"mention_everyone":false,"id":"825510941301932044","flags":0,"embeds":[],"edited_timestamp":null,"content":"alright boys and girls whos gonna sign up for the neuralink","channel_id":"110373943822540800","author":{"username":"GoatGeek","public_flags":0,"id":"96979199411113984","discriminator":"0001","avatar":"a_4c5080f0287d6f8340b4206a056ac479"},"attachments":[]},"pinned":false,"nonce":"825511098684801024","message_reference":{"message_id":"825510941301932044","guild_id":"110373943822540800","channel_id":"110373943822540800"},"mentions":[],"mention_roles":[],"mention_everyone":false,"member":{"roles":["110375768374136832","113379036524212224","231130892926582786","234237413675892736","407326634819977217","499303630567112704","520136799134416896","803324278987685888","344727499864932354","818750459350482954","530106314752524299","755499785020113036","585535347753222157","588728844345671696","540025225597812762","598574793712992286","801105321456173086","801550928108191777","746739847145717800","753295484973482055"],"premium_since":"2020-08-16T18:01:15.677000+00:00","pending":false,"nick":"amy ✨","mute":false,"joined_at":"2017-01-24T01:45:38.514000+00:00","is_pending":false,"hoisted_role":"234237413675892736","deaf":false},"id":"825511099008024598","flags":0,"embeds":[],"edited_timestamp":null,"content":"Sorry I don't want the government stealing my ABSOLUTELY PROPRIETARY thoughts","channel_id":"110373943822540800","author":{"username":"amy","public_flags":131584,"id":"128316294742147072","discriminator":"0001","avatar":"a_1d97b4b1fa012fb4438b96256c4d10da"},"attachments":[],"guild_id":"110373943822540800"})
java.lang.AssertionError: null
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] "
	at org.javacord.core.entity.message.MessageAuthorImpl.<init>(MessageAuthorImpl.java:55) ~[javacord-core-3.1.3-SNAPSHOT.jar:?] "
	at org.javacord.core.entity.message.MessageImpl.<init>(MessageImpl.java:168) ~[javacord-core-3.1.3-SNAPSHOT.jar:?] "
	at org.javacord.core.DiscordApiImpl.lambda$getOrCreateMessage$29(DiscordApiImpl.java:1092) ~[javacord-core-3.1.3-SNAPSHOT.jar:?] "
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?] "
	at org.javacord.core.DiscordApiImpl.getOrCreateMessage(DiscordApiImpl.java:1092) ~[javacord-core-3.1.3-SNAPSHOT.jar:?] "
	at org.javacord.core.util.handler.message.MessageCreateHandler.handle(MessageCreateHandler.java:56) ~[javacord-core-3.1.3-SNAPSHOT.jar:?] "
	at org.javacord.core.util.handler.message.MessageCreateHandler.lambda$handle$0(MessageCreateHandler.java:51) ~[javacord-core-3.1.3-SNAPSHOT.jar:?] "
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] "
	at org.javacord.core.util.handler.message.MessageCreateHandler.handle(MessageCreateHandler.java:50) ~[javacord-core-3.1.3-SNAPSHOT.jar:?] "
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51) ~[javacord-core-3.1.3-SNAPSHOT.jar:?] "
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?] "
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?] "
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?] "
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?] "
	at java.lang.Thread.run(Thread.java:831) [?:?] "
```
Reverting this PR seemed to just go back to its original state.

2021-03-28 00:09 UTC, Joshix-1 commented
I don't see how this PR should cause this. Does the development branch work for you? It seems weird that this PR should cause this, as I didn't change anything with the MessageAuthor.

2021-03-28 00:14 UTC, lost-illusi0n commented
Yes, I'm using the development branch along with a 2 line change within AudioSocket, and then I pulled this PR. It seemed to be fine on my dev bot, and when I then pushed the update to my production version, it had started spamming the above exception after a few minutes. Maybe it could be some freak one-time Discord thing?

2021-03-28 17:08 UTC, lost-illusi0n commented
Seemed to resolve it self *hopefully*, and I'm leaning on that this was some freak discord bug in combination with bad timing. It worked locally overnight, and is now running in production 👍

2021-04-05 08:50 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionRemoveHandler.java
> +        }
This causes the error @lost-illusi0n commented. Remove the `!` and it should work again

2021-04-05 10:43 UTC, Joshix-1 commented on javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionRemoveHandler.java
> +        }
I removed the `!`.

2021-04-05 11:06 UTC, KILLEliteMaste commented
Can you please squash the PR into a single commit?

2021-04-06 15:09 UTC, KILLEliteMaste commented
lgtm! Can you please rebase to the latest version?

2021-04-06 15:44 UTC, merged