Radio channel
Javacord/Javacord pull request #726
Opened 2021-03-31 23:39 UTC by Joshix-1

should fix #725 

maybe fixes #724, but I don't know if topics are the only thing special about the server stage voice channels.

This is a draft as I still have to look over it tomorrow. I just want to get feedback.

2021-04-01 14:35 UTC, Bastian commented on javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelCreateHandler.java
> +        // https://github.com/hammerandchisel/discord-api-docs/issues/184Messa
```suggestion
        // https://github.com/hammerandchisel/discord-api-docs/issues/184

2021-04-01 14:35 UTC, Bastian commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +                        // TODO Handle them different from voice channel:
Aren't you handling if differently? Or is this a remnant?

2021-04-01 14:58 UTC, Bastian requested changes

2021-04-01 14:58 UTC, Bastian commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerStageVoiceChannel.java
> +
```suggestion

    @Override
    default ChannelType getType() {
        return ChannelType.SERVER_STAGE_VOICE_CHANNEL;
    }

```

2021-04-01 14:58 UTC, Bastian commented on javacord-core/src/main/java/org/javacord/core/entity/channel/ServerStageVoiceChannelImpl.java
> +
```suggestion
    @Override
    public String toString() {
        return String.format("ServerStageVoiceChannel (id: %s, name: %s)", getIdAsString(), getName());
    }

```

2021-04-01 21:12 UTC, Joshix-1 commented
I think as a quick fix for just fixing #725 this is enough.

2021-04-02 10:29 UTC, Bastian commented
Lgt :)

Thanks!

2021-04-02 10:29 UTC, merged