Fix global ratelimiter math and correct / update javadocs
Javacord/Javacord pull request #749
Opened 2021-04-29 15:19 UTC by coaxial1

I've fixed the bad math of the default global ratelimiter as discussed on Discord.

I've replaced the recommended formula to calculate the bucket duration, because to be honest, the old one was just wrong or I did not understand it correctly. I'm open for discussion, but the one I suggested will work (see examples in this table).
![grafik](https://user-images.githubusercontent.com/23171488/116575385-e0bc3880-a90e-11eb-893d-9b7f7e2e2822.png)

Additionally, I updated and corrected a few documentation lines around the global ratelimiter. For example, a documentation in the builder said that Javacord will not use a global ratelimiter if none is set by the users, which is wrong (we have default global ratelimiters).

2021-04-29 16:42 UTC, Vampire requested changes

2021-04-29 16:42 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/util/ratelimit/LocalRatelimiter.java
>   * <li>About {@code 1} request per {@code 20.5 ms}
The values do not match the new results

2021-04-29 16:42 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/util/ratelimit/LocalRatelimiter.java
> + * In general, it's recommended to set the ratelimit a bit lower than the actual maximum to make up for network jitter.
If that is recommended, why not incorporate it in the suggested formula for example by using `0.9 * realAmount`?

2021-04-29 17:28 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/util/ratelimit/LocalRatelimiter.java
> + * In general, it's recommended to set the ratelimit a bit lower than the actual maximum to make up for network jitter.
I think this would cause confusion. Imho, the given formula should yield exact results for the given inputs. If I say I want "exactly 50 requests per 1 second", the formula should exactly do that.
If a user wants to follow the advice, they can just lower `realAmount` to whatever the see fit. I'd generally say that someone who sets a custom ratelimiter should be advanced enough to understand and implement that advice.

There may even be use cases where that recommendation is exactly what you don't want since our `Ratelimiter` interface and this implementation are very "generic" and could be reused in more scenarios than just global ratelimiting.
We could either just remove it, or replace `In general` with `For global ratelimiting`.

What do you think?

2021-04-29 17:29 UTC, Bastian commented
> because to be honest, the old one was just wrong or I did not understand it correctly

The formula exists to prevent misalignment with Discord global ratelimit bucket. Here's a simple example:
![image](https://user-images.githubusercontent.com/5033001/116592559-6c8a9080-a920-11eb-8ab1-ae2e6a63ff60.png)

Setting the `LocalRatelimiter` to allow 25 req / 0,5 sec would make it possible to execute up to 150 requests in less than 1 sec (because the "first" ones could be at the "end" of the LocalRatelimiter bucket and then the "last" ones at the "start" of the LocalRatelimiter bucket).

2021-04-29 17:33 UTC, Vampire commented
Ah, so we need the old formula, but correctly implemented and maybe explained as comment why.

2021-04-29 17:34 UTC, coaxial1 commented
Got it, thanks for the explanation.

2021-04-29 17:40 UTC, coaxial1 commented
Should be good now.

2021-04-29 17:41 UTC, coaxial1 commented
We should add the explanation why we need this to a wiki article.
The linked page https://javacord.org/r/local-ratelimiter does currently resolve to 404.

2021-04-29 17:44 UTC, coaxial1 commented
I'd suggest to change the link to https://javacord.org/wiki/advanced-topics/ratelimits.html and create another PR to talk about global ratelimits on that wiki page. Opinions?

2021-04-29 21:32 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/util/ratelimit/LocalRatelimiter.java
>   * <li>About {@code 1} request per {@code 20.5 ms}
Actually the values are still not correct, as a `ceil` is done there should be no digits after the point

2021-04-29 21:35 UTC, Vampire requested changes

2021-04-29 21:35 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/util/ratelimit/LocalRatelimiter.java
> + *     ({@code amount = 25} and {@code bucketDuration = Duration.ofMillis((long) Math.ceil(25000D / 40D))}).
This should be `/ 25D`, shouldn't it?

2021-05-02 13:11 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/util/ratelimit/LocalRatelimiter.java
> + *     ({@code amount = 25} and {@code bucketDuration = Duration.ofMillis((long) Math.ceil(25000D / 40D))}).
Yup.

2021-05-02 18:01 UTC, Vampire approved these changes

2021-05-02 18:01 UTC, merged