Interaction response
Javacord/Javacord pull request #750
Opened 2021-05-13 13:45 UTC by KILLEliteMaste

This implements the ability to respond to interactions.
Also fixed a hard coded limit for webhook embeds in the message builder.

Internal PR implementations:
* [x] Responding to an interaction
* [ ]  Followup messages

Issue implementations:
* [ ] Respond to application commands

Usage example:
Coming soon

2021-05-17 16:42 UTC, KILLEliteMaste commented
I am not 100% satisfied with the location of some methods like #deleteInitialResponse located in the event. It could also be moved i.e. into the Interaction class `event.getInteraction().deleteInitialResponse()` but I am not sure and open for suggestions.

2021-05-19 00:05 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/entity/message/InteractionMessageBuilderDelegateImpl.java
> +    private Flag flag = null;
This should probably be an `EnumSet<Flag>`, though there currently are no other flags

2021-05-19 12:53 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/entity/message/InteractionMessageBuilderDelegateImpl.java
> +    public void setFlags(EnumSet<MessageFlag> messageFlags) {
You can also overload to `MessageFlag...`  for easier usage

2021-05-19 12:53 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/entity/message/InteractionMessageBuilderDelegateImpl.java
> +    public void setFlags(EnumSet<MessageFlag> messageFlags) {
Ah apologies, missed the one above

2021-05-26 19:13 UTC, coaxial1 requested changes
Added a minor suggestion (open for discussion), otherwise this LGTM. :)

2021-05-26 19:13 UTC, coaxial1 commented on javacord-core/src/main/java/org/javacord/core/entity/message/InteractionMessageBuilderDelegateImpl.java
> +        topBody.put("type", 4);
Should we maybe create an Enum for this, such as ``InteractionCallbackType``? We're using "4" here and "5" for the "response later" body as magic numbers right now. Today they added two more (6 and 7) for component callbacks, so it'd probably better to define and name these types somewhere.

2021-05-26 19:13 UTC, coaxial1 commented on javacord-core/src/main/java/org/javacord/core/event/command/InteractionCreateEventImpl.java
> +    private static final String RESPOND_LATER_BODY = "{\"type\": 5}";
See the conversation above.

2021-05-26 20:16 UTC, coaxial1 approved these changes

2021-05-26 20:18 UTC, merged