General component fixes
Javacord/Javacord pull request #786
Opened 2021-06-17 20:04 UTC by KILLEliteMaste

This PR changes some method names and i.e. Button.primary now builds the object right away instead of returning the builder.
Changed the ButtonBuilder and ActionRowBuilder to build the actual object which are then passed as the arguments for i.e. the messagebuilder.

2021-06-17 22:25 UTC, coaxial1 requested changes
Please see the comments below :)

2021-06-17 22:25 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandOption.java
>      static ApplicationCommandOptionBuilder with(ApplicationCommandOptionType type, String name, String description) {
Did you forget to change this one? It should also return the option itself instead of the builder I guess, and be renamed to "create" like the other methods.

2021-06-17 22:25 UTC, coaxial1 commented on javacord-core/src/main/java/org/javacord/core/entity/message/component/ActionRowImpl.java
> +                case ACTION_ROW:
I don't think you need to add this case since your iterating over components of type ``LowLevelComponent`` which ActionRow doesn't implement, so this case can't happen

2021-06-17 22:25 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
> +    static Button success(String customId) {
This method MUST return a builder instead of a button (please read the javadoc comment above it). If you immediately build, this will not yield a valid button as it does not have a label nor an emoji (empty buttons are not possible).

2021-06-17 22:25 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
> +    static Button secondary(String customId) {
This method MUST return a builder instead of a button (please read the javadoc comment above it). If you immediately build, this will not yield a valid button as it does not have a label nor an emoji (empty buttons are not possible).

2021-06-17 22:25 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
> +    static Button primary(String customId) {
This method MUST return a builder instead of a button (please read the javadoc comment above it). If you immediately build, this will not yield a valid button as it does not have a label nor an emoji (empty buttons are not possible).

2021-06-17 22:25 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
> +    static Button danger(String customId) {
This method MUST return a builder instead of a button (please read the javadoc comment above it). If you immediately build, this will not yield a valid button as it does not have a label nor an emoji (empty buttons are not possible).

2021-06-17 22:25 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
> +    static Button link(String url) {
This method MUST return a builder instead of a button (please read the javadoc comment above it). If you immediately build, this will not yield a valid button as it does not have a label nor an emoji (empty buttons are not possible).

2021-06-17 22:25 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
>      static ButtonBuilder with(String customId, ButtonStyle style, String label) {
Why didn't you change the ``with(...)`` methods to return a full button as well? A button with a style, customid and label would be perfectly valid.
Same for the methods below.

2021-06-18 08:41 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/component/ActionRowImpl.java
> +                case ACTION_ROW:
This is copied from the ActionRowBuilder from a previous PR so I didn't had a look at the code anymore and just adjusted it where necessary.

2021-06-18 08:54 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
>      static ButtonBuilder with(String customId, ButtonStyle style, String label) {
Doing this clashes with the button methods returning a builder. `static ButtonBuilder dangerWith(String customId)`. I would rather vote for removing these methods as we already have methods to create any kind of valid button. What do you think?

2021-06-18 11:01 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
>      static ButtonBuilder with(String customId, ButtonStyle style, String label) {
The ``with()`` methods have the advantage that they accept a style as parameter, so it can be set programmatically if a lib user needs to accept a dynamic style instruction from elsewhere. If we remove them, they'd need to use ``new ButtonBuilder()`` or a switch statement (to choose the correct danger, primary, ... shorthand) which can both be avoided by simply letting these methods survive. :)

2021-06-18 11:06 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
>      static ButtonBuilder with(String customId, ButtonStyle style, String label) {
I mean removing the methods that only have the custom ID like `danger(String customId)` as they are have to return the builder and need an additional parameter. And we actually have for any case already a working method which returns a valid button if I've seen correctly.

2021-06-18 11:12 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
>      static ButtonBuilder with(String customId, ButtonStyle style, String label) {
Yeah, you're absolutely right. They don't make munch sense in this context anymore. I'd as well vote for removing shorthands that produce an invalid button in all cases. Sorry for the misunderstanding

2021-06-18 12:43 UTC, coaxial1 approved these changes

2021-06-18 12:54 UTC, merged