Added SelectMenus
Javacord/Javacord pull request #800
Opened 2021-07-02 22:45 UTC by Morazzer

Created a implementation for the [select menus](https://discord.com/developers/docs/interactions/message-components#select-menus).

Issue for that #796

2021-07-03 15:17 UTC, KILLEliteMaste requested changes
Thank you for your fist and also quiet big contribution! :)

2021-07-03 15:17 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SelectMenuInteractionImpl.java
> +        ObjectNode dataObject = (ObjectNode) jsonData.get("data");
Same as above

2021-07-04 14:41 UTC, Morazzer commented
![image](https://user-images.githubusercontent.com/59416038/124389261-a42e0400-dce6-11eb-9078-4c8b6c9ad0f0.png)
Is this a problem with my code?

2021-07-04 16:11 UTC, Bastian commented
The GitHub Action did not fail, so probably not.
I triggered a rebuild, let's see.

2021-07-04 17:40 UTC, KILLEliteMaste requested changes
Just a few more things :)

2021-07-04 17:40 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/listener/interaction/SelectMenuChooseListener.java
> +
Remove line

2021-07-04 17:40 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/component/internal/SelectMenuOptionBuilderDelegateImpl.java
> +    private Emoji emoji;
Assign `null` to all variables except for isDefault

2021-07-04 17:40 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/component/SelectMenuImpl.java
> +        object.put("placeholder", this.placeholder);
Add a `placeholder != null` check

2021-07-04 17:40 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/component/SelectMenuOptionImpl.java
> +        object.put("description", description);
Add a `description != null` check

2021-07-04 17:40 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/component/SelectMenuOptionImpl.java
> +        if (!(emoji == null)) {
`emoji != null` is more readable :)

2021-07-04 17:40 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/component/internal/SelectMenuOptionBuilderDelegateImpl.java
> +
Remove line

2021-07-04 17:40 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/SelectMenu.java
> +    int getMaxValues();
Imo renaming them to `getMinimumValues` and `getMaximumValues` sounds better. Please apply the renaming in all classes

2021-07-04 18:22 UTC, Morazzer commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/SelectMenu.java
> +    int getMaxValues();
Also the local variables?

2021-07-04 18:28 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/component/SelectMenu.java
> +    int getMaxValues();
Yes

2021-07-04 19:00 UTC, KILLEliteMaste approved these changes

2021-07-04 19:00 UTC, KILLEliteMaste commented
Can you please squash the PR into a single commit?

2021-07-04 19:10 UTC, Morazzer commented
I hope it's right how i done it

2021-07-04 19:21 UTC, KILLEliteMaste commented
Yeah, it's fine. Thank you!

2021-07-04 19:21 UTC, merged