Added ability to edit message with message builder
Javacord/Javacord pull request #810
Opened 2021-07-09 01:10 UTC by Morazzer

Added ability to edit messages with the message builder.

Issue: #575

2021-07-22 14:10 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
> +    }
Is there an actual use case for the booleans I didn't think of? Why can't you just remove the values from from the MessageBuilder or create a new?

2021-08-02 15:04 UTC, coaxial1 commented
Since it seems like the original author isn't coming back to this (and I need this myself actually), I've changed this to remove the boolean flags and check for the content field to be filled at all.
@KILLEliteMaste Please lmk fi this makes sense for you now. :)

2021-08-02 16:11 UTC, KILLEliteMaste requested changes

2021-08-02 16:11 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +        prepareComponents(body);
I think we can reuse nearly everything from #send(TextChannel) for this. There are also a lot of things missing like the allowed mentions, flags...  See https://discord.com/developers/docs/resources/channel#edit-message-jsonform-params

If for some reason you do not reuse the code from the #send method you should also remove the check to update the message content as it is not possible atm to remove it.

2021-08-02 16:35 UTC, coaxial1 commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +        prepareComponents(body);
For flags: We currently do not support flags at all, do we? I mean any of those: https://discord.com/developers/docs/resources/channel#message-object-message-flags

So all that's missing is allowed mentions and files/attachments.

> you should also remove the check to update the message content 

I don't understand this one. I've intentionally added the check. All requests trying to patch in an empty content will either fail (completely empty message won't work) or produce unexpected results (e.g. it'd remove content from a message that also contains an embed although this is not wanted), so we need to exclude it from the request if the content is empty / unset, right? This is important for requests where we e.g. only want to patch in some components:

```java
Message m = ...;
new MessageBuilder().addComponents(...).edit(m);
```
We do not use ``Message#toMessageBuilder()`` since we don't want to change anything else than components in this case, so we create a new one (like you suggested in your complaint about the boolean flags)

2021-08-02 17:26 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +        prepareComponents(body);
>  All requests trying to patch in an empty content will either fail (completely empty message won't work) or produce unexpected results (e.g. it'd remove content from a message that also contains an embed although this is not wanted), so we need to exclude it from the request if the content is empty / unset, right?

But how else should you be able to edit a message which contains a `content` and `embed` to only having an `embed`?

> For flags: We currently do not support flags at all, do we? I mean any of those:

We do: `EPHEMERAL` for example as this was the only Message flag available back this time we implemented it.

And taking your example
```java
Message m = ...;
new MessageBuilder().addComponents(...).edit(m);
```
You example assumes that we patch in the new stuff. I was thinking more about we replace the message with the the new MessageBuilder

2021-08-02 18:01 UTC, coaxial1 commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +        prepareComponents(body);
> But how else should you be able to edit a message which contains a content and embed to only having an embed?

Yeah, that is a problem. But we should really avoid to send the entire message in the patch request, even tho we only change the components (for example) ... So how would we do it? We could compare everything against the Message object passed in as parameter to ``edit()`` and only send differences ... in theory ...

>  the only Message flag available back this time we implemented it.

I think you're confusing https://discord.com/developers/docs/interactions/slash-commands#interaction-response-object-interaction-application-command-callback-data-flags with the link I sent above; those are different types of flags! And the ones I linked above existed for a long time already when we added support for ephemeral interaction responses.

>  I was thinking more about we replace the message with the the new MessageBuilder

Yeah we could do that as well, but it would need to inlcude the difference checking stuff I mentioned above.

2021-08-02 18:12 UTC, coaxial1 commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +        prepareComponents(body);
Alternatively to the difference chec which would be complex to do, we could track wether or not any of the methods affect ``content`` have been called on the MessageBuilder, and send an empty content field if they have been intentionally set to be empty.

Second alternative would be to have a new interface ``MessageUpdater``, similar to ``ServerUpdater``, to make the intention more clear. I agree that having a MessageBuilder with ``edit`` would imply that all fields of the builder are applied, even if empty (and thus replace the message).

2021-08-02 18:26 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +        prepareComponents(body);
> I think you're confusing...

Prorbably yeah. But since these are 2 different Enums our current implementation for `setFlags` in `InteractionMessageBuilderBase` and maybe some other places is wrong as this assumes MessageFlag which is then something different than the `Interaction Application Command Callback Data Flags`. 

I think introducing a message updater is a good idea. This clearly differenciates the MessageBuilder which sends a message to updating a message. And this also allows us to have different updating methods like `updateSetFields` and `replaceMessage` without cluttering everything in the MessageBuilder and it makes it clear how you are updating the message.

2021-08-02 18:34 UTC, coaxial1 commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +        prepareComponents(body);
> our current implementation for setFlags ... is wrong

I don't think so. EPHEMERAL is indeed to only flag that can be set when sending interaction responses. Offering anything else would currently be misleading.
We could have another enum to represent the flags of an already sent message, maybe, for example to know wether or not a message has been crossposted or not, but I wouldn't consider that high priority. Might deserve an issue, though. Also, except for the SUPPRESS_EMBEDS flags nothing is updateable, so we could just have a method like ``Message#suppressEmbeds()`` to set the flag to true. That would be the same thing as the little "X" that appear on the top right of embeds in the UI.

> I think introducing a message updater is a good idea.

I'll create a new pull request for that approach. I also like it better than having an ``.edit()`` on the builder. I don't know wether or not we should make a difference between "UpdateSetFields" and "ReplaceMessage", though. The first one is how an updater usually works

2021-08-02 18:44 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +        prepareComponents(body);
> I don't think so. EPHEMERAL is indeed to only flag that can be set when sending interaction responses. Offering anything else would currently be misleading.

Because exactly of this the current implementation is not correct as MessageFlag also contains i.e. `SUPPRESS_EMBEDS`. So we have to create a 2nd enum which contains only the valid flags repsonding to an interaction.

> The first one is how an updater usually works

Yes, but I think there are actually more use cases for replacing a message than just adding e.g. a component to a message. It's also more clear what the message will actually look like when replacing it.

2021-08-03 09:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
> +    protected final MessageBuilderDelegate delegate = DelegateFactory.createMessageBuilderDelegate();
Name has to be updated correspondingly

2021-08-03 09:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +    public CompletableFuture<Message> replaceMessage() {
I think calling them quiet similar would be better as you get all possible update methods when you type the first few letters. Something like `updateApplyChanges` and `updateReplace` but the mentioned names are probably not that nice. Maybe you know something better

2021-08-03 09:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +            // Discord now supports multiple embeds for Discord bots.
Remove the comment as it's not helpful in any way

2021-08-03 09:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +
Remove line

2021-08-03 14:49 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
> +abstract class MessageBuilderBase<T> {
But it's also not the base of a message ... :D
I think it's not critical to have a "correct" name here, even tho I think the name is fine anyways.
The updater sends a request to Discord, and is thereby building a new state of the message that's returned afterwards.
I don't really know a better name tbh.

2021-08-03 14:49 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
> +    protected final MessageBuilderDelegate delegate = DelegateFactory.createMessageBuilderDelegate();
So you mean like "MessageBuilderBaseDelegate" (assuming that we keep the name of the base)?

2021-08-03 14:51 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +    public CompletableFuture<Message> replaceMessage() {
Hmm...
What about sth like
``applyChanges``
and
``applyReplacing``

2021-08-03 14:52 UTC, coaxial1 commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
> +            // Discord now supports multiple embeds for Discord bots.
It's not from me, but yeah we can remove it

2021-08-03 15:01 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
> +abstract class MessageBuilderBase<T> {
As this is also a class you wouldn't interact with normally I think if someone finds a better name we can change it without hesitation as this would normally be a breaking change. So I guess leave it for now 🤔

2021-08-03 15:03 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
> +    protected final MessageBuilderDelegate delegate = DelegateFactory.createMessageBuilderDelegate();
As I thought we would rename the class I just mentioned it here. But we should probably update it to include "base" as it's for exactly this class

2021-08-03 15:05 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
> +abstract class MessageBuilderBase<T> {
Mhm. I mean it's still in the API package, but abstract so I wouldn't say that a user would usually use that type anywhere

2021-08-03 15:37 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +    public CompletableFuture<Message> replaceMessage() {
It's always `replace` that doesn't sound good to me. What do you think about `applySwap` or `applyExchange` ? 
Maybe this is also a bad Idea and applyChanges and replaceMessage are just fine. Just thought about having a uniform update method would be easier for new users 😕

2021-08-03 23:20 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +    public CompletableFuture<Message> replaceMessage() {
We could use ``updateChanges()`` or ``updateEverything()``?
Dunno. I also think that the existing names are fines. I wouldn't type any letter. I would type a dot and then have the IDE suggest the available methods, which would show both

2021-08-04 06:44 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageUpdater.java
> +    public CompletableFuture<Message> replaceMessage() {
Hm, then I guess we should leave it as it is currently.

2021-08-04 06:58 UTC, KILLEliteMaste requested changes

2021-08-04 06:58 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
>          if (embeds.size() != 0) {
You can replace this with `prepareEmbeds`. You should also replace the loop in the method with the used one here as the one in the method is has a hardcoded limit.

2021-08-04 06:58 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
> +    }
Should be moved to the other `prepare*` methods below

2021-08-04 15:42 UTC, KILLEliteMaste approved these changes

2021-08-04 15:52 UTC, merged