Add addIntents and setNonPrivilegedIntentsAnd method to DiscordApiBuilder
Javacord/Javacord pull request #812
Opened 2021-07-11 14:01 UTC by ShindouMihou

This adds the two methods: `addIntents(...)` which adds the specified intents to the current list (or default) and also `setNonPrivilegedIntentsAnd(...)` which is basically setting the default intents together with the intents specified, though it's probably better to use `addIntents(...)` instead since it does the same thing (as long as you don't set anything else).

2021-07-22 09:22 UTC, ShindouMihou commented
Fixed conflicting merges and rebased successfully.

2021-07-22 13:32 UTC, KILLEliteMaste requested changes

2021-07-22 13:32 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
> +     * Adds the intents specified.
Change to `Adds the given intents to the already set`

2021-07-22 13:32 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/internal/DiscordApiBuilderDelegate.java
> +     * intents.
Change to `Adds the given intents to the already set`

2021-07-22 13:32 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/DiscordApiBuilderDelegateImpl.java
> +                .filter(intent -> !this.intents.contains(intent))
No need to filter as `intents` is a Set

2021-07-23 06:04 UTC, ShindouMihou commented on javacord-core/src/main/java/org/javacord/core/DiscordApiBuilderDelegateImpl.java
> +                .filter(intent -> !this.intents.contains(intent))
Realized that when I first sent the PR but forgot to change. 😓

2021-07-23 09:23 UTC, KILLEliteMaste approved these changes

2021-07-23 09:23 UTC, merged