Add method to manually request members + ServerMembersChunkEvent
Javacord/Javacord pull request #818
Opened 2021-07-21 16:14 UTC by Bastian

2021-07-22 13:57 UTC, KILLEliteMaste requested changes

2021-07-22 13:57 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    void requestMembers();
I think this shouldn't be called `requestMembers` as this would probably be more appropiate for this endpoint https://discord.com/developers/docs/resources/guild#list-guild-members . You could rename it to i.e. `requestMemberChunks` or `initiateMemberChunksRequest`.

2021-07-22 13:57 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/event/server/member/ServerMembersChunkEvent.java
> +    List<User> getMembersChunk();
Although `getMembersChunk` is a bit more descriptive(and maybe also a bit wrong as you dont get a chunk but the members out of it) where you get the members from I think `getMembers` is sufficient as it should be clear that you get the members from the chunk event

2021-07-22 13:57 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/event/server/member/ServerMembersChunkEventImpl.java
> +     * Creates a new server member join event.
Wrong Javadoc

2021-07-22 13:57 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildMembersChunkHandler.java
> +
Remove line

2021-09-10 15:19 UTC, AyuAi approved these changes
Mostly reviewing for extra visibility, as I now have a need for this feature; Would be nice to have it staged sooner rather than later :D (And huge ty for even making this PR for when I needed to make my own Member Cache <3)

PR looks good to me otherwise. I generally agree with @KILLEliteMaste's comments, but they are simply semantical tbf

2021-09-10 15:19 UTC, AyuAi commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +    void requestMembers();
I think `requestMembersChunk` makes the most sense, since `request` implies a REST request, and the data being acquired is a Member Chunk

2021-09-10 15:19 UTC, AyuAi commented on javacord-core/src/main/java/org/javacord/core/event/server/member/ServerMembersChunkEventImpl.java
> +     * Creates a new server member join event.
```suggestion
     * Creates a new server members chunk event.
```

2021-09-27 21:01 UTC, Milo123459 commented
Any updates?

2021-11-24 12:05 UTC, merged