Elevate getAvatarHash to User
Javacord/Javacord pull request #843
Opened 2021-08-08 17:11 UTC by AyuAi

This PR is to make the `UserImpl.getAvatarHash` from the `javacord-core` accessible via the `User` class.

This is important, at least for me (and anyone else who wants to manage their own cache), so that the raw hash can be easily accessible / stored on the Javacord user's end. I am actually currently running on a patch myself (https://github.com/AyuAi/Javacord/commit/55e8ecb8d70d9469ff26329a5afff32b028be4a0) that elevated this method because I needed access to it to implement my own member/user cache on top of Javacord.

2021-08-08 17:16 UTC, coaxial1 requested changes

2021-08-08 17:16 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/user/User.java
> +
If you're converting this to a public API, this must return an ``Optional<String>``, as users without avatar won't have an avatar hash.

2021-08-08 17:17 UTC, AyuAi commented on javacord-api/src/main/java/org/javacord/api/entity/user/User.java
> +
Ah, you are right. That's a good point

2021-08-08 17:22 UTC, AyuAi commented on javacord-api/src/main/java/org/javacord/api/entity/user/User.java
> +
https://github.com/Javacord/Javacord/commit/45ebb0437b87d93eaebddddc94cb7b1e88c0fc84

2021-08-08 17:24 UTC, coaxial1 commented
This won't compile.
Also, make sure to check all locations where the original ``getAvatarHash`` method is used, and adjust all affected code accordingly to deal with the new optional return type. :)

2021-08-08 17:29 UTC, AyuAi commented
> This won't compile.
> Also, make sure to check all locations where the original `getAvatarHash` method is used, and adjust all affected code accordingly to deal with the new optional return type. :)

Aw heck, you right. Idk why I thought it was a quick change lol

2021-08-08 17:50 UTC, AyuAi commented
Unrelated tangent, but I hate how VSCode wont import Javacord as a Java project.. 🙃

2021-08-08 17:58 UTC, coaxial1 commented
That's why you'd usually use IntelliJ for Java development xD

2021-08-08 17:58 UTC, coaxial1 approved these changes
LGTM!

2021-08-08 18:06 UTC, AyuAi commented
> That's why you'd usually use IntelliJ for Java development xD

Lame

2021-08-09 12:15 UTC, coaxial1 commented
Hey @AyuAi if you rebase your PR onto latest dev, we can merge it :)

2021-08-09 15:48 UTC, AyuAi commented
> Hey @AyuAi if you rebase your PR onto latest dev, we can merge it :)

Rebased! c:

2021-08-09 17:11 UTC, merged