Move from deprecated "embed" field to "embeds" in UncachedMessageUtil.
Javacord/Javacord pull request #848
Opened 2021-08-14 14:16 UTC by KILLEliteMaste

- Added MessageBuilderBase#addEmbeds(List<EmbedBuilder>)
- Switched the edit methods in Message from using the static edit methods to using the MessageUpdater.
- Message#edit, MessageEvent#editMessage and UncachedMessageUtil#edit methods now take a list of embeds instead of a single embed(breaking change)

2021-08-14 14:20 UTC, ShindouMihou commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> edit(List<EmbedBuilder> embeds) {
Can't we allow single embeds as well by simply using `Collections#singletonList` since changing this method up will probably break a pile load of stuff. I don't really see why adding a convenience method to prevent this from being a breaking is not possible?

2021-08-14 14:36 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> edit(List<EmbedBuilder> embeds) {
It is of course possible but I've chosen to go this way as it is probably better to have 1 way of doing it than multiple and otherwise we would have to overload the method so many times you cannot really keep track of them anymore. Furthermore I think it is also more confusion to the users as they differentiate just for 1 argument.
If the demand is really that high for a single embed param we could add the methods back but I am against it.

2021-08-14 14:39 UTC, ShindouMihou approved these changes

2021-08-14 20:13 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> edit(List<EmbedBuilder> embeds) {
Why don't we use ``EmbedBuilder... embeds`` instead to keep it non-breaking?

2021-08-14 20:42 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> edit(List<EmbedBuilder> embeds) {
We could but is it really such a big deal? This PR will stay a breaking change even if we decide to change it because of
```java
static CompletableFuture<Message> edit(DiscordApi api, long channelId, long messageId, String content,
                                        boolean updateContent, EmbedBuilder embed, boolean updateEmbed)
```
which would need to be adjusted.
It may also be a personal preference but I think having a list as param is also more common to use instead of an array. And if I had to add multiple embeds dynamicaly I would have convert my embed list to an array which would look kinda weird `List.of(embed1, embed2).toArray(new EmbedBuilder[0])` and further more a list provides just a lot more flexibility.
This PR is also aimed for version 3.5 where a lot of breaking changes will be included so I don't see why we wouldn't want to improve these methods right away.

2021-08-14 22:07 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> edit(List<EmbedBuilder> embeds) {
For example, I use the single embed method you're changing up here like at least 70 times and I'd need to refactor everything to ``message.edit(List.of(embed));`` which looks 100% weird as well.

I don't see why it's not a good idea to just offer both, if both is needed by different users with different requirements. We offer both in the MessageBuilder, so why not here?

I think it's totally fine to switch to a list for the complex edit() method you mentioned in your comment above as the list is in the middle of the parameter list (is anyone really using that method with all the flags? Probably an edge case anyways), but I really don't see why we should make the use of ``Message#edit`` less convenient than before. I want to edit my embed-only message with another embed. This was easy before, now I randomly have to wrap it in a list. This is not an improvement.

2021-08-14 22:13 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> edit(List<EmbedBuilder> embeds) {
> having a list as param is also more common to use instead of an array

Yeah I mean the method gets served an array, but this is a variadic paraemter an as such a very common thing. As a developer I can easily pass in two, or three, or more embed builders without the need to use any sort of collection.
You are right that ``edit(EmbedBuilder[] embeds)`` would be a weird and uncommon thing.

2021-08-14 22:25 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> edit(List<EmbedBuilder> embeds) {
I can see your point that you not necessarily want to always use `List.of()` if you only want to change 1 embed. But I also had the code maintainability in mind. So should we really offer both variants for each method? That would be 7 new methods. Or only for Message#edit(EmbedBuilder...) and #edit(String, EmbedBuilder...) as these are probably the most common used ones?

2021-08-15 00:17 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> edit(List<EmbedBuilder> embeds) {
I think we should offer flexibility where possible. Look at all the convenience methods we have for components. :D

Why are 7 methods a problem if they are directly next to their related one with the list parameter, respectively, and the similarity is obvious to anyone who needs to change these methods in the future? :) 
In comparision, we have 24 methods just to create a button and I still believe we'll be able to maintain that.

I think there's no good reason to remove fully working, intuitive and easy APIs that have been present since the beginning (of v3, at least).
It's 7 quick methods for us, but potentially thousands of changes that need to be done in all the Javacord projects out there, as editing a message is likely one of the most common things to do with a bot. ^_^

2021-08-15 00:33 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> edit(List<EmbedBuilder> embeds) {
For those methods where the list is in the middle of the param list, we could also still offer an overload with a singular instance like suggested by ShindouMihou above. I'd vote for this for the same reasons (offer flexibility, be easy to use). But since you don't like it, it's probably up to the others.

Side note: ``org.javacord.api.entity.message.Messageable.java`` probably deserves a similar refactoring :D

2021-08-15 10:48 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +    default CompletableFuture<Message> edit(List<EmbedBuilder> embeds) {
@coaxial1 I have reworked everything, readded and enhanced the single embed method. I also added and enhanced some methods in Messageable as you mentioned.

2021-08-19 23:24 UTC, coaxial1 requested changes
A few last thoughts :)

2021-08-19 23:24 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
> +        return api.getUncachedMessageUtil().edit(channelId,messageId,content);
No spaces? Maybe just hit the auto formatter on this file again :D

2021-08-19 23:24 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/event/message/MessageEvent.java
> +    CompletableFuture<Message> editMessage(List<EmbedBuilder> embeds);
I think we should offer the ``Embed embed, Embed... embeds`` version you have everywhere here as well in addition to the list based methods.
Also, the javadocs here are still saying "the embed" :)

2021-08-19 23:24 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/event/message/MessageEvent.java
> +    CompletableFuture<Message> editMessage(String content, List<EmbedBuilder> embeds);
Here as well.

2021-08-19 23:24 UTC, coaxial1 commented on javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
>      public InteractionMessageBuilder addEmbeds(EmbedBuilder... embeds) {
Should we have a method accepting a list here as well?

2021-08-20 08:19 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
>      public InteractionMessageBuilder addEmbeds(EmbedBuilder... embeds) {
Yes. I am adding the method but i think we would have to rework this anyway to use the MessageBuilderBase.

2021-08-20 11:19 UTC, coaxial1 approved these changes
LGTM!

2021-08-20 11:34 UTC, merged