Context Menus
Javacord/Javacord pull request #867
Opened 2021-09-22 01:59 UTC by Mysterypotatoguy

Implements Context Menus and renames some Slash Command components (SlashCommandPermissions) to generify them into Application Command components

2021-09-22 10:55 UTC, KILLEliteMaste requested changes
I didn't mention anything in the delegates as you can reflect / adjust the changes from the builder classes.

In `PermissionType` your forgot to change `USE_SLASH_COMMANDS` to `USE_APPLICATION_COMMANDS`

In `MessageType` you forgot to add `ContextMenuCommand` https://discord.com/developers/docs/resources/channel#message-object-message-types

In `RestRequestResultErrorCodes` your forgot to change `UNKNOWN_SLASH COMMAND` to `UNKNOWN_SLASH_COMMAND` and the description. And if you want you can also add the missing codes as there are quiet a few new ones or you can leave it open for another PR so we can create an issue

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandBuilder.java
> +public class SlashCommandBuilder implements ApplicationCommandBuilder<SlashCommand> {
Again, can't select it, `setName` `setDescription` `setDefaultPermissions` and both create methods can be moved to the ApplicationCommandBuilder class

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandUpdater.java
> +public class SlashCommandUpdater implements ApplicationCommandUpdater<SlashCommand> {
Same here, `setDescription` `setDefaultPermission` and the updater methods can be moved to the `ApplicationCommandUpdater`

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/UserContextMenu.java
> +    }
Can be moved to the ContextMenu interface

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/UserContextMenuBuilder.java
> +public class UserContextMenuBuilder implements ApplicationCommandBuilder<UserContextMenu> {
Same as mentioned in the `MessageContextMenuBuilder`

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/UserContextMenuUpdater.java
> +public class UserContextMenuUpdater implements ApplicationCommandUpdater<UserContextMenu> {
Same as mentioned in the `MessageContextMenuUpdater`

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
> +            List<ApplicationCommandBuilder<?>> applicationCommandBuilderList) {
This probably should be changed to 
```suggestion
            List<ApplicationCommandBuilder<? extends ApplicationCommand>> applicationCommandBuilderList) {
```

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
> +            body.add(((ApplicationCommandBuilderDelegateImpl<?>) applicationCommandBuilder.getDelegate())
Same here
```suggestion
        for (ApplicationCommandBuilder<? extends ApplicationCommand> applicationCommandBuilder : applicationCommandBuilderList) {
            body.add(((ApplicationCommandBuilderDelegateImpl<? extends ApplicationCommand>) applicationCommandBuilder.getDelegate())
```

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
> +            Server server, List<ApplicationCommandBuilder<?>> applicationCommandBuilderList) {
```suggestion
            Server server, List<ApplicationCommandBuilder<? extends ApplicationCommand>> applicationCommandBuilderList) {
```

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
> +            body.add(((ApplicationCommandBuilderDelegateImpl<?>) applicationCommandBuilder.getDelegate())
```suggestion
        for (ApplicationCommandBuilder<? extends ApplicationCommand> applicationCommandBuilder : applicationCommandBuilderList) {
            body.add(((ApplicationCommandBuilderDelegateImpl<? extends ApplicationCommand>) applicationCommandBuilder.getDelegate())
```

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/CommandType.java
> +public enum CommandType {
```suggestion
public enum ApplicationCommandType {
```

2021-09-22 10:55 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/util/handler/interaction/InteractionCreateHandler.java
> +                switch (applicationCommandType) {
What about an `ApplicationCommandEvent` ?

2021-09-26 14:16 UTC, KILLEliteMaste requested changes

2021-09-26 14:16 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java
> +
You should add a `getType` method

2021-09-26 14:16 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
>      public CompletableFuture<List<SlashCommand>> getGlobalSlashCommands() {
Another thing I came across, I think you should remove the other methods for the context menu and change this one to `getGlobalApplicationCommands`. This removes quiet a lot of code and the user can simply get the needed application commands by themself if you add the above mentioned method by `list.stream().filter(command -> command.getType == CommandType.SLASH).map(command -> (SlashCommand)command).toList()` . If we decide to not remove any methods there should be at least a `getGlobalApplicationCommands` method otherwise 3 request are needed (and at some time even more with more application command types which also need to be patched in to acces them)

2022-01-18 11:56 UTC, Saladoc requested changes
looks good (except for the one question), thanks for your work

2022-01-18 11:56 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageType.java
> +                return messageType;
How does this correctly differentiate between `NORMAL_WEBHOOK` and `NORMAL`?

2022-01-18 12:12 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageType.java
> +                return messageType;
Somehow I missed that. But what is the actual reason we have this type for? I would remove this and instead add a `isWebhookMessage` in the message or don't do it at all as you can check if the message is from a webhook by `message.getAuthor().isWebhook()`. What do you think?

2022-01-18 13:27 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageType.java
> +                return messageType;
Possible, but it should not be done on the fly as a side effect of this PR. 

We could include an if clause to catch that specific case for now, and bring forward a change request to remove `NORMAL_WEBHOOK` or adjust the enum instances to also have the proper `isWebhook` properties and check those in the loop as well.

2022-01-18 13:31 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/message/MessageType.java
> +                return messageType;
> Possible, but it should not be done on the fly as a side effect of this PR.

Yeah, I will revert this change and open another PR that will remove this for the version 3.5 breaking change release

2022-01-18 13:43 UTC, Saladoc approved these changes

2022-01-18 13:44 UTC, merged