Add min_value and max_value
Javacord/Javacord pull request #891
Opened 2021-10-18 21:31 UTC by ILGO0413

Fixes https://github.com/Javacord/Javacord/issues/889

Keep in mind that NUMBER option type can be implemented later, and depending on option type, the min/max_value format can be different.

2021-10-19 17:27 UTC, ILGO0413 commented
> 
> 
> This PR is not functional, maybe your forgot to commit something?
> 
> To keep the conversation at one place in #889 you metnioned that the methods for `INTEGER` take arguments of type `long`, I don't really get why you did it like that. And why should the methods for the `NUMBER` option implemented later and not now?

Yep, my commit is lost somehow and I am investigating what's happened. Gonna update it soon.
If 'NUMBER' option is already implemented, gonna implement min max values for it as well.

2021-10-30 18:10 UTC, KILLEliteMaste requested changes

2021-10-30 18:10 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionImpl.java
> +        return Optional.of(numberMaxValue);
Use `Optional#ofNullable` instead of `Optional#of`

2021-10-30 18:10 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionImpl.java
> +    private Double numberMaxValue;
Can be final but then you have to set them explicitly `null` depending on what type the option is in the `if` statement or `else` block

2021-10-30 18:55 UTC, ILGO0413 commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionImpl.java
> +    private Double numberMaxValue;
It can be final, but in this case we should handle 3 options:
1) type is INTEGER, set 2 integer values and set both number values as null
2) type is NUMBER. set 2 number values and set both integer as null
3) type is neither INTEGER nor NUMBER, set all 4 values as null. 
Is it OK to use 3 logical blocks for 4 variables initialization? AFAIK, Long and Double are immutable and no setters are provided

2021-10-30 18:56 UTC, ILGO0413 commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionImpl.java
> +        return Optional.of(numberMaxValue);
Shame on me. Fixed

2021-10-30 19:06 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionImpl.java
> +    private Double numberMaxValue;
Yes, that should just be ~8 more lines for variable initialization. But what does the immutability of Longs and Doubles have to do with this?

2021-10-31 08:07 UTC, ILGO0413 commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionImpl.java
> +    private Double numberMaxValue;
Well, I suppose its the main idea to define internal variable as final - to make sure it can be provided only when the object is created and it cannot be reinitialized later. Previous implementation had no 'final' keyword, but user had no possibility to set variable after object creation, and had no possibility to change the variable itself due to Long/Double immutability.

New implementation is provided, it covers all 3 options. Please compare and choose what implementation is more preferable

2021-10-31 13:00 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionImpl.java
> +    private Double numberMaxValue;
> Previous implementation had no 'final' keyword, but user had no possibility to set variable after object creation, and had no possibility to change the variable by reference itself due to Long/Double immutability.

It's not only about the user being able to change the assignment of a variable but also to prevent in the first place developers to do something that may be wrong because if you use final you have to think twice about it if that what you are doing really makes sense.

2021-10-31 13:12 UTC, KILLEliteMaste approved these changes
LGTM!
Please rebase to the latest version and resolve the merge conflicts.

2021-10-31 15:20 UTC, ILGO0413 commented
And I failed on the rebase again

2021-11-02 11:52 UTC, KILLEliteMaste requested changes
I have no idea what you are doing but the rebase really messed this up. Some previous changes are nore not applied anymore and there are still conflicts

2021-11-02 11:52 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOption.java
> +
Remove line

2021-11-02 11:52 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOption.java
> +
Remove line

2021-11-02 11:52 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionImpl.java
> +        return Optional.of(numberMaxValue);
Change to `Optional#ofNullable`

2021-11-30 20:08 UTC, Vampire commented
I hopefully resolved your merge mess and rebased onto latest `development`.
So now the history should be nice and intact.
Be aware to **NOT** do a pull with merge now, even if Git suggests to do so.

If someone made a force push, rewriting history, and you try to push a new commit, Git suggests to do a pull with merge, but this is one of the worst things you can do as you then somehow merge the old and new history and create an even bigger mess which I believe you did before to get to that state this PR was in. Just reset your local branch to the remote branch and if you had additional local commits, cherry-pick them on top for example.

2021-11-30 20:32 UTC, KILLEliteMaste approved these changes
LGTM!
@Vampire would you also be so kind to squash the commits into a single one? :)

2021-11-30 20:39 UTC, Vampire commented
Sure, no problem, done.
As you approved it I'll also push to dev when the checks are through.
I just did not do a content review, just fixed the merge-mess as I need that feature. :-D

2021-11-30 20:50 UTC, merged