Add ServerThreadChannelUpdater & ServerThreadChannelBuilder
Javacord/Javacord pull request #903
Opened 2021-10-24 07:30 UTC by ruiner189

Adds an updater for threads.
Some breaking changes: 
- Moved canCreateInstantInvite & permission methods from the ServerChannel to the new RegularServerChannel
- Moved permission methods from ServerChannel-Updater/Builder to RegularServerChannel-Updater/Builder

2021-11-04 16:12 UTC, KILLEliteMaste commented
@ruiner189 after a short internal discussion we came up with a different name `RegularServerChannel` which could replace the `PositionableServerChnnel` pretty well. Then you can move the permission methods to it's updater

2021-12-28 01:53 UTC, Vampire requested changes

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerThreadChannelUpdaterDelegate.java
> +    void setName(String name);
This is unnecessary, it is already inherited from super interface

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerThreadChannelUpdaterDelegate.java
> +     * Queues the archived to be updated.
"flag" is missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerThreadChannelUpdaterDelegate.java
> +     * Queues the locked to be updated.
"flag" is missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerThreadChannelUpdaterDelegate.java
> +     * Queues the invitable to be updated.
"flag" missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelBuilder.java
> +     * The regular server channel delegate used by this instance.
"builder" missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelBuilder.java
> +        delegate = null;
What is the point of having a `delegate` field that is always `null`?
If it ever is used, it will throw `NullPointerException`.
It only works if every subclass overwrites the methods using this field.
I guess a more correct solution would be if the subclasses supply the `delegate` in the super constructor call and do not overwrite the methods.
Or if they are expected to overwrite the methods, the field should be removed and the methods made abstract, but I think that would be the worse solution.

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelBuilder.java
> +     * @param permissionable The entity which permission overwrite should be removed.
"which" is not correct, is it?

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelUpdater.java
> +        delegate = null;
Same as for `RegularServerChannelBuilder` just that here a second constructor exists

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelUpdater.java
> +     * @param permissionable The entity which permission overwrite should be removed.
"which" is not correct, is it?

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelUpdater.java
> +     * The server channel delegate used by this instance.
"regular" and "updater" missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelUpdater.java
> +     * Creates a new server channel updater without delegate.
"regular" missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelUpdater.java
> +     * Creates a new server channel updater.
"regular" missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelBuilder.java
> +public class RegularServerChannelBuilder extends ServerChannelBuilder {
methods for (raw)position are missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +     * The server thread channel delegate used by this instance.
"updater" missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +     * Queues the archived to be updated.
"flag" missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +     * Queues the locked to be updated.
"flag" missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +     * Queues the invitable to be updated.
"flag" missing

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
What about a `ServerThreadChannelBuilder`, is that not possible?

2021-12-28 01:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactoryDelegate.java
>       * @return A new server channel updater delegate.
"regular" missing

2021-12-28 01:53 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/entity/channel/RegularServerChannelBuilderDelegateImpl.java
> +        if (permissionOverwrites != null) {
Is there a reason for this unnecessary check?
The only time this is `null` is, if the added sizes are 0 which means the for-loops below will not be entered anyway.

2021-12-28 01:53 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/entity/channel/RegularServerChannelImpl.java
> +public class RegularServerChannelImpl extends ServerChannelImpl implements RegularServerChannel {
Shouldn't also here all the permission related methods be moved down to `RegularServer...`?

2021-12-28 01:53 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/entity/channel/RegularServerChannelUpdaterDelegateImpl.java
> +    public CompletableFuture<Void> update() {
Why is this overwritten?
The only difference to the superclass is, that it does not support audit log reason.
Does it not support audit log reason?
Then it would be bad that you can still set it on the updater but it is just silently ignored.

2021-12-28 01:53 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/entity/channel/ServerThreadChannelUpdaterDelegateImpl.java
> +        super.prepareUpdateBody(body);
This should be called in this classes `prepareUpdateBody` architecturally.
And also like it is, its return value is ignored, so if you just want to update a threads name, the update request will not be done.

2021-12-28 01:53 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/entity/channel/ServerThreadChannelUpdaterDelegateImpl.java
> +    public CompletableFuture<Void> update() {
Why is this overwritten? The only difference to the superclass is, that it calls the superclass `prepareUpdateBody` which is misplaced here anyway.

2021-12-28 11:22 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelBuilder.java
> +        delegate = null;
Actually that's how it has been done in the past. The methods are also overwritten in i.e. ServerTextChannelBuilder and the other types but I will change this

2021-12-28 11:30 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelBuilder.java
> +        delegate = null;
Yeah, seen that after I wrote the comment, but perfect opportunity to improve the code quality here. :-)

2021-12-28 15:30 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
Possible for sure. Currently it's done through a `Message` or `ServerTextChannel` where you can call `createThread` or `createThreadForMessage` and I am not sure if it makes sense to add a builder for threads too atm as they would also split into 2 builder because of a thread with message and without. As they also have not that many possible arguments atm I would vote for only having the `createThread` methods. 
https://discord.com/developers/docs/resources/channel#start-thread-with-message
What do you think?

2021-12-28 15:37 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
Hm, well, it just felt a bit inconsistent.
For all other types we have a builder and we have an updater than can be constructed directly or through the object to be updated.

2021-12-28 15:40 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
Also why would we need two builders?
One could handle both cases, couldn't it?
You have one constructor that takes a message and one constructor that takes type and invitable flag.

2021-12-28 15:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
Yeah but I thought as they differentiate in the possible arguments we should not offer these methods to set. Or is it just for the sake of completeness and be able to do whatever you want with the builder in case something changes from discords side?

2021-12-28 15:53 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
Not sure what you mean.
Besides one takes type and invitable and the other takes a message, they have the same possibilities, don't they?
There would be no setters for message, invitable, and type.

Btw. while talking about it, the updater has a field for invitable flag.
This is probably also bad if that flag is not valid for message-based threads?

2021-12-28 15:57 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
I am not sure but the docs don't mention anything https://discord.com/developers/docs/resources/channel#modify-channel-json-params-thread

2021-12-28 15:58 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
![Uploading grafik.png…]()

2021-12-28 15:59 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
![grafik](https://user-images.githubusercontent.com/325196/147584219-9a598a4e-d707-4351-affc-82d915d6c675.png)

2021-12-28 16:01 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
It seems to even not only be in non-message threads, but only on private threads.
Actually that's also what the "start a thread" docs say:
![grafik](https://user-images.githubusercontent.com/325196/147584396-522ecdae-1a74-4773-90d4-bd4725567636.png)

2021-12-28 16:02 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
This "only for private threads" might fall under the category "we don't check it in Javacord, but let Discord validate that" though.

2021-12-28 16:04 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelUpdater.java
> +public class ServerThreadChannelUpdater extends ServerChannelUpdater {
Ah yeah just saw it. I guess mentioning in the javadoc that this only works for private threads might be enough

2021-12-28 20:06 UTC, Vampire requested changes
A few more minor things

2021-12-28 20:17 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerChannelUpdater.java
>       * Creates a new server channel updater without delegate.
Not sure, you wrote this :D

2021-12-28 20:27 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerChannelUpdater.java
>       * Creates a new server channel updater without delegate.
Well, there it was probably correct as delegate was null, but you kept it and even added it to the other. :-P

2021-12-28 23:13 UTC, Vampire requested changes
Aaaalmost there :-)

2021-12-28 23:13 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannelBuilder.java
> +     * Creates a new regular server channel builder delegate.
-"delegate" too

2021-12-28 23:13 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerChannelBuilder.java
> +     * Creates a new server channel builder delegate.
-"delegate" too

2021-12-28 23:13 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerChannelUpdater.java
> +     * Creates a new server channel updater delegate.
-"delegate" too

2021-12-28 23:13 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerChannelUpdater.java
> +     * Creates a new server channel updater delegate.
-"delegate" too

2021-12-28 23:13 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerStageVoiceChannel.java
> +    default Optional<? extends ServerStageVoiceChannel> getCurrentCachedInstance() {
Here no extends is necessary as long as there is no further subclass

2021-12-28 23:13 UTC, Vampire commented on javacord-api/src/main/java/org/javacord/api/entity/channel/ServerStageVoiceChannel.java
> +    default CompletableFuture<? extends ServerStageVoiceChannel> getLatestInstance() {
Here no extends is necessary as long as there is no further subclass

2021-12-28 23:13 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/audio/AudioConnectionImpl.java
> +     * M
"M"?

2021-12-28 23:28 UTC, KILLEliteMaste commented
Okay, but now there shouldn't be anything left 😃

2021-12-28 23:30 UTC, Vampire approved these changes
Well, I'm not going to surch further. :-D
lgtm now.
Feel free to bring it over after you combined it into 1 or 2 commits, the sooner the better for me. :-)

2021-12-28 23:41 UTC, merged