Add member timeouts
Javacord/Javacord pull request #948
Opened 2022-01-21 18:00 UTC by KILLEliteMaste

2022-01-28 18:20 UTC, Tigerpanzer02 commented
Just adding some information to that pr from the official discord documentation
https://dis.gd/timeout

2022-03-07 14:45 UTC, Saladoc requested changes
Looks good overall, but I've marked some spots that seemed odd to me. 
Some suggestions I made would need to be applied in more than one place.

2022-03-07 14:45 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerUpdaterDelegateImpl.java
> +                updateNode.put("communication_disabled_until",timeout);
According to the [docs](https://discord.com/developers/docs/resources/guild#modify-guild-member) the timeout, if to be removed, should be set to `null`. Even if we internally use `Instant.MIN` as a magic value, we should try to conform to discord's API to the best of our ability

2022-03-07 14:45 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/listener/user/UserChangeTimeoutListener.java
> +public interface UserChangeTimeoutListener extends ServerAttachableListener, UserAttachableListener,
Does this also fire when a timeout expires or only if it is manually unset? Do we get gateway events for expiring timeouts?

2022-03-07 14:45 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/user/User.java
> +     * @return The timestamp of when this will no longer be timeout or an Instant in the past.
```suggestion
     * @return The timestamp of when this user will no longer be timed out. Empty, if user is currently not timed out.
```

2022-03-07 14:45 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/ServerUpdater.java
> +
Also include a method to queue the user's timeout to be unset.

2022-03-07 14:45 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +
What do you think of also adding convenience methods with a `User, Duration` signature to make "timeout this user for 48 hours starting now" style calls easier?

```suggestion

    /**
     * Timeout the given user on this server.
     *
     * <p>If you want to update several settings at once, it's recommended to use the
     * {@link ServerUpdater} from {@link #createUpdater()} which provides a better performance!
     *
     * @param user    The user.
     * @param duration The duration how long the user should be timed out.
     * @param reason  The audit log reason for this update.
     * @return A future to check if the update was successful.
     */
    default CompletableFuture<Void> timeoutUser(User user, Duration timeout, String reason) {
        return createUpdater().setUserTimeout(user, Instant.now().plus(duration)).setAuditLogReason(reason).update();
    }
```

2022-03-07 14:45 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * @param timeout The timestamp until the user should be timeout,
```suggestion
     * @param timeout The timestamp until the user should be timed out,
```

2022-03-07 14:45 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * @param timeout The timestamp until the user should be timeout,
```suggestion
     * @param timeout The timestamp until the user should be timed out,
```

2022-03-07 14:45 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * The returned Instant may be in the past which indicates that the user is not timed out.
If the user is not timed out, the returned optional should be empty.

2022-03-07 14:45 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/entity/user/Member.java
> +     * @return The timestamp of when this will no longer be timeout or an Instant in the past.
```suggestion
     * @return The timestamp of when this member will no longer be timed out.
```

2022-03-07 14:45 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/entity/user/MemberImpl.java
> +        return Optional.ofNullable(communicationDisabledUntil);
If the timeout is expired, the returned optional should be empty
```suggestion
        return Optional.ofNullable(communicationDisabledUntil).filter(Instant.now()::isBefore);
```

2022-03-07 17:17 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/listener/user/UserChangeTimeoutListener.java
> +public interface UserChangeTimeoutListener extends ServerAttachableListener, UserAttachableListener,
It doesn't. Seems to fire only when its manually changed

2022-03-07 17:20 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * The returned Instant may be in the past which indicates that the user is not timed out.
Should this be added to the Javadoc? Or do you mean to change the behavior?

2022-03-07 19:59 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +     * The returned Instant may be in the past which indicates that the user is not timed out.
Both. The behavior is changed in another suggestion, but the javadoc should also be changed accordingly. I feel that if you get a non-empty optional the question should not be whether but rather how long the user is timed out.

2022-03-07 20:05 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/entity/user/MemberImpl.java
> +        return Optional.ofNullable(communicationDisabledUntil);
I see, that's a legit case too. Maybe two functions? `getTimeout()` and `getActiveTimeout()`?

2022-03-07 21:09 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +
Personally I think the use case would be minimal and just clutter the API. I can imagine the use case of timeouts would be to integrate it into moderation bots where mods can timeout a user with a command `/timeout Domme 12` and then the convenience methods are useless. And the time range is just so huge (+28days) so what would be the most used times to make convenience methods for?

2022-03-08 17:54 UTC, bassner commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +
I think Saladocs suggestion (the code above) is a good idea. With your current implementation, you need to calculate the target instant / timestamp yourself.
With the suggest additional method, you can go like
```java
server.timeoutUser(user, Duration.ofHours(12));
```

2022-03-08 18:17 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
> +
Oh, I totally misunderstood what he meant. Indeed, this is a good idea

2022-03-09 16:45 UTC, bassner approved these changes
Code LGTM! 👍

2022-03-10 17:47 UTC, Saladoc approved these changes
LGTM overall. Two quick questions, but if you don't think they warrant further changes we can skip them and merge.

2022-03-10 17:47 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/ServerUpdater.java
> +        return setUserTimeout(user, Instant.now().plusSeconds(duration.getSeconds()));
Is there a particular reason to not just use `Instant.now().plus(duration)`?

2022-03-10 17:47 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/internal/ServerUpdaterDelegate.java
>      /**
Should we also have the `setUserTimeout(User, Duration)` method here?

2022-03-10 18:43 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/internal/ServerUpdaterDelegate.java
>      /**
You have missed it, I added it with the previous changes too

2022-03-10 18:45 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/server/ServerUpdater.java
> +        return setUserTimeout(user, Instant.now().plusSeconds(duration.getSeconds()));
When I tried what you did, it was red underlined by the IDE. Now when I tried it again it works. Maybe it was because at that moment my system was under heavy load and it took way to long to visualize it as valid

2022-03-10 18:46 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/entity/server/internal/ServerUpdaterDelegate.java
>      /**
ah yeah nevermind it should not be on the delegate as that's internal - I didn't properly read the class name.

2022-03-10 18:53 UTC, merged