Add teams
Javacord/Javacord pull request #968
Opened 2022-03-07 14:13 UTC by Saladoc

This is #615 updated and expanded. 

Probably the most controversial change is how `getOwner()` and `getOwnerId()` are handled. No existing behavior is broken, however:

If an application (like our bot) is owned by a Team, the ownerId field will be the team ID for the owner, there may be a pseudo user with the team id, the username `team[teamid]` etc. 

To preserve api stability, if a team is the owner of the application, the `getOwner()` and `getOwnerId`  methods will return the owner of the team. This way, we don't need to break `getOwner()` and make it return `Optional<User>`.

2022-03-07 16:40 UTC, KILLEliteMaste requested changes

2022-03-07 16:40 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
> +        return team != null ? ownerId : team.getOwnerId();
`applicationInfo.flatMap(ApplicationInfo::getTeam).map(Team::getOwnerId).orElseGet(() -> ownerId)`

2022-03-07 16:40 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/team/TeamImpl.java
> +     * Creates a new user.
```suggestion
     * Creates a new Team.

```

2022-03-07 16:40 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/team/TeamImpl.java
> +     * @param data The json data of the user.
```suggestion
     * @param data The json data of the Team.

```

2022-03-07 16:40 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/activity/ApplicationInfoImpl.java
>          ownerDiscriminator = data.get("owner").get("discriminator").asText();
Imo we should change the datatype to return an Optional. There should be either a user owner or a team owner. Mixing these fields is not a good idea as it also somewhat doesn't make sense to return the team name as the owner name or a weird self created owner discriminator.

2022-03-10 21:20 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/DiscordApi.java
> +
So do we remove the `getOwnerId()` and `getOwner()` methods from Discord Api as well? because that too is part of the Application Info.
The main problem here is that before, an applications owner was static. Now, applications can be transferred from single users to teams and the team members can change. The application info is requested once on startup and then cached. If `getApplicationInfo()` is called, the cache is updated. For a long time, that only was relevant for when the bot description changed or the application name, whether the bot was public etc. 

I'll think this over once more. Obviously, owner info and team info are the most relevant parts of the ApplicationInfo when it comes to bots since they might be relevant for permissions etc so if it is feasible, they should be made available directly from the api object. But we also shouldn't duplicate information all over the place.

2022-03-10 23:05 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/DiscordApi.java
> +
Or to be more precise I basically wonder why we don't provide a cached ApplicationInfo rather than the cached team. Currently we only have a method to request it, but why shouldn't we allow the user to access a cached instance? Doing this would also save us 2 variables in the `DiscordApiImpl` which then are no longer needed anymore. And this would also automatically update everything dependent like the team without needing to assign it again.

2022-05-16 18:51 UTC, KILLEliteMaste commented
What's the state of this? As far as I see only the last requested change needs to be done and then it can be merged

2022-06-26 15:55 UTC, Saladoc commented
Alright, time to get this under wraps. Here's the short notes:
 - Previous owner info has been encapsulated in a separate class
 - Previous methods have been kept (some with changed signatures -> breaking change), deprecated and marked for removal in the subsequent release
 - Either `Owner` or `Team` is present on an Application Info instance. Both are `Optional<>`

2022-07-08 14:10 UTC, KILLEliteMaste requested changes

2022-07-08 14:10 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/team/TeamImpl.java
> +        id = Long.parseLong(data.get("id").asText());
```suggestion
        id = data.get("id").asLong();

```

2022-07-08 14:10 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/team/TeamImpl.java
> +        iconHash = data.has("icon") ? data.get("icon").asText() : null;
```suggestion
        iconHash = data.path("icon").asText(null);

```

2022-07-08 14:10 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
> +                                    ready.complete(this);
Shouldn't you assign the `ApplicationInfo` in here?

2022-07-08 15:17 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/DiscordApi.java
> +    default CompletableFuture<Optional<User>> getOwner() {
The alternative I first went with, but then never commited was returning `CompletableFuture<User>` and returning a failed future with `NoSuchElementException` if there was no owner. Would you prefer that? Personally I found it more important to encode the possiblilty that there might not be an owner.

The best way here would probably be to mimic `EmbedAuthor#downloadIconAsBufferedImage` and return `Optional<Completablefuture<User>>` to drive home the point that there might be situations where there is no chance of obtaining a user at all.

2022-07-08 15:23 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
> +                                    ready.complete(this);
That *could* prove helpful, yes.

2022-07-19 18:24 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/DiscordApi.java
> +    default OptionalLong getOwnerId() {
We don't really have precedent for using `OptionalLong` over `Optional<Long>` anywhere else, is this something we want to start doing?

2022-07-19 20:11 UTC, Saladoc commented on javacord-api/src/main/java/org/javacord/api/DiscordApi.java
> +    default OptionalLong getOwnerId() {
Probably not. If we do, we'll want to change it everywhere but that's out of scope for this PR. I honestly forgot we had `Optional<Long>` elsewhere.

2022-07-21 13:12 UTC, Mysterypotatoguy approved these changes

2022-07-21 13:34 UTC, KILLEliteMaste requested changes
Otherwise it LGTM! Rebase + squashing commits.

2022-07-21 13:34 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/team/TeamImpl.java
> +
Remove lines

2022-07-21 19:37 UTC, KILLEliteMaste approved these changes

2022-07-21 19:39 UTC, Saladoc commented
@all-contributors please add @Joshix-1 for code

2022-07-21 19:43 UTC, merged

2022-07-21 20:16 UTC, KILLEliteMaste commented
@all-contributors please add @Joshix-1 for code