Add `requestBan` to access individual bans
Javacord/Javacord pull request #970
Opened 2022-03-08 01:22 UTC by AyuAi

2022-03-08 02:04 UTC, AyuAi commented
Also, unrelated to this PR but still a small nit, maybe `getBans()` should be renamed to `requestBans()` to match the more "requestX" name-scheme used for REST-request methods 👀

2022-03-08 07:22 UTC, AyuAi commented
Drafting the PR to make some last-minute optimizations to the current code that uses `getBans()` when it does not need to 👀 Will make the change later

2022-03-08 07:50 UTC, AyuAi commented on javacord-core/src/main/java/org/javacord/core/event/server/member/ServerMemberBanEventImpl.java
> +                .thenApply(ban -> Optional.of(ban));
It's worth noting that we have a weird predicament here with the method's return type. The Optional does not actually serve any use here, and we'd be better off removing it and making this a simple `CompletableFuture<Ban>`, but that would make this a non-backwards-compatible PR.

I still think this change should be merged though, simply because a single request with some redundant Optional casting is far better than requesting the entire ban list to check for a single ban.

2022-03-08 17:48 UTC, bassner commented
Your PR is breaking anyways. Right now, Javacord returns an empty optional if the ban doesn't exist. Now, it would throw an exception that has to be catched. Since it's breaking, you can just change it to a raw ban in my opinion. That way, people using the new version can't overlook that breaking change as they need to adapt the code for it to compile 🤷

2022-03-08 19:04 UTC, AyuAi commented
> Your PR is breaking anyways. Right now, Javacord returns an empty optional if the ban doesn't exist. Now, it would throw an exception that has to be catched. Since it's breaking, you can just change it to a raw ban in my opinion. That way, people using the new version can't overlook that breaking change as they need to adapt the code for it to compile 🤷

This is actually not fully true, because the user needs to handle the `CompletionException`s since this is a `CompletableFuture` already. However, I agree that the expectation before was that exceptions should rarely happen, and this new change implies exceptions to happen more frequently. Definitely a not-so-good oversight on my part.

I could add an `exceptionally(ex -> ex instanceof NotFoundException ? Optional.empty() : throw ex)`, if I am not mistaken with how exceptions work on the futures. That should restore the behavior as-expected 👀 This doesn't *have* to be breaking unless we want it to be.

2022-03-08 19:38 UTC, AyuAi commented
There, should be fixed 😊 Now if I understand correctly, the change should be more-or-less exactly as it was before. 

If the ban isn't missing, the `Optional` is filled. If the ban *is* missing, the `Optional` is empty. And, if there's any exception along the way (not counting one that indicates `NotFoundException`), the `CompletableFuture` completes exceptionally, as it did before

2022-03-09 16:53 UTC, bassner commented on javacord-core/src/main/java/org/javacord/core/event/server/member/ServerMemberBanEventImpl.java
> +                    throw new CompletionException(ex);
Yeah you should change like you suggested, otherwise you end up with two nested CompletionExceptions

2022-03-09 17:37 UTC, AyuAi commented on javacord-core/src/main/java/org/javacord/core/event/server/member/ServerMemberBanEventImpl.java
> +                    throw new CompletionException(ex);
I do agree, though, that exceptions for "not found" are a bit odd to me (and always have been).

2022-03-10 18:04 UTC, Saladoc commented on javacord-core/src/main/java/org/javacord/core/event/server/member/ServerMemberBanEventImpl.java
> +                    throw new CompletionException(ex);
Overall both feel weird, but imo the `CompletableFuture<Optional<Ban>>` is the less wrong one, since it offers a proper and trivial distinction between the cases 
 - the request failed (-> exceptionally)
 - the request executed successfully but there was no Ban to request. (-> empty optional)

The main reason for this is that the call returning no Ban is an expected, possible result and therefore does not warrant  completing exceptionally. Any requestXY method should only complete exceptionally if there was an issue with the request itself OR if the requested object should be guaranteed to be available. If the object is not guaranteed to be present, the Future should wrap an optional.

2022-03-10 18:13 UTC, Vampire commented on javacord-core/src/main/java/org/javacord/core/event/server/member/ServerMemberBanEventImpl.java
> +                    throw new CompletionException(ex);
That would be a major refactoring that needs to be done to all methods then though.
Having it like this here would be inconsistent with the rest of Javacord.
For example `getUserById` and others.
So if we really want to change that, it should probably be changed for all instances in a major refactoring action.

2022-03-10 18:15 UTC, Saladoc requested changes
Return type should be `CompletableFuture<Optional<Ban>>` to be consistend with the other apis for requesting things that might not exist.

If this should be changed in general it should be done consistently over the whole api which would be out of scope for this PR.

2022-03-10 18:50 UTC, Saladoc commented
Then we are already inconsistent. See the links in my previous comment.

2022-03-10 19:03 UTC, Vampire commented
As I said, those are different.

First link: That is what we talk about and in the current implementation there is no exception from Discord but all bans are requested and then filtered by user

Second link: If the message was deleted in the meantime you get an exceptional completion of the future, only if the message requesting was successful you get an optional as then all reactions are there and filtered by the emoji

Third link: If the returned JSON has no `user` field, there will be an empty `Optional`. But if the user id is already known, the user is requested from Discord and if it is not available, the completable future will complete exceptionally.

We do **NOT** translate exceptions from Discord, but forward them to the user just like we also do not do validations locally that Discord is doing server-side already. If those links would be `CompletableFuture<Foo>`, then we would need to actively throw a new exception in the cases where we currently return an empty `Optional` and that would be unnice.

2022-03-10 19:04 UTC, Saladoc approved these changes

2022-03-10 20:38 UTC, bassner approved these changes
I think we can merge this as it fits in the current way Javacord handles not found stuff. It's breaking, but that's fine.

In the long run we might want to rethink forwarding "Not Found" errors through Exceptions

2022-03-10 21:14 UTC, bassner commented
@AyuAi Could you rebase the PR onto the latest development commit? :)

2022-03-11 03:00 UTC, AyuAi commented
> @AyuAi Could you rebase the PR onto the latest development commit? :)

There is a button to do this in GitHub now btw c:
But yes, done

2022-03-11 08:16 UTC, merged