Updated Discord api version
Javacord/Javacord pull request #994
Opened 2022-05-13 19:58 UTC by RealYusufIsmail

I have updated the discord api version to 10

closes #960

2022-05-13 20:44 UTC, KILLEliteMaste reviewed
1. Your change does not work, it should be `10`
2. You have not done any changes mentioned in the changelog of the v10. The link is in the issue.

2022-05-13 20:45 UTC, RealYusufIsmail commented
oh ok

2022-05-14 22:31 UTC, KILLEliteMaste requested changes
Since the attachments for messages are now removed when editing their attachments, this is a breaking change and the MessageUpdater needs to be updated properly to be able to use the new feature.
The changelog also states `/channels/<channel_id>/threads/active has been removed` which you did not

2022-05-14 22:31 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +            }
Why?

2022-05-14 22:31 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
> +     */
Why did you add / edit the Javadoc in the implementation and not in the interface available in the API module?

2022-05-14 22:31 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/intent/Intent.java
> +    MESSAGE_CONTENT(15, false),
This is a privileged intent, so it has to be true

2022-05-16 17:28 UTC, KILLEliteMaste commented
> <img alt="Screenshot 2022-05-16 at 16 43 12" width="1093" src="https://user-images.githubusercontent.com/67903886/168631787-3e3bf50a-3d27-4a27-95d4-983c7863a843.png">
> 
> It is not there

Then we have this endpoint not implemented. I thought we support everything for threads but then it doesn't seem like that.

2022-05-17 12:21 UTC, RealYusufIsmail commented
I will work on MessageUpdater  later today.

2022-05-17 17:06 UTC, RealYusufIsmail commented
@KILLEliteMaste what would I change with the Message updater. Like do i need to change anything in MessageBuilderBase or some other class ?

2022-05-19 13:54 UTC, KILLEliteMaste commented
> @KILLEliteMaste what would I change with the Message updater. Like do i need to change anything in MessageBuilderBase or some other class ?

I don't know, that's something you have to figure out. Since the MessageBuilderBase contains some functionality that's used by the MessageBuilder/Updater it may be possible that you need to change something even in the MessageBuilder to correctly adjust to changes in the MessageBuilderBase

2022-05-19 14:16 UTC, RealYusufIsmail commented
Ok

2022-06-24 11:12 UTC, RealYusufIsmail commented
Will start working on this today.

2022-08-05 20:43 UTC, closed without merging