Add application command localization
Javacord/Javacord pull request #995
Opened 2022-05-13 23:55 UTC by Mysterypotatoguy

Adds localization to application commands, slash command options and option choices.
as documented here [Slash command localization discord/discord-api-docs#4653](https://github.com/discord/discord-api-docs/pull/4653)

You will need to obtain the localization experiment from Discord Developers if you wish to test this yourself.

2022-05-14 00:03 UTC, ShindouMihou commented on javacord-api/src/main/java/org/javacord/api/interaction/DiscordLocale.java
> +    }
(Not reviewing but just asking out of curiosity) Isn't this equivalent to doing:
```java
private static final Map<String, DiscordLocale> instanceByCode = Arrays.stream(...)....;?
```

2022-05-14 00:06 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/interaction/DiscordLocale.java
> +    }
I believe it's a single instantiation vs instantiating this every time a new DiscordLocale instance is created.
Won't lie to you, I copied this straight from one of the other enum classes

2022-05-15 15:56 UTC, KILLEliteMaste requested changes
Most comments are just about the same Javadoc correction suggestion.

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandUpdater.java
> +     * @param localization The localization.
```suggestion
     * @param localization The command name for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
> +     * @param localization The localization.
```suggestion
     * @param localization The command name for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandBuilder.java
> +    public SlashCommandBuilder addDescriptionLocalization(DiscordLocale locale, String localization) {
Why is the description only available in the SlashCommandBuilder? According to the [Discord docs](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-structure) they are used for any application command like the `name_localizations` . You also check for the `description_localization` in the `ApplicationCommandImpl`

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandUpdater.java
> +    public SlashCommandUpdater addDescriptionLocalization(DiscordLocale locale, String localization) {
Same as in SlashCommandBuilder

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandUpdater.java
> +     * @param localization The localization.
```suggestion
     * @param localization The slash commands description for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandBuilder.java
> +     * @param localization The localization.
```suggestion
     * @param localization The slash commands description for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOptionBuilder.java
> +     * @param localization The localization.
```suggestion
     * @param localization The options name for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOptionBuilder.java
> +     * @param localization The localization.
```suggestion
     * @param localization The options description for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOptionChoiceBuilder.java
> +     * @param localization The localization.
```suggestion
     * @param localization The options name for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/internal/ApplicationCommandBuilderDelegate.java
> +     * @param localization The localization.
```suggestion
     * @param localization The application commands name for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/internal/ApplicationCommandUpdaterDelegate.java
> +     * @param localization The localization.
```suggestion
     * @param localization The application commands name for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/internal/SlashCommandBuilderDelegate.java
> +     * @param localization The localization.
```suggestion
     * @param localization The slash commands description for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/internal/SlashCommandOptionBuilderDelegate.java
> +     * @param localization The localization.
```suggestion
     * @param localization The slash command options name for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/internal/SlashCommandOptionBuilderDelegate.java
> +     * @param localization The localization.
```suggestion
     * @param localization The slash command options description for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/internal/SlashCommandOptionChoiceBuilderDelegate.java
> +     * @param localization The localization.
```suggestion
     * @param localization The slash command option choices name for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/internal/SlashCommandUpdaterDelegate.java
> +     * @param localization The localization.
```suggestion
     * @param localization The slash commands description for this localization.
```

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandImpl.java
> +        if (data.has("name_localizations")) {
Imo we should also support getting commands by localization.
https://discord.com/developers/docs/interactions/application-commands#retrieving-localized-commands
On the one side this mean all current endpoints need to include the `with_localizations` query param set to `true` and corresponding new methods need to be added where you can specify the locale in the header as mentioned in the first link.
Furthermore for that you also need to add a check here for `(name/description)_localized`

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandImpl.java
> +                    .collect(Collectors.toMap(e -> DiscordLocale.fromLocaleCode(e.getKey()), Map.Entry::getValue));
Seems to be a bit overly complex?
```java
data.get("name_localizations").fields().forEachRemaining(stringJsonNodeEntry -> nameLocalizations .put(DiscordLocales.fromLocaleCode(stringJsonNodeEntry.getKey()),stringJsonNodeEntry.getValue()));
```
When using `path` instead of `get` you should also be able to get rid of the if statement

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandImpl.java
> +        }
Same as above

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionChoiceImpl.java
> +        }
The same as in `ApplicationCommandImpl`

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionImpl.java
> +        }
The same as in `ApplicationCommandImpl`

2022-05-15 15:56 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandUpdaterDelegateImpl.java
> +        if (!nameLocalizations.isEmpty()) {
I just see this now since you add the name here(not your fault), why does `ApplicationCommandUpdaterDelegateImpl` does not have a `prepareBody` method which gets called by every extending class? I think the variables declared in the parent class should also be set there so we don't repeat ourself each time this class gets extended

2022-05-16 00:34 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandBuilder.java
> +    public SlashCommandBuilder addDescriptionLocalization(DiscordLocale locale, String localization) {
Message/User context menu commands can't have descriptions (They become empty strings), I'm not entirely sure why I left them at the top level for the application command rework, possibly for futureproofing.
Could go either way on this

2022-05-16 00:47 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandUpdaterDelegateImpl.java
> +        if (!nameLocalizations.isEmpty()) {
This would be my fault as I did most of the application command rework. I can fix it here or open a new PR after

2022-05-16 08:06 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandBuilder.java
> +    public SlashCommandBuilder addDescriptionLocalization(DiscordLocale locale, String localization) {
The `ApplicationCommand` also has a `getDescription()` method which currently returns the empty string for context menus. So I would go the route and move it to the ApplicationCommand to be futureproof as maybe some day they allow setting the description (and display it i.e. in a tooltip).

2022-05-16 08:07 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandUpdaterDelegateImpl.java
> +        if (!nameLocalizations.isEmpty()) {
It's up to you how you would like to do it :)

2022-05-22 23:47 UTC, Mysterypotatoguy commented on javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandBuilder.java
> +    public SlashCommandBuilder addDescriptionLocalization(DiscordLocale locale, String localization) {
Pulled getDescription/setDescription methods up to ApplicationCommand level

2022-05-22 23:47 UTC, Mysterypotatoguy commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandUpdaterDelegateImpl.java
> +        if (!nameLocalizations.isEmpty()) {
Will open a new PR when this is merged as I feel it's out of scope here

2022-05-23 08:58 UTC, KILLEliteMaste requested changes

2022-05-23 08:58 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
> +     * @param description The name.
```suggestion
     * @param description The description.
```

2022-05-23 08:58 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandBuilderDelegateImpl.java
> +
Move `descriptionLocalizations` and `description` to the `ApplicationCommandBuilderDelegateImpl`

2022-05-23 12:34 UTC, KILLEliteMaste approved these changes
LGTM!

2022-05-23 12:35 UTC, KILLEliteMaste approved these changes

2022-05-23 12:49 UTC, merged