Updated activity flags
Javacord/Javacord pull request #996
Opened 2022-05-14 14:31 UTC by RealYusufIsmail

This update introduces these new flags 
```
| PLAY                        | 1 << 5 |
| PARTY_PRIVACY_FRIENDS       | 1 << 6 |
| PARTY_PRIVACY_VOICE_CHANNEL | 1 << 7 |
| EMBEDDED                    | 1 << 8 |
```

This also means JOIN_REQUEST value is now 1 << 3.

2022-05-14 14:54 UTC, RealYusufIsmail commented
@KILLEliteMaste can you please check if I am missing anything.

2022-05-14 22:15 UTC, KILLEliteMaste reviewed
No idea what you did here, but you have edited the completely wrong Enum. The linked PR for the changes is not meant for the Message Activity Type as you can see here [Discord Docs](https://discord.com/developers/docs/resources/channel#message-object-message-activity-types)

2022-05-15 11:44 UTC, RealYusufIsmail commented
Ok sorry for the inconvenience

2022-05-16 15:17 UTC, RealYusufIsmail commented
I cant find the enum for this.

2022-05-16 17:47 UTC, KILLEliteMaste requested changes

2022-05-16 17:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/ActivityFlags.java
> +public enum ActivityFlags {
```suggestion
public enum ActivityFlag {
```

2022-05-16 17:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/ActivityFlags.java
> +        return null;
Javacord **NEVER** returns `null`. Instead add another enum type `UNKNOWN(-1)` and return this.

2022-05-16 17:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/ActivityFlags.java
> +     * Gets the flag of the given integer value.
```suggestion
     * Gets the activity flag of the given integer value.
```

2022-05-16 17:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/ActivityFlags.java
> +     * @return The flags' id of the given integer value.
```suggestion
     * @return The activity flag of the given integer value.
```

2022-05-16 17:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/ActivityFlags.java
> +     * @return Gets the integer value of the flag.
```suggestion
     * Gets the integer value of the activity flag.
     * @return Gets the integer value of the activity flag.
```

2022-05-16 17:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +    ActivityFlags getFlags();
From what I can see this should return a List of ActivityFlag as it says they are OR d together.

2022-05-16 17:47 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +     * @return the activity flags.
```suggestion
     * Gets the activity flags of this activity.
     * The flags describe what the payload includes.
     *
     * @return the activity flags.
```
Also don't just copy paste the description straight from the docs. As you can see above we have a structure for the Javadoc and it should also follow this.

2022-05-16 18:13 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +    ActivityFlags getFlags();
<img width="733" alt="Screenshot 2022-05-16 at 19 13 38" src="https://user-images.githubusercontent.com/67903886/168656464-4043d691-92ba-4b34-b579-b609dd00dadd.png">
Does not show it as list on the docs.

2022-05-16 18:17 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +    ActivityFlags getFlags();
Should I change it anyway.

2022-05-16 18:38 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +    ActivityFlags getFlags();
It doesn't make any sense to show any array / list type in the docs. Like it's written there, they are OR d together that would mean that besides `1000` (binary) it would also be possible to have values like `1100` which represent 2 values (in this case  SPECTATE and JOIN_REQUEST)

2022-05-16 18:41 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +    ActivityFlags getFlags();
oh ok.

2022-05-16 18:45 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +    ActivityFlags getFlags();
When it comes to how to do this you can have a look at how it's done here https://github.com/Javacord/Javacord/blob/c840cd6aa1f8a6f8e16fbda166123776d8992f29/javacord-core/src/main/java/org/javacord/core/entity/user/UserImpl.java#L75-L82

2022-05-16 19:03 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +    ActivityFlags getFlags();
Should I also make this flags an enum set

2022-05-16 19:09 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +    ActivityFlags getFlags();
Yes

2022-05-16 19:12 UTC, RealYusufIsmail commented
<img width="611" alt="Screenshot 2022-05-16 at 20 11 27" src="https://user-images.githubusercontent.com/67903886/168665250-c77ebc82-f9a9-4006-b120-504225725c76.png">
Is there any way to avoid this.

2022-05-16 19:23 UTC, RealYusufIsmail commented on javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
> +    ActivityFlags getFlags();
Ok done.

2022-05-16 19:43 UTC, KILLEliteMaste requested changes
Only 2 more small things

2022-05-16 19:43 UTC, KILLEliteMaste commented on javacord-api/src/main/java/org/javacord/api/entity/activity/ActivityFlag.java
> +    public static ActivityFlag getActivityFlagsById(int flags) {
```suggestion
    public static ActivityFlag getActivityFlagById(int flags) {
```

2022-05-16 19:43 UTC, KILLEliteMaste commented on javacord-core/src/main/java/org/javacord/core/entity/activity/ActivityImpl.java
> +        return flags;
```suggestion
        return EnumSet.copyOf(flags);
```

2022-05-16 19:55 UTC, RealYusufIsmail commented
Ok

2022-05-16 20:08 UTC, KILLEliteMaste approved these changes
LGTM!

2022-05-16 20:08 UTC, merged